## Colombia World Development Indicators Analytics

In [2]:
import pandas as pd
import numpy as np
import plotly.plotly as py
import plotly.graph_objs as go

datos = pd.read_csv("suramerica.csv").drop('Unnamed: 0', 1)
paises = ['COL']
pais_nombre = 'Colombia'

preprocessing = 'imput'
search = 'original'
year_init = 2015
year_range = 15
look_back = 3
years = range(year_init-year_range+1,year_init+1)[::-1]

agricultura     = open("Indicadores/iagricultura.txt").read().split(',')
ambiente        = open("Indicadores/iambiente.txt").read().split(',')
ayuda           = open("Indicadores/iayuda.txt").read().split(',')
ciencia         = open("Indicadores/iciencia.txt").read().split(',')
clima           = open("Indicadores/iclima.txt").read().split(',')
comercio        = open("Indicadores/icomercio.txt").read().split(',')
deuda           = open("Indicadores/ideuda.txt").read().split(',')
economia        = open("Indicadores/ieconomia.txt").read().split(',')
educacion       = open("Indicadores/ieducacion.txt").read().split(',')
energia         = open("Indicadores/ienergia.txt").read().split(',')
finanzas        = open("Indicadores/ifinanzas.txt").read().split(',')
genero          = open("Indicadores/igenero.txt").read().split(',')
infraestructura = open("Indicadores/iinfraestructura.txt").read().split(',')
pobreza         = open("Indicadores/ipobreza.txt").read().split(',')
privado         = open("Indicadores/iprivado.txt").read().split(',')
publico         = open("Indicadores/ipublico.txt").read().split(',')
salud           = open("Indicadores/isalud.txt").read().split(',')
social          = open("Indicadores/isocial.txt").read().split(',')
trabajo         = open("Indicadores/itrabajo.txt").read().split(',')
urbano          = open("Indicadores/iurbano.txt").read().split(',')

conjunto_nombre = ['Agricultura','Ambiente','Ayuda','Ciencia','Clima','Comercio','Deuda','Economia','Educacion',
                   'Energia','Finanzas','Genero','Infraestructura','Pobreza','Privado','Publico','Salud','Social',
                   'Trabajo','Urbano']

conjunto = [agricultura,ambiente,ayuda,ciencia,clima,comercio,deuda,economia,educacion,energia,finanzas,genero,
            infraestructura,pobreza,privado,publico,salud,social,trabajo,urbano]

datos.head()

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
0,Antigua and Barbuda,ATG,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1960,126.144000
1,Antigua and Barbuda,ATG,Age dependency ratio (% of working-age populat...,SP.POP.DPND,1960,88.237117
2,Antigua and Barbuda,ATG,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,1960,7.779958
3,Antigua and Barbuda,ATG,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,1960,80.457159
4,Antigua and Barbuda,ATG,"Birth rate, crude (per 1,000 people)",SP.DYN.CBRT.IN,1960,32.920000

## Promedio de Rendimiento

In [11]:
resultados = pd.read_csv("colombia_original_log.csv").drop('Unnamed: 0', 1)

pd.DataFrame((resultados[resultados['Look Back']==2]['%'].values/resultados[resultados['Look Back']==1]['%'].values)-1)*100

             0
0    -8.879261
1    -6.562222
2     0.623730
3    22.458666
4   -21.358855
5    -3.336695
6    -4.696976
7    20.424620
8    -8.172113
9   -17.416736
10   -5.567910
11   38.410483
12   14.468321
13    2.957920
14   15.716867
15   18.909181
16   19.063342
17  -27.270284
18    0.439702
19   -5.214146
20   -6.763751
21   -7.503621
22    8.447391
23  -12.287837
24   12.214899
25   11.206278
26   -0.854631
27  -12.991445
28    5.694767
29  -10.092828
..         ...
370 -13.205323
371  10.135520
372  23.276837
373  28.850364
374   0.336111
375 -14.635955
376 -14.075391
377  37.246394
378 -15.098640
379  48.674141
380   4.029347
381   3.149784
382 -19.773009
383  10.736855
384  -4.459070
385   5.161706
386  -9.533887
387  -4.140513
388  18.690505
389   0.916703
390  -4.192392
391   8.389614
392 -18.596103
393 -32.300922
394   7.416134
395   5.250434
396  -3.413177
397  13.880595
398 -11.096932
399 -13.858165

[400 rows x 1 columns]

In [37]:
df = resultados
df[df['Look Back']==1].groupby('Base').mean().sort_values('%', ascending=False).index.values[:5]

array(['Salud', 'Urbano', 'Economia', 'Clima', 'Ciencia'], dtype=object)

In [34]:
df_mean

                 Look Back     Reg         %       Time
Base
Salud                  1.0  101.15  0.433663  21.983977
Urbano                 1.0  103.50  0.431319  21.971159
Economia               1.0   98.85  0.414579  22.400105
Clima                  1.0   98.80  0.409295  22.340288
Ciencia                1.0  104.50  0.398558  23.173375
Privado                1.0   97.60  0.395674  21.403402
Social                 1.0  101.65  0.394699  21.635336
Agricultura            1.0  102.40  0.376734  22.565217
Finanzas               1.0  102.90  0.374121  22.994043
Infraestructura        1.0  102.60  0.368476  22.422080
Comercio               1.0   96.80  0.365133  21.371000
Genero                 1.0   94.15  0.356069  21.640545
Ayuda                  1.0  103.05  0.349771  23.604380
Energia                1.0  101.30  0.348686  23.633265
Ambiente               1.0   98.65  0.348354  22.617108
Trabajo                1.0   99.95  0.338418  22.107255
Educacion              1.0   99.35  0.337528  23.166245
Publico                1.0  103.50  0.332638  22.731269
Deuda                  1.0  102.65  0.315579  23.609363
Pobreza                1.0  104.35  0.278601  23.336985

In [28]:
df = resultados
df_temp = pd.DataFrame.pivot_table( df[df['Look Back'] == 1].drop(['Time','Reg','Results'],1) , index=["Base","Target"], columns=["Look Back"])
np.mean(df_temp.values[20:40])

0.34835393028080003

In [69]:
def conjuntos_performance(df,look_back,perform,predict,rango):
    return df[df['Look Back']==look_back].groupby(predict).mean().sort_values('%', ascending=perform).index.values[:rango]

In [82]:
def predecibles_predictores(df,look_back,rango):
    return pd.DataFrame(np.column_stack([conjuntos_performance(df,look_back,False,'Base',rango),conjuntos_performance(df,look_back,True,'Base',rango),conjuntos_performance(df,look_back,False,'Target',rango),conjuntos_performance(df,look_back,True,'Target',rango)]),columns=[['Predictor','Predictor','Predictable','Predictable'],['Best','Worse','Easy','Hard']])

In [83]:
predecibles_predictores(resultados,1,5)

  Predictor             Predictable
       Best      Worse         Easy       Hard
0     Salud    Pobreza        Salud    Publico
1    Urbano      Deuda       Urbano    Pobreza
2  Economia    Publico     Economia  Educacion
3     Clima  Educacion  Agricultura     Genero
4   Ciencia    Trabajo      Privado    Energia

## Categorizamos los Indicadores

Categorizamos los Indicadores en sus respectivos conjuntos

In [4]:
def categorizar_indicadores(df):
    for i in range(len(conjunto)):
        df.loc[df['IndicatorCode'].isin(conjunto[i]), 'Set'] = conjunto_nombre[i]
    return df

In [5]:
df = categorizar_indicadores(datos)
df.head()

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value,Set
0,Antigua and Barbuda,ATG,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1960,126.144000,Social
1,Antigua and Barbuda,ATG,Age dependency ratio (% of working-age populat...,SP.POP.DPND,1960,88.237117,Salud
2,Antigua and Barbuda,ATG,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,1960,7.779958,Salud
3,Antigua and Barbuda,ATG,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,1960,80.457159,Salud
4,Antigua and Barbuda,ATG,"Birth rate, crude (per 1,000 people)",SP.DYN.CBRT.IN,1960,32.920000,Salud

## Graficamos Registros Paises

Graficamos la cantidad de años registrados para cada uno de los paises de Suramérica

In [6]:
def registros_country_year(df):
    return df.groupby(['CountryName','Year']).agg(['count']).drop(['CountryCode','IndicatorName','IndicatorCode','Set'], 1)

In [7]:
def graficar_registros_paises(df):

    trace = go.Heatmap(z=df.reset_index(col_level=0)['Value'].values,
                       x=df.reset_index(col_level=0)['Year'],
                       y=df.reset_index(col_level=0)['CountryName'],
                       colorscale = 'Viridis')
    data=[trace]
    
    layout = go.Layout(
        title='Registros Pais + Años',
        xaxis=dict(title='Años',   titlefont=dict(size=18)),
        yaxis=dict(title='Paises', titlefont=dict(size=18))
    )
    
    fig = go.Figure(data=data, layout=layout)

    return py.iplot(fig,filename='Registros por Años')

In [8]:
graficar_registros_paises(registros_country_year(df))

PlotlyRequestError: Hey there! You've hit one of our API request limits.

To get unlimited API calls(10,000/day), please upgrade to a paid plan.

UPGRADE HERE: https://goo.gl/i7glmM

Thanks for using Plotly! Happy Plotting!

## Graficamos Registros Conjuntos

Graficamos los registros de años para cada conjunto de indicadores para Colombia

In [ ]:
def registros_set_year(df,pais):
    return df[df['CountryCode'] == pais].groupby(['Set','Year']).agg(['count']).drop(['CountryName','CountryCode','IndicatorName','IndicatorCode'], 1)

In [ ]:
def graficar_registros_conjuntos(df,pais):

    trace = go.Heatmap(z=df.reset_index(col_level=0)['Value'].values,
                       x=df.reset_index(col_level=0)['Year'],
                       y=df.reset_index(col_level=0)['Set'],
                       colorscale = 'Viridis')
    data=[trace]
    
    layout = go.Layout(
        title='Registros Conjunto + Años para '+pais,
        xaxis=dict(title='Paises',   titlefont=dict(size=18)),
        yaxis=dict(title='Años', titlefont=dict(size=18))
    )
    
    fig = go.Figure(data=data, layout=layout)

    return py.iplot(fig,filename='Registros Conjunto + Años para '+pais)

In [ ]:
graficar_registros_conjuntos(registros_set_year(df,'COL'),'Colombia')

## Cargamos Resultados para Colombia y parámetros Originales

Si eliminamos los indicadores con menos de 5 registros y ampliamos el espectro de años a 15 e iniciamos desde 2015 hacia atrás. Tendremos los siguientes resultados:

In [9]:
resultados = pd.read_csv("colombia_original_log.csv").drop('Unnamed: 0', 1)
resultados

,Base,Target,Look Back,Reg,%,Time,Results
0,Agricultura,Agricultura,1,48,0.455277,10.584898,[[ 0. ]\n [ 0. ]\n [ 0.93549912]...
1,Agricultura,Agricultura,2,48,0.414852,13.457072,[[ 0. ]\n [ 0. ]\n [ 0.81843835]...
2,Agricultura,Agricultura,3,48,0.394925,13.106958,[[ 0.32661843]\n [ 0.60803299]\n [ 0.50717803]...
3,Agricultura,Ambiente,1,96,0.307334,16.575595,[[ 0. ]\n [ 0.74249732]\n [ 0. ]...
4,Agricultura,Ambiente,2,96,0.287166,18.022063,[[ 0. ]\n [ 0.85310254]\n [ 0. ]...
5,Agricultura,Ambiente,3,96,0.286223,18.956299,[[ 0.16877031]\n [ 0. ]\n [ 0. ]...
6,Agricultura,Ayuda,1,71,0.382280,17.504265,[[ 1. ]\n [ 0.29062546]\n [ 1. ]...
7,Agricultura,Ayuda,2,71,0.384664,18.287500,[[ 1. ]\n [ 0.88768056]\n [ 1. ]...
8,Agricultura,Ayuda,3,71,0.420092,19.652280,[[ 1. ]\n [ 0.83451842]\n [ 1. ]...
9,Agricultura,Ciencia,1,13,0.429908,5.675936,[[ 0.40123109]\n [ 0. ]\n [ 0.75798151]...
10,Agricultura,Ciencia,2,13,0.526460,6.966463,[[ 0.68452153]\n [ 0.88615762]\n [ 0.00254929]...
11,Agricultura,Ciencia,3,13,0.359109,8.054454,[[ 0.53968864]\n [ 0.71894124]\n [ 0.74365687]...
12,Agricultura,Clima,1,67,0.404357,12.573218,[[ 0. ]\n [ 0.70268907]\n [ 0.63606519]...
13,Agricultura,Clima,2,67,0.317991,15.026738,[[ 0. ]\n [ 0. ]\n [ 0.87887107]...
14,Agricultura,Clima,3,67,0.303738,16.695707,[[ 0.36589416]\n [ 0.64791907]\n [ 0. ]...
15,Agricultura,Comercio,1,142,0.385315,36.118337,[[ 0. ]\n [ 1. ]\n [ 1. ]...
16,Agricultura,Comercio,2,142,0.372458,37.032504,[[ 0. ]\n [ 1. ]\n [ 1. ]...
17,Agricultura,Comercio,3,142,0.408497,37.551263,[[ 0.43945927]\n [ 1. ]\n [ 1. ]...
18,Agricultura,Deuda,1,229,0.399775,58.190400,[[ 0. ]\n [ 0.16023494]\n [ 0. ]...
19,Agricultura,Deuda,2,229,0.380998,59.279684,[[ 0. ]\n [ 0. ]\n [ 0. ]...
20,Agricultura,Deuda,3,229,0.392082,59.631616,[[ 0. ]\n [ 0.21054931]\n [ 0. ]...
21,Agricultura,Economia,1,258,0.391107,68.414853,[[ 0. ]\n [ 0. ]\n [ 0.79617266]...
22,Agricultura,Economia,2,258,0.470989,69.198278,[[ 0. ]\n [ 0. ]\n [ 0.9956917 ]...
23,Agricultura,Economia,3,258,0.424218,72.710434,[[ 0.37328958]\n [ 0.53515686]\n [ 0.64018881]...
24,Agricultura,Educacion,1,168,0.332868,32.773233,[[ 0.12820348]\n [ 0. ]\n [ 0.35054676]...
25,Agricultura,Educacion,2,168,0.305666,34.068100,[[ 0.50557905]\n [ 0. ]\n [ 0. ]...
26,Agricultura,Educacion,3,168,0.288547,36.535992,[[ 0. ]\n [ 0. ]\n [ 0.44895788]...
27,Agricultura,Energia,1,51,0.378089,12.634916,[[ 0. ]\n [ 0.6124027 ]\n [ 0. ]...
28,Agricultura,Energia,2,51,0.312238,14.092758,[[ 0. ]\n [ 0.27805315]\n [ 0.53927483]...
29,Agricultura,Energia,3,51,0.326550,15.579574,[[ 0.32629595]\n [ 0.95599462]\n [ 0. ]...
...,...,...,...,...,...,...,...
1170,Urbano,Finanzas,1,67,0.404308,17.077399,[[ 0.28684851]\n [ 0. ]\n [ 0.26257077]...
1171,Urbano,Finanzas,2,67,0.387358,18.406805,[[ 0. ]\n [ 0.38897055]\n [ 0. ]...
1172,Urbano,Finanzas,3,67,0.440543,20.077385,[[ 0.36406091]\n [ 0.98664174]\n [ 0.30453651]...
1173,Urbano,Genero,1,177,0.333585,30.714756,[[ 0. ]\n [ 0. ]\n [ 0.98102152]...
1174,Urbano,Genero,2,177,0.361572,33.110508,[[ 0.31112843]\n [ 0.49788384]\n [ 0.87983791]...
1175,Urbano,Genero,3,177,0.352030,32.036810,[[ 0.00651215]\n [ 0. ]\n [ 0.94214979]...
1176,Urbano,Infraestructura,1,42,0.479024,10.211755,[[ 0.75101494]\n [ 0. ]\n [ 0.74626685]...
1177,Urbano,Infraestructura,2,42,0.389944,12.158855,[[ 3.44515533e-01]\n [ 5.42062411e-01]\n [ ...
1178,Urbano,Infraestructura,3,42,0.427210,12.540909,[[ 0.66871716]\n [ 0. ]\n [ 0.33932606]...
1179,Urbano,Pobreza,1,22,0.383994,6.848615,[[ 0. ]\n [ 0.29697291]\n [ 0. ]...
1180,Urbano,Pobreza,2,22,0.259960,7.930539,[[ 0.58685054]\n [ 0.46282143]\n [ 0.3357779 ]...
1181,Urbano,Pobreza,3,22,0.288541,8.679558,[[ 0.26371056]\n [ 0. ]\n [ 0. ]...
1182,Urbano,Privado,1,165,0.481318,30.097158,[[ 0.48137052]\n [ 0.93860817]\n [ 1. ]...
1183,Urbano,Privado,2,165,0.517013,34.693261,[[ 0. ]\n [ 0.97145754]\n [ 1. ]...
1184,Urbano,Privado,3,165,0.412960,33.616778,[[ 0.97370564]\n [ 0.80568259]\n [ 1. ]...
1185,Urbano,Publico,1,97,0.179014,17.343178,[[ 7.57608073e-02]\n [ 9.11243486e-01]\n [ ...
1186,Urbano,Publico,2,97,0.188413,18.381524,[[ 0.31373435]\n [ 0.92919117]\n [ 0. ]...
1187,Urbano,Publico,3,97,0.183076,18.841018,[[ 0.27177398]\n [ 0.91594362]\n [ 0.6819051 ]...
1188,Urbano,Salud,1,149,0.645482,18.278908,[[ 0.87145355]\n [ 0.77893707]\n [ 0.95614962]...
1189,Urbano,Salud,2,149,0.623450,19.969232,[[ 0.94081369]\n [ 0.90911485]\n [ 0.92051625]...
1190,Urbano,Salud,3,149,0.619510,21.248627,[[ 0.97436275]\n [ 0.96468561]\n [ 0.88032626]...
1191,Urbano,Social,1,35,0.514450,8.132997,[[ 0.78375172]\n [ 0. ]\n [ 0.9983829 ]...
1192,Urbano,Social,2,35,0.585859,9.744151,[[ 0.97028559]\n [ 0.7535213 ]\n [ 0.99304839]...
1193,Urbano,Social,3,35,0.478110,10.718298,[[ 0.31878179]\n [ 0.90752784]\n [ 0.84836465]...
1194,Urbano,Trabajo,1,133,0.406413,28.452537,[[ 0.73259146]\n [ 0.50000018]\n [ 0.80461548]...
1195,Urbano,Trabajo,2,133,0.361313,28.539003,[[ 0. ]\n [ 0. ]\n [ 0.15732555]...
1196,Urbano,Trabajo,3,133,0.395997,30.223503,[[ 0.52952032]\n [ 0. ]\n [ 0.47999382]...
1197,Urbano,Urbano,1,24,0.669267,5.653761,[[ 0.78398256]\n [ 1. ]\n [ 0.72721594]...
1198,Urbano,Urbano,2,24,0.576519,6.143457,[[ 0.87134921]\n [ 0.51536026]\n [ 0.92496248]...
1199,Urbano,Urbano,3,24,0.520378,8.061021,[[ 0.02384615]\n [ 0.445 ]\n [ 0.43446874]...

## Mejores Combinaciones

In [10]:
resultados.sort_values('%', ascending=False).reset_index().drop(['index','Time','Results'],1)[:10]

       Base  Target  Look Back  Reg         %
0    Social  Urbano          2   24  0.721845
1    Social  Urbano          3   24  0.693165
2    Urbano  Urbano          1   24  0.669267
3   Energia  Urbano          2   20  0.661917
4    Urbano   Salud          1  149  0.645482
5     Clima  Urbano          2   16  0.643453
6    Social   Salud          2  145  0.641142
7     Salud  Urbano          2   21  0.639400
8     Salud   Salud          1  152  0.637943
9  Economia  Urbano          2   24  0.637235

## Peores Combinaciones

In [11]:
resultados.sort_values('%', ascending=True).reset_index().drop(['index','Time','Results'],1)[:10]

              Base   Target  Look Back  Reg         %
0      Agricultura  Publico          3   97  0.107455
1         Finanzas  Publico          2   95  0.111846
2  Infraestructura  Publico          2   97  0.112536
3  Infraestructura  Publico          3   97  0.117392
4          Trabajo  Publico          2   97  0.117819
5            Ayuda  Publico          3   97  0.121123
6            Deuda  Publico          1   97  0.123299
7          Energia  Publico          2   97  0.127654
8          Publico  Publico          3   97  0.130190
9           Genero  Publico          1   87  0.130502

In [14]:
pd.DataFrame.pivot_table(resultados, index=["Base","Target","Reg"], columns=["Look Back"])

                                        %                           Time  \
Look Back                               1         2         3          1
Base        Target          Reg
Agricultura Agricultura     48   0.455277  0.414852  0.394925  10.584898
            Ambiente        96   0.307334  0.287166  0.286223  16.575595
            Ayuda           71   0.382280  0.384664  0.420092  17.504265
            Ciencia         13   0.429908  0.526460  0.359109   5.675936
            Clima           67   0.404357  0.317991  0.303738  12.573218
            Comercio        142  0.385315  0.372458  0.408497  36.118337
            Deuda           229  0.399775  0.380998  0.392082  58.190400
            Economia        258  0.391107  0.470989  0.424218  68.414853
            Educacion       168  0.332868  0.305666  0.288547  32.773233
            Energia         51   0.378089  0.312238  0.326550  12.634916
            Finanzas        67   0.399494  0.377250  0.351654  17.354203
            Genero          175  0.275397  0.381179  0.355255  31.719054
            Infraestructura 41   0.430422  0.492697  0.325059  10.778756
            Pobreza         23   0.256389  0.263973  0.210966   7.099161
            Privado         163  0.375130  0.434089  0.362763  33.863217
            Publico         97   0.175645  0.208858  0.107455  16.890111
            Salud           150  0.448525  0.534029  0.527037  19.825360
            Social          35   0.467667  0.340133  0.509848   9.067962
            Trabajo         130  0.326938  0.328375  0.313273  28.238288
            Urbano          24   0.512767  0.486031  0.568008   5.422578
Ambiente    Agricultura     32   0.423388  0.394752  0.441853   9.451177
            Ambiente        112  0.350286  0.324002  0.326197  17.497463
            Ayuda           71   0.271423  0.294352  0.295583  19.056038
            Ciencia         13   0.494345  0.433600  0.392608   5.747954
            Clima           31   0.456323  0.512062  0.419186   9.618566
            Comercio        144  0.316751  0.352248  0.366474  37.866983
            Deuda           229  0.335557  0.332690  0.374617  60.068401
            Economia        239  0.443180  0.385605  0.441595  65.323090
            Educacion       168  0.277919  0.293746  0.262384  33.225837
            Energia         31   0.271766  0.244337  0.393576   8.719014
...                                   ...       ...       ...        ...
Trabajo     Finanzas        67   0.378030  0.328110  0.346170  17.589508
            Genero          120  0.304890  0.335792  0.236539  18.957240
            Infraestructura 43   0.351432  0.433235  0.420787  11.433934
            Pobreza         25   0.216952  0.279543  0.297508   7.495653
            Privado         165  0.399616  0.400959  0.355508  33.524757
            Publico         97   0.138020  0.117819  0.173536  17.668730
            Salud           152  0.506311  0.435045  0.360767  20.268499
            Social          13   0.242855  0.333309  0.425035   6.011615
            Trabajo         133  0.366519  0.311180  0.281991  27.818852
            Urbano          24   0.390143  0.580042  0.613578   5.741159
Urbano      Agricultura     48   0.482081  0.501506  0.538538  11.128162
            Ambiente        105  0.438390  0.452198  0.372888  17.359005
            Ayuda           71   0.371373  0.297941  0.318027  16.802381
            Ciencia         13   0.501220  0.555035  0.482072   4.491826
            Clima           72   0.404652  0.386608  0.411397  14.033512
            Comercio        144  0.376892  0.396346  0.392874  34.514162
            Deuda           229  0.435910  0.394351  0.384227  55.177979
            Economia        260  0.489227  0.468970  0.515478  67.859633
            Educacion       168  0.275230  0.326671  0.329841  32.376154
            Energia         49   0.354558  0.357809  0.257036  12.869297
            Finanzas        67   0.404308  0.387358  0.440543  17.077399
            Genero          177  0.333585  0.361572  0.352030  30.714756
            Infraestructura 42   0.479024  0.389944  0.427210  10.211755
            Pobreza         22   0.383994  0.259960  0.288541   6.848615
            Privado         165  0.481318  0.517013  0.412960  30.097158
            Publico         97   0.179014  0.188413  0.183076  17.343178
            Salud           149  0.645482  0.623450  0.619510  18.278908
            Social          35   0.514450  0.585859  0.478110   8.132997
            Trabajo         133  0.406413  0.361313  0.395997  28.452537
            Urbano          24   0.669267  0.576519  0.520378   5.653761


Look Back                                2          3
Base        Target          Reg
Agricultura Agricultura     48   13.457072  13.106958
            Ambiente        96   18.022063  18.956299
            Ayuda           71   18.287500  19.652280
            Ciencia         13    6.966463   8.054454
            Clima           67   15.026738  16.695707
            Comercio        142  37.032504  37.551263
            Deuda           229  59.279684  59.631616
            Economia        258  69.198278  72.710434
            Educacion       168  34.068100  36.535992
            Energia         51   14.092758  15.579574
            Finanzas        67   19.730522  19.973023
            Genero          175  31.503593  34.020554
            Infraestructura 41   12.662892  13.276506
            Pobreza         23    8.109485   9.383795
            Privado         163  33.992894  35.715093
            Publico         97   18.168449  19.879536
            Salud           150  20.990423  21.456110
            Social          35   10.634744  11.408494
            Trabajo         130  29.103705  28.788162
            Urbano          24    6.770044   7.902477
Ambiente    Agricultura     32   10.689403  11.864513
            Ambiente        112  19.847845  19.243054
            Ayuda           71   19.598884  21.048097
            Ciencia         13    6.771274   7.827994
            Clima           31    9.877200  11.592887
            Comercio        144  38.468903  39.864002
            Deuda           229  61.848740  61.412548
            Economia        239  70.225517  67.904164
            Educacion       168  34.133948  35.567533
            Energia         31    9.801435  10.651739
...                                    ...        ...
Trabajo     Finanzas        67   19.054963  20.655439
            Genero          120  19.857934  21.904036
            Infraestructura 43   12.605860  13.536708
            Pobreza         25    8.300082   8.862020
            Privado         165  33.718135  37.355340
            Publico         97   19.136120  20.145054
            Salud           152  22.674047  24.763588
            Social          13    7.051957   7.943902
            Trabajo         133  30.542890  31.962832
            Urbano          24    6.822545   8.181821
Urbano      Agricultura     48   11.501588  12.928935
            Ambiente        105  18.431406  19.474776
            Ayuda           71   19.076373  20.629791
            Ciencia         13    6.420654   7.432653
            Clima           72   15.138404  16.400259
            Comercio        144  37.303233  38.359712
            Deuda           229  57.709494  59.826229
            Economia        260  70.055099  67.615246
            Educacion       168  32.934234  34.680565
            Energia         49   13.641661  14.653362
            Finanzas        67   18.406805  20.077385
            Genero          177  33.110508  32.036810
            Infraestructura 42   12.158855  12.540909
            Pobreza         22    7.930539   8.679558
            Privado         165  34.693261  33.616778
            Publico         97   18.381524  18.841018
            Salud           149  19.969232  21.248627
            Social          35    9.744151  10.718298
            Trabajo         133  28.539003  30.223503
            Urbano          24    6.143457   8.061021

[400 rows x 6 columns]

## Rendimiento Look Back

In [ ]:
resultados[resultados['Look Back']==1]

## Graficamos Resultados Globales

El siguiente Heatmap nos muestra el promedio del Score R2 obtenido para cada conjunto de indicadores

In [ ]:
def graficar_resultados(df,look_back):

    trace = go.Heatmap(z=df[df['Look Back'] == look_back]['%'],
                       x=df[df['Look Back'] == look_back]['Base'],
                       y=df[df['Look Back'] == look_back]['Target'],
                       zmax=1.0,
                       zmin=0.0,
                       colorscale = 'Viridis')
    data=[trace]
    
    layout = go.Layout(
        title=pais_nombre+' + '+search+': Total Heatmap with Look Back = '+str(look_back),
        xaxis=dict(title='Base',   titlefont=dict(size=18)),
        yaxis=dict(title='Target', titlefont=dict(size=18))
    )
    
    fig = go.Figure(data=data, layout=layout)

    return py.iplot(fig,filename=pais_nombre+' + '+search+': Total Heatmap with Look Back = '+str(look_back))

In [ ]:
graficar_resultados(resultados,1)

In [ ]:
graficar_resultados(resultados,2)

In [ ]:
graficar_resultados(resultados,3)

## Conclusiones

- Con el objetivo de encontrar los conjuntos con mayor grado de predictibilidad, contamos la cantidad de conjuntos en los que el rendimiento promedio fue superior al 30% para dos casos:

 **Predictor:** Conjunto que predice a otro conjunto
 
 **Predecible:** Conjunto que es predecido por otro conjunto

In [17]:
def conjuntos_predecibles(df,look_back):
    df_temp = pd.DataFrame.pivot_table( df[df['Look Back'] == look_back].drop(['Time','Reg','Results'],1) , index=["Target","Base"], columns=["Look Back"])
    return pd.DataFrame(df_temp[df_temp['%'] > 0.3].count(level=0).sort_values([('%',1)], ascending=False).index.values, columns=["Conjunto"])

In [18]:
def conjuntos_predictores(df,look_back):
    df_temp = pd.DataFrame.pivot_table( df[df['Look Back'] == look_back].drop(['Time','Reg','Results'],1) , index=["Base","Target"], columns=["Look Back"])
    return pd.DataFrame(df_temp[df_temp['%'] > 0.3].count(level=0).sort_values([('%',1)], ascending=False).index.values, columns=["Conjunto"])

In [19]:
def predictor_predictable(df,look_back,rango):
    return pd.DataFrame(np.column_stack([conjuntos_predictores(df,look_back)[:rango],conjuntos_predictores(df,look_back).tail(rango),conjuntos_predecibles(df,look_back)[:rango],conjuntos_predecibles(df,look_back).tail(rango)]), columns=['Best Predictor','Worse Predictor','Easier Predictable','Hard Predictable'])

In [20]:
predictor_predictable(resultados,1,7)

    Best Predictor Worse Predictor Easier Predictable Hard Predictable
0         Economia         Publico        Agricultura           Social
1            Clima          Social              Deuda         Ambiente
2           Urbano         Energia              Salud          Trabajo
3          Privado        Ambiente            Privado           Genero
4  Infraestructura           Ayuda           Economia        Educacion
5            Salud           Deuda             Urbano          Pobreza
6           Genero         Pobreza           Comercio          Publico