## Resultados

Cargamos los resultados de iterar todos los conjuntos de indicadores

In [11]:
import pandas as pd
import numpy as np

df = pd.read_csv("suramerica_random_log.csv").drop(['Unnamed: 0'], 1)
df

,Base,Target,Look Back,Reg,%,Time,Results
0,Agricultura,Agricultura,1,48,0.765274,276.635405,[[ 0.689148 ]\n [ 0.88352764]\n [ 0.93667888]...
1,Agricultura,Agricultura,2,48,0.755387,350.148652,[[ 0.20762782]\n [ 0.87408148]\n [ 0.55534214]...
2,Agricultura,Agricultura,3,48,0.805246,343.161418,[[ 0.84624086]\n [ 0.93792492]\n [ 0.9136193 ]...
3,Agricultura,Ambiente,1,96,0.710018,538.873662,[[ 0.56562301]\n [ 0.87384423]\n [ 0.71845521]...
4,Agricultura,Ambiente,2,96,0.700323,600.934850,[[ 0.79388253]\n [ 0.90908956]\n [ 0.64653924]...
5,Agricultura,Ambiente,3,96,0.711968,643.579668,[[ 0.72620427]\n [ 0.90600589]\n [ 0.79006985]...
6,Agricultura,Ayuda,1,71,0.540683,624.620061,[[ 1. ]\n [ 0.43219933]\n [ 0.75025167]...
7,Agricultura,Ayuda,2,71,0.518157,736.729489,[[ 1. ]\n [ 0.49148507]\n [ 0.88739724]...
8,Agricultura,Ayuda,3,71,0.540304,750.428898,[[ 1. ]\n [ 0.47676634]\n [ 0.82135258]...
9,Agricultura,Ciencia,1,13,0.749912,89.825199,[[ 0.90403914]\n [ 0.94107443]\n [ 0.39165049]...
10,Agricultura,Ciencia,2,13,0.828071,90.972852,[[ 0.83445915]\n [ 0.95436176]\n [ 0.90769198]...
11,Agricultura,Ciencia,3,13,0.830269,90.362647,[[ 0.96883686]\n [ 0.66977311]\n [ 0.84874472]...
12,Agricultura,Clima,1,67,0.762458,334.130085,[[ 0.58358229]\n [ 0. ]\n [ 0. ]...

## Resultados iniciales

In [2]:
pd.DataFrame.pivot_table(df, index=["Base","Target","Reg"], columns=["Look Back"]).drop(['Time'],1)

                                        %
Look Back                               1         2         3
Base        Target          Reg
Agricultura Agricultura     48   0.409091  0.340909  0.363636
            Ambiente        96   0.293333  0.280000  0.240000
            Ayuda           71   0.136364  0.196970  0.166667
            Ciencia         13   0.076923  0.538462  0.461538
            Clima           67   0.472727  0.418182  0.363636
            Comercio        142  0.304965  0.290780  0.234043
            Deuda           229  0.245536  0.263393  0.245536
            Economia        258  0.372000  0.348000  0.268000
            Educacion       168  0.146552  0.137931  0.086207
            Energia         51   0.380000  0.340000  0.360000
            Finanzas        67   0.266667  0.216667  0.166667
            Genero          175  0.187050  0.165468  0.151079
            Infraestructura 41   0.390244  0.292683  0.317073
            Pobreza         23   0.100000  0.100000  0.100000
            Privado         163  0.248322  0.181208  0.201342
            Publico         97   0.387500  0.312500  0.312500
            Salud           150  0.336000  0.280000  0.296000
            Social          35   0.371429  0.285714  0.285714
            Trabajo         130  0.220472  0.173228  0.133858
            Urbano          24   0.388889  0.500000  0.388889
Ambiente    Agricultura     32   0.187500  0.312500  0.218750
            Ambiente        112  0.356322  0.298851  0.379310
            Ayuda           71   0.060606  0.090909  0.090909
            Ciencia         13   0.538462  0.307692  0.307692
            Clima           31   0.433333  0.366667  0.433333
            Comercio        144  0.237762  0.195804  0.209790
            Deuda           229  0.174107  0.133929  0.160714
            Economia        239  0.298701  0.303030  0.350649
            Educacion       168  0.094828  0.137931  0.137931
            Energia         31   0.354839  0.354839  0.387097
...                                   ...       ...       ...
Trabajo     Finanzas        67   0.116667  0.100000  0.083333
            Genero          120  0.083333  0.047619  0.023810
            Infraestructura 43   0.186047  0.232558  0.116279
            Pobreza         25   0.136364  0.000000  0.136364
            Privado         165  0.092715  0.072848  0.066225
            Publico         97   0.162500  0.162500  0.125000
            Salud           152  0.102362  0.094488  0.118110
            Social          13   0.153846  0.000000  0.076923
            Trabajo         133  0.146154  0.176923  0.161538
            Urbano          24   0.277778  0.055556  0.055556
Urbano      Agricultura     48   0.522727  0.477273  0.409091
            Ambiente        105  0.400000  0.352941  0.352941
            Ayuda           71   0.121212  0.212121  0.166667
            Ciencia         13   0.692308  0.615385  0.230769
            Clima           72   0.516667  0.500000  0.466667
            Comercio        144  0.328671  0.363636  0.321678
            Deuda           229  0.299107  0.308036  0.227679
            Economia        260  0.523810  0.496032  0.428571
            Educacion       168  0.206897  0.181034  0.129310
            Energia         49   0.458333  0.562500  0.416667
            Finanzas        67   0.283333  0.433333  0.350000
            Genero          177  0.205674  0.219858  0.170213
            Infraestructura 42   0.428571  0.476190  0.428571
            Pobreza         22   0.200000  0.300000  0.100000
            Privado         165  0.317881  0.264901  0.264901
            Publico         97   0.537500  0.412500  0.387500
            Salud           149  0.360000  0.360000  0.344000
            Social          35   0.342857  0.342857  0.314286
            Trabajo         133  0.230769  0.184615  0.200000
            Urbano          24   0.444444  0.500000  0.500000

[400 rows x 3 columns]

In [3]:
datos = pd.read_csv("suramerica.csv").drop('Unnamed: 0', 1)
paises = datos['CountryCode'].drop_duplicates().values.tolist()

preprocessing = 'imput'
search = 'original'
year_init = 2012
year_range = 5
look_back = 3
years = range(year_init-year_range+1,year_init+1)[::-1]

agricultura     = open("Indicadores/iagricultura.txt").read().split(',')
ambiente        = open("Indicadores/iambiente.txt").read().split(',')
ayuda           = open("Indicadores/iayuda.txt").read().split(',')
ciencia         = open("Indicadores/iciencia.txt").read().split(',')
clima           = open("Indicadores/iclima.txt").read().split(',')
comercio        = open("Indicadores/icomercio.txt").read().split(',')
deuda           = open("Indicadores/ideuda.txt").read().split(',')
economia        = open("Indicadores/ieconomia.txt").read().split(',')
educacion       = open("Indicadores/ieducacion.txt").read().split(',')
energia         = open("Indicadores/ienergia.txt").read().split(',')
finanzas        = open("Indicadores/ifinanzas.txt").read().split(',')
genero          = open("Indicadores/igenero.txt").read().split(',')
infraestructura = open("Indicadores/iinfraestructura.txt").read().split(',')
pobreza         = open("Indicadores/ipobreza.txt").read().split(',')
privado         = open("Indicadores/iprivado.txt").read().split(',')
publico         = open("Indicadores/ipublico.txt").read().split(',')
salud           = open("Indicadores/isalud.txt").read().split(',')
social          = open("Indicadores/isocial.txt").read().split(',')
trabajo         = open("Indicadores/itrabajo.txt").read().split(',')
urbano          = open("Indicadores/iurbano.txt").read().split(',')


conjunto_nombre = ['Agricultura','Ambiente','Ayuda','Ciencia','Clima','Comercio','Deuda','Economia','Educacion',
                   'Energia','Finanzas','Genero','Infraestructura','Pobreza','Privado','Publico','Salud','Social',
                   'Trabajo','Urbano']
conjunto = [agricultura,ambiente,ayuda,ciencia,clima,comercio,deuda,economia,educacion,energia,finanzas,genero,
            infraestructura,pobreza,privado,publico,salud,social,trabajo,urbano]

In [4]:
def tabla_base(indicadores):
    tab = pd.DataFrame.pivot_table(datos, values='Value', index=['CountryCode', 'Year'], columns=['IndicatorCode']).loc[(paises,years),indicadores].sortlevel(["CountryCode","Year"], ascending=[True,False])
    return tab

In [5]:
def buscar_mejores(df):
    return df[df.Resultados > 0.9].reset_index(drop=True)

In [6]:
def graficar_resultados(df,look_back):

    trace = go.Heatmap(z=df[df['Look Back'] == look_back]['%'],
                       x=df[df['Look Back'] == look_back]['Base'],
                       y=df[df['Look Back'] == look_back]['Target'],
                       colorscale = 'Viridis')
    data=[trace]
    
    layout = go.Layout(
        title='Total Heatmap'+' with '+'Look Back = '+str(look_back),
        xaxis=dict(title='Base',   titlefont=dict(size=18)),
        yaxis=dict(title='Target', titlefont=dict(size=18))
    )
    
    fig = go.Figure(data=data, layout=layout)

    return py.iplot(fig,filename='Total Heatmap'+' with '+'Look Back = '+str(look_back))

In [7]:
def buscar_resultados(df,indicador_1,indicador_2,look_back):
    #Buscamos Resultados en base al conjunto de indicadores Base, Target y Look Back
    temp = df[(df['Base']==indicador_1)&(df['Target']==indicador_2)&(df['Look Back'] == look_back)]['Results'].values[0]
    df_temp = temp.replace("'","").replace("[","").replace("]","").replace(" ","").split('\n')
    results = []
    for i in df_temp: 
        results.append(float(i))
    
    # Códigos de los indicadores con registros 
    df_nombres = pd.DataFrame(conjunto_nombre, columns=['Resultados'])
    indicador_1 = conjunto[df_nombres[df_nombres['Resultados']==indicador_1].index.values[0]]
    indicador_2 = conjunto[df_nombres[df_nombres['Resultados']==indicador_2].index.values[0]]     
    df = pd.DataFrame(indicador_2)
    
    # Filtro indicadores repetidos
    if(indicador_1!=indicador_2):
        indicador_2 = np.array(df.loc[~df.ix[:,0].isin(indicador_1)]).flatten()
    df_zeros = tabla_base(indicador_2).dropna(how='all',axis=1)
    icodes = df_zeros.columns.values

    # Buscamos Nombres de los Códigos de los Indicadores
    nombres = pd.DataFrame(datos).loc[:,['IndicatorName','IndicatorCode']].set_index('IndicatorCode').loc[icodes].drop_duplicates()

    # Concatenamos Resultados y Nombres, Reindexando en base a los nombres
    df_results = pd.DataFrame(np.column_stack([nombres,results]),columns=['Indicadores','Resultados'])
    
    return df_results

In [8]:
def graficar_resultados_individuales(df,indicador_base,indicador_target,look_back):

    df_temp = buscar_resultados(df,indicador_base,indicador_target,look_back)

    data = [go.Bar(
                x= df_temp['Indicadores'],
                y= df_temp['Resultados'],

        marker=dict(     
            color = df_temp['Resultados'].values,
            colorscale ='Viridis',
            showscale = True
            ),
        )]

    layout = go.Layout(
        title='Result to predict: '+indicador_target+' from '+indicador_base+' with '+'Look Back = '+str(look_back),
    )
    
    fig = go.Figure(data=data, layout=layout)

    return py.iplot(fig, filename = 'Result to predict: '+indicador_target+' from '+indicador_base+' with '+'Look Back = '+str(look_back))

In [9]:
def conjuntos_predecibles(df,look_back):
    df_temp = pd.DataFrame.pivot_table( df[df['Look Back'] == 1].drop(['Time','Reg','Results'],1) , index=["Target","Base"], columns=["Look Back"])
    return pd.DataFrame(df_temp[df_temp['%'] > 0.3].count(level=0).sort_values([('%',1)], ascending=False).index.values, columns=["Conjunto"])

In [10]:
def conjuntos_predictores(df,look_back):
    df_temp = pd.DataFrame.pivot_table( df[df['Look Back'] == 1].drop(['Time','Reg','Results'],1) , index=["Base","Target"], columns=["Look Back"])
    return pd.DataFrame(df_temp[df_temp['%'] > 0.3].count(level=0).sort_values([('%',1)], ascending=False).index.values, columns=["Conjunto"])

## Buscamos Mejores Resultados Individuales

In [11]:
buscar_mejores(buscar_resultados(df,'Agricultura','Infraestructura',1))

                                          Indicadores Resultados
0             Air transport, freight (million ton-km)   0.910649
1   Container port traffic (TEU: 20 foot equivalen...   0.957681
2         Electric power consumption (kWh per capita)    0.91501
3   Electricity production from hydroelectric sour...   0.920372
4   Electricity production from natural gas source...   0.963087
5   Electricity production from oil sources (% of ...   0.936279
6                       Fixed broadband subscriptions   0.918652
7                       Fixed telephone subscriptions    0.99226
8      Fixed telephone subscriptions (per 100 people)     0.9844
9              ICT service exports (BoP, current US$)   0.936051
10  Investment in transport with private participa...   0.951249
11                      Mobile cellular subscriptions   0.914159
12                        Rail lines (total route-km)   0.929643
13       Railways, goods transported (million ton-km)   0.999056
14  Railways, passengers carried (million passenge...   0.906451
15     Secure Internet servers (per 1 million people)   0.904757

## Mejores combinaciones

In [12]:
df.sort_values('%', ascending=False).reset_index().drop(['index','Time','Results'],1)[:10]

              Base   Target  Look Back  Reg         %
0  Infraestructura  Ciencia          2   13  0.692308
1  Infraestructura  Ciencia          1   13  0.692308
2           Urbano  Ciencia          1   13  0.692308
3         Comercio  Ciencia          2   11  0.636364
4          Privado  Ciencia          1   11  0.636364
5           Urbano  Ciencia          2   13  0.615385
6            Clima    Clima          1   80  0.584615
7            Clima    Clima          2   80  0.584615
8          Energia  Energia          2   53  0.576923
9           Urbano  Energia          2   49  0.562500

## Peores combinaciones

In [13]:
df.sort_values('%', ascending=False).reset_index().drop(['index','Time','Results'],1).tail(10)

          Base       Target  Look Back  Reg    %
1190   Pobreza      Ciencia          3   13  0.0
1191     Ayuda      Pobreza          3   23  0.0
1192   Trabajo       Social          2   13  0.0
1193   Pobreza        Clima          3   79  0.0
1194   Pobreza  Agricultura          2   46  0.0
1195   Pobreza      Energia          3   53  0.0
1196   Pobreza     Comercio          1  144  0.0
1197   Pobreza      Energia          1   53  0.0
1198   Trabajo      Pobreza          2   25  0.0
1199  Finanzas      Pobreza          3   25  0.0

## Graficamos Resultados Individuales

Resultado de predecir el conjunto de indicadores de Infraestructura desde Agricultura

In [14]:
graficar_resultados_individuales(df,'Agricultura','Infraestructura',1)

In [15]:
graficar_resultados_individuales(df,'Agricultura','Economia',1)

## Graficamos Resultados Globales

Este Heatmap nos muestra el porcentaje de cada conjunto indicadores que tiene un Score de R2 > 90% (0.9)

In [16]:
graficar_resultados(df,1)

In [17]:
graficar_resultados(df,2)

In [18]:
graficar_resultados(df,3)

# Conclusiones

- Con el objetivo de encontrar los conjuntos con mayor grado de predictibilidad, contamos la cantidad de conjuntos en los cuales el 30% o más de sus indicadores obtuvieron un puntaje mayor al 90% para dos casos:

 **Predictor:** Conjunto que predice a otro conjunto
 
 **Predecible:** Conjunto que es predecido por otro conjunto

In [19]:
pd.DataFrame(np.column_stack([conjuntos_predictores(df,1)[:5],conjuntos_predictores(df,1).tail(5),conjuntos_predecibles(df,1)[:5],conjuntos_predecibles(df,1).tail(5)]), columns=['Best Predictor','Worse Predictor','Easier Predictable','Hard Predictable'])

  Best Predictor Worse Predictor Easier Predictable Hard Predictable
0         Urbano         Ciencia            Ciencia            Deuda
1          Salud       Educacion           Economia           Genero
2    Agricultura          Genero             Urbano          Pobreza
3          Clima           Ayuda            Publico            Ayuda
4         Social         Pobreza              Clima          Trabajo