## World Development Indicators - Analytics

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

datos = pd.read_csv("economia7.csv").drop('Unnamed: 0', 1)
datos.head()

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
0,Antigua and Barbuda,ATG,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1960,126.144000
1,Antigua and Barbuda,ATG,Age dependency ratio (% of working-age populat...,SP.POP.DPND,1960,88.237117
2,Antigua and Barbuda,ATG,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,1960,7.779958
3,Antigua and Barbuda,ATG,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,1960,80.457159
4,Antigua and Barbuda,ATG,"Birth rate, crude (per 1,000 people)",SP.DYN.CBRT.IN,1960,32.920000

In [3]:
def r2(y_true, y_predict):
    from sklearn.metrics import r2_score
    return r2_score(y_true, y_predict)

In [4]:
def tabla_base(paises,years,indicadores,datos):
    tab = pd.DataFrame.pivot_table(datos, values='Value', index=['CountryName', 'Year'], columns=['IndicatorCode']).loc[(paises,years),indicadores].sortlevel(["CountryName","Year"], ascending=[True,False])
    return tab

In [5]:
def zeros(tab):
    df = pd.DataFrame(tab)
    #Eliminamos las columnas de NaN descartando Indicadores que no tienen regristros para ningún pais y año deseados
    df = df.dropna(how='all',axis=1)
    #Asignamos a los NaN el valor de 0    
    df = df.fillna(0)
    # Elimina Indicadores con todos sus registros en Zero
    df = df.loc[:, (df != 0).any(axis=0)]
    return np.array(df)

In [6]:
def imputar(tab):
    from sklearn.preprocessing import Imputer
    impute=Imputer(missing_values="NaN",strategy='mean',axis=0)
    impute.fit(tab)
    tab_imputada=impute.transform(tab)
    return np.array(tab_imputada)

In [7]:
def normalizar(tab):
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    return sc.fit_transform(tab)

In [8]:
def correlacion(tab,y_indicator):
    # Buscamos los indicadores que se correlacionen más (coeficiente > 0.7)
    eliminar = []
    tabla_correlacion = np.array(pd.DataFrame(tab).corr())
    for i in range(np.shape(tab)[1]):
        if abs(tabla_correlacion[i,y_indicator]) > 0.7:
            eliminar.append(i)

    # Eliminamos los indicadores que se correlacionan más (Coeficiente > 0.7)
    temporal = tab[:,:]

    for i in range(len(eliminar)):
        temporal = np.delete(temporal[:,:], eliminar[i]-i, 1)

    return temporal

In [9]:
def Splitter(tab1,tab2,y_indicator):
    from sklearn.model_selection import train_test_split
    #Fusionamos la tabla_1 y el indicador y de la tabla_2
    tab_fusion = np.column_stack((tab1[:,:],tab2[:,y_indicator]))
    
    # Asignamos X e y, eliminando los indicadores que se correlacionen más (coeficiente > 0.7)  
    X = correlacion(tab_fusion,-1)
    y = tab_fusion[:,-1]
    
    # Separamos Train y Test respectivamente para X e y
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    return X_train, X_test, y_train, y_test

In [10]:
def estimator_Universal(estimador, preprocess, search, X_train, X_test, y_train, y_test):
    from sklearn.ensemble import RandomForestRegressor
    from sklearn.tree import DecisionTreeRegressor
    from sklearn.svm import SVR
    
    start_time = time.time()
    best_params = SearchCV_Universal(estimador, search, X_train, y_train)       
    
    if(estimador=='DTR'):
        estimator = DecisionTreeRegressor().set_params(**best_params)
    if(estimador=='RFR'):
        estimator = RandomForestRegressor(n_jobs=-1).set_params(**best_params)
    if(estimador=='SVR'):
        estimator = SVR().set_params(**best_params)
        
    estimator.fit(X_train,y_train)
    y_predict = estimator.predict(X_test)
    
    log_detail.append([estimador, preprocess, search, "%s" % (time.time() - start_time), best_params])
        
    return r2(y_test,y_predict)

In [11]:
def SearchCV_Universal(estimador, search, X_train, y_train):
    from sklearn.model_selection import GridSearchCV
    from sklearn.model_selection import RandomizedSearchCV
    from sklearn.model_selection import ShuffleSplit
    from sklearn.tree import DecisionTreeRegressor
    from sklearn.ensemble import RandomForestRegressor
    from sklearn.svm import SVR
        
    if(estimador=='DTR'):
        estimator  = DecisionTreeRegressor()
        param_grid = {  'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
                        'splitter': ['best', 'random']
                     }
        
    if(estimador=='RFR'):
        estimator  = RandomForestRegressor()       
        param_grid = { 
                        "n_estimators"      : [10,20,30,40],
                        "max_features"      : ["auto", "sqrt", "log2"],
                        "min_samples_split" : [2,4,8],
                        "bootstrap": [True, False],
                     }
    if(estimador=='SVR'):
        estimator  = SVR()
        param_grid ={
                        'gamma'  : ['auto', 1e-3, 1e-4],
                        'C'      : [1, 10, 100, 1000],            
                    }

    if (search=='random'):
        grid = RandomizedSearchCV(estimator, param_grid, n_jobs=-1, cv=ShuffleSplit(test_size=0.2))
    if (search=='grid'):
        grid = GridSearchCV(estimator, param_grid, n_jobs=-1, cv=ShuffleSplit(test_size=0.2))
    grid.fit(X_train, y_train)
    
    return grid.best_params_

In [12]:
def iter_Splitter_Optimus(tab1,tab2,preprocess,search):    
    R2_global = list()
    for i in range(0,np.shape(zeros(tab2))[1]):
        
        if (preprocess=='zeros'):
            X_train, X_test, y_train, y_test = Splitter(normalizar(zeros(tab1)),normalizar(zeros(tab2)), i)
        if (preprocess=='imput'):
            X_train, X_test, y_train, y_test = Splitter(normalizar(imputar(tab1)),normalizar(imputar(tab2)), i)

        result = estimator_Universal('DTR', preprocess, search, X_train, X_test, y_train, y_test)

        if(result < 0.9): 
            temp = estimator_Universal('SVR', preprocess, search, X_train, X_test, y_train, y_test)
            if(temp < 0.9): 
                temp2 = estimator_Universal('RFR', preprocess, search, X_train, X_test, y_train, y_test)
                if (temp2 > temp): 
                    result = temp2
            if(temp > result): 
                result = temp

        R2_global.append(result)
        pd.DataFrame(log_detail, columns=["Estimator","Preprocess","Search","Time","Best Params"]).to_csv('log_base_detail.csv')    

    return R2_global

In [15]:
def porcent_result(df):
    df_temp = np.array(df)
    x = 0.0
    for i in range(len(df_temp)):
        if(df_temp[i] > 0.9):
            x=x+1
    porcentaje = x/len(df)
    return porcentaje , df

## Rendimiento Normalizar Zeros vs Normalizar Imputado

In [42]:
log_detail = []

iter_Zeros = iter_Splitter_Optimus(datos,'zeros','random')
iter_Imput = iter_Splitter_Optimus(datos,'imput','random')

porcent_zeros , result_zeros = porcent_result(iter_Zeros)
porcent_imput , result_imput = porcent_result(iter_Imput)

print "Zeros" , porcent_zeros
print "Imput" , porcent_imput

pd.DataFrame(np.column_stack([iter_Zeros,iter_Imput]),columns=['Zeros','Imputado'])

Zeros 0.568181818182
Imput 0.386363636364

       Zeros  Imputado
0  -0.000103  0.106693
1   0.366220  0.480536
2   0.906952  0.755478
3   0.978087  0.996838
4   0.980990  0.985190
5   0.075907  1.000000
6   0.863476  0.000000
7   0.953800 -0.032878
8   0.700349  0.526084
9   0.985380  0.106734
10 -1.397480  0.015800
11  0.806307  0.574269
12  0.774831  0.844232
13  0.905866  0.953272
14  0.910955  0.914431
15  0.985518  0.955599
16  0.104696 -0.239303
17  0.960879  0.989696
18  0.986958  0.993334
19  0.998949  0.878109
20  0.400483 -0.000928
21  0.934991  0.839183
22  0.967866  0.833434
23  0.915267  0.842847
24  0.884265  0.804039
25  0.636551  0.959120
26  0.666645  0.824373
27  0.117095  0.803506
28  0.847851  0.757668
29  0.931986  0.720938
30  0.845017  0.926757
31  0.999657  0.989237
32  0.948427  0.932882
33  0.995742  0.938844
34  0.998780  0.936891
35  0.973184  0.800846
36  0.935330  0.608726
37  0.990215  0.977778
38  0.823697  0.899118
39  0.971230  0.980185
40  0.967206  0.913986
41  0.838835  0.699108
42  0.703585  0.811012
43  0.996572  0.697541

## Rendimiento RandomizedSearch vs GridSearch

In [ ]:
log_detail = []

iter_random = iter_Splitter_Optimus(datos,'zeros','random')
iter_grid   = iter_Splitter_Optimus(datos,'zeros','grid')

porcent_random , result_random = porcent_result(iter_random)
porcent_grid , result_grid = porcent_result(iter_grid)

print "Random" , porcent_zeros
print "Grid" , porcent_imput

pd.DataFrame(np.column_stack([iter_random,iter_grid]),columns=['Random','Grid'])

## Cargamos resultados

In [17]:
current = pd.read_csv("log.csv").drop('Unnamed: 0', 1)
current

,Base,Target,Look Back,%,Time,Indicators >90%
0,Agricultura,Agricultura,1,0.590909,606.989,Indica...
1,Agricultura,Agricultura,2,0.613636,556.706,Indica...

In [18]:
optimus = pd.read_csv("log_base.csv").drop('Unnamed: 0', 1)
optimus

,Base,Target,Look Back,%,Time,Results
0,Agricultura,Agricultura,1,0.545455,564.243,"[0.15643444150326735, 0.049425973594666162, 0...."
1,Agricultura,Agricultura,2,0.636364,574.454,"[0.4474346786034068, 0.4243037686278408, 0.423..."
2,Agricultura,Agricultura,3,0.454545,707.747,"[0.73481763173455406, 0.66178940131207709, 0.9..."
3,Agricultura,Ayuda,1,0.181818,1225.504,"[1.0, 0.60168480611699982, 0.08192142663539248..."
4,Agricultura,Ayuda,2,0.242424,1232.591,"[1.0, 0.55010499953005199, 0.88628137043969135..."
5,Agricultura,Ayuda,3,0.166667,1466.036,"[1.0, 0.57771240836484328, 0.91914047340930738..."
6,Agricultura,Clima,1,0.523077,1076.463,"[0.34659092882129983, 0.89717141284706869, 0.9..."
7,Agricultura,Clima,2,0.492308,1031.602,"[0.70820173539776432, 0.81491424608952356, 0.9..."
8,Agricultura,Clima,3,0.523077,1144.477,"[0.6957243549314851, 0.71638672030648465, 0.99..."
9,Agricultura,Economia,1,0.559524,3425.863,"[0.47939850678703388, 0.96690062633883045, 0.9..."
10,Agricultura,Economia,2,0.492063,3626.461,"[0.28728410408490856, 0.93861568734685363, 0.9..."
11,Agricultura,Economia,3,0.523810,4268.061,"[0.15609961691340402, 0.87583047624121502, 0.9..."
12,Agricultura,Educacion,1,0.129310,2603.257,"[0.58549782360218627, 0.39878001946649233, 0.5..."
13,Agricultura,Educacion,2,0.120690,2809.773,"[0.58386568014119467, 0.65263046264735736, 0.3..."
14,Agricultura,Educacion,3,0.137931,2331.567,"[0.6068751715165206, 0.51999776860375524, 0.80..."
15,Agricultura,Energia,1,0.480769,738.504,"[-0.1011505980754297, 0.076477342726747111, 0...."
16,Agricultura,Energia,2,0.519231,816.706,"[0.62252148167411159, 0.55906020539749413, 0.7..."
17,Agricultura,Energia,3,0.500000,777.198,"[0.70258253347528998, 0.74108474672734537, 0.7..."
18,Agricultura,Ambiente,1,0.471264,1182.392,"[0.34257564673862184, 0.33873818257006727, 0.6..."
19,Agricultura,Ambiente,2,0.413793,1585.165,"[0.53905295919729546, 0.65539079464952343, 0.8..."
20,Agricultura,Ambiente,3,0.413793,1617.623,"[0.72607374763585197, 0.82057173799666527, 0.6..."
21,Agricultura,Deuda,1,0.281250,3974.728,"[0.57484881671063359, 0.67022633812734878, 0.4..."
22,Agricultura,Deuda,2,0.245536,6299.709,"[0.38814471206338486, 0.67740611494173342, 0.5..."
23,Agricultura,Deuda,3,0.209821,5420.656,"[0.54140470067154811, 0.49733481595273232, 0.0..."
24,Agricultura,Finanzas,1,0.433333,1185.953,"[0.86231679409737771, 0.96963373436376799, 0.9..."
25,Agricultura,Finanzas,2,0.416667,1801.854,"[0.96887571509131687, 0.94629844546654629, 0.9..."
26,Agricultura,Finanzas,3,0.433333,1177.102,"[0.8896802793235814, 0.91952551483071265, 0.91..."
27,Agricultura,Genero,1,0.205674,3557.816,"[0.4293877777347852, 0.57483336208913771, 0.92..."

## Rendimiento Current WorkFlow Vs Optimus WorkFlow

In [19]:
pd.DataFrame.pivot_table(current, index=["Base","Target"], columns=["Look Back"] )

                                %               Time
Look Back                       1         2        1        2
Base        Target
Agricultura Agricultura  0.590909  0.613636  606.989  556.706

In [20]:
pd.DataFrame.pivot_table(optimus, index=["Base","Target"], columns=["Look Back"] )

                                %                          Time            \
Look Back                       1         2         3         1         2
Base        Target
Agricultura Agricultura  0.545455  0.636364  0.454545   564.243   574.454
            Ambiente     0.471264  0.413793  0.413793  1182.392  1585.165
            Ayuda        0.181818  0.242424  0.166667  1225.504  1232.591
            Clima        0.523077  0.492308  0.523077  1076.463  1031.602
            Deuda        0.281250  0.245536  0.209821  3974.728  6299.709
            Economia     0.559524  0.492063  0.523810  3425.863  3626.461
            Educacion    0.129310  0.120690  0.137931  2603.257  2809.773
            Energia      0.480769  0.519231  0.500000   738.504   816.706
            Finanzas     0.433333  0.416667  0.433333  1185.953  1801.854
            Genero       0.205674       NaN       NaN  3557.816       NaN


Look Back                       3
Base        Target
Agricultura Agricultura   707.747
            Ambiente     1617.623
            Ayuda        1466.036
            Clima        1144.477
            Deuda        5420.656
            Economia     4268.061
            Educacion    2331.567
            Energia       777.198
            Finanzas     1177.102
            Genero            NaN