In [135]:
import numpy as np
import pandas as pd
datos = pd.read_csv("suramerica.csv")

In [136]:
paises = np.array(['Antigua and Barbuda','Argentina','Aruba','Bahamas, The','Barbados','Belize','Bolivia','Brazil','Cayman Islands','Chile','Colombia','Costa Rica','Cuba','Curacao','Dominica','Dominican Republic','Ecuador','El Salvador','Grenada','Guatemala','Guyana','Haiti','Honduras','Jamaica','Mexico','Nicaragua','Panama','Paraguay','Peru','Puerto Rico','Sint Maarten (Dutch part)','St. Kitts and Nevis','St. Vincent and the Grenadines','St. Lucia','St. Martin (French part)','Suriname','Trinidad and Tobago','Turks and Caicos Islands','Uruguay','Venezuela, RB','Virgin Islands (U.S.)'])

# Agricultura y Desarrollo Rural

In [160]:
indicadores = np.array(['EG.ELC.ACCS.RU.ZS','EG.NSF.ACCS.RU.ZS'])
filtro = []
temporal = list()
agricultura = list()
output = {}

for k in range(len(datos)):
    cn = datos['CountryName'][k]
    indicator_code = datos['IndicatorCode'][k]

    if cn in paises and indicator_code in indicadores:
        year = datos['Year'][k]

        if cn not in output.keys():
            output[cn] = []
        output[cn].append(year)
        
for p in paises:
    if p not in output.keys():
        temporal.append(np.array([p,0]))
        
for o in output:
    temporal.append(np.array([o,np.mean(output.get(o))]))

temporal = sorted(temporal,key=lambda x:x[0])  

for i in temporal:
    filtro.append(i[1])
agricultura = filtro

pd.DataFrame(
    {'Paises': paises,
     'Agricultura': agricultura,
    }, columns=['Paises','Agricultura'])

                            Paises Agricultura
0              Antigua and Barbuda         3.0
1                        Argentina         3.0
2                            Aruba         4.0
3                     Bahamas, The         3.0
4                         Barbados         3.0
5                           Belize         3.0
6                          Bolivia         3.0
7                           Brazil         3.0
8                   Cayman Islands         4.0
9                            Chile         3.0
10                        Colombia         3.0
11                      Costa Rica         3.0
12                            Cuba         3.0
13                         Curacao         4.0
14                        Dominica         3.0
15              Dominican Republic         3.0
16                         Ecuador         3.0
17                     El Salvador         3.0
18                         Grenada         3.0
19                       Guatemala         3.0
20                          Guyana         3.0
21                           Haiti         3.0
22                        Honduras         3.0
23                         Jamaica         3.0
24                          Mexico         3.0
25                       Nicaragua         3.0
26                          Panama         3.0
27                        Paraguay         3.0
28                            Peru         3.0
29                     Puerto Rico         4.0
30       Sint Maarten (Dutch part)           0
31             St. Kitts and Nevis         3.0
32  St. Vincent and the Grenadines         3.0
33                       St. Lucia         4.0
34        St. Martin (French part)         3.0
35                        Suriname         3.0
36             Trinidad and Tobago         3.0
37        Turks and Caicos Islands         4.0
38                         Uruguay         3.0
39                   Venezuela, RB         3.0
40           Virgin Islands (U.S.)         4.0

# Ayuda y efectividad

In [161]:
indicadores = np.array(['DT.DOD.MDRI.CD','BX.GRT.EXTA.CD.WD','DT.DIS.IDAG.CD','DC.DAC.AUSL.CD'])
filtro = []
temporal = list()
ayuda = list()
output = {}

for k in range(len(datos)):
    cn = datos['CountryName'][k]
    indicator_code = datos['IndicatorCode'][k]

    if cn in paises and indicator_code in indicadores:
        year = datos['Year'][k]

        if cn not in output.keys():
            output[cn] = []
        output[cn].append(year)
        
for p in paises:
    if p not in output.keys():
        temporal.append(np.array([p,0]))
        
for o in output:
    temporal.append(np.array([o,np.mean(output.get(o))]))

temporal = sorted(temporal,key=lambda x:x[0])  

for i in temporal:
    filtro.append(i[1])
ayuda = filtro

pd.DataFrame(
    {'Paises': paises,
     'Ayuda': ayuda,
    }, columns=['Paises','Ayuda'])

                            Paises  Ayuda
0              Antigua and Barbuda   25.0
1                        Argentina   30.5
2                            Aruba   17.0
3                     Bahamas, The   21.0
4                         Barbados   34.0
5                           Belize   37.0
6                          Bolivia  36.25
7                           Brazil   42.0
8                   Cayman Islands   16.0
9                            Chile   40.0
10                        Colombia   39.5
11                      Costa Rica   36.5
12                            Cuba   27.0
13                         Curacao      0
14                        Dominica  30.25
15              Dominican Republic  34.25
16                         Ecuador  36.75
17                     El Salvador   38.0
18                         Grenada  35.25
19                       Guatemala  38.25
20                          Guyana   42.0
21                           Haiti   36.5
22                        Honduras  37.25
23                         Jamaica   42.0
24                          Mexico   42.0
25                       Nicaragua   38.5
26                          Panama  34.75
27                        Paraguay   34.5
28                            Peru   40.0
29                     Puerto Rico      0
30       Sint Maarten (Dutch part)      0
31             St. Kitts and Nevis   25.5
32  St. Vincent and the Grenadines  32.25
33                       St. Lucia      0
34        St. Martin (French part)  35.75
35                        Suriname   24.0
36             Trinidad and Tobago   30.5
37        Turks and Caicos Islands   17.5
38                         Uruguay   27.0
39                   Venezuela, RB   28.5
40           Virgin Islands (U.S.)      0

In [169]:
pd.DataFrame(
    {'Paises': paises,
     'Agricultura': agricultura,
     'Ayuda': ayuda
    }, columns=['Paises','Agricultura','Ayuda'])

                            Paises Agricultura  Ayuda
0              Antigua and Barbuda         3.0   25.0
1                        Argentina         3.0   30.5
2                            Aruba         4.0   17.0
3                     Bahamas, The         3.0   21.0
4                         Barbados         3.0   34.0
5                           Belize         3.0   37.0
6                          Bolivia         3.0  36.25
7                           Brazil         3.0   42.0
8                   Cayman Islands         4.0   16.0
9                            Chile         3.0   40.0
10                        Colombia         3.0   39.5
11                      Costa Rica         3.0   36.5
12                            Cuba         3.0   27.0
13                         Curacao         4.0      0
14                        Dominica         3.0  30.25
15              Dominican Republic         3.0  34.25
16                         Ecuador         3.0  36.75
17                     El Salvador         3.0   38.0
18                         Grenada         3.0  35.25
19                       Guatemala         3.0  38.25
20                          Guyana         3.0   42.0
21                           Haiti         3.0   36.5
22                        Honduras         3.0  37.25
23                         Jamaica         3.0   42.0
24                          Mexico         3.0   42.0
25                       Nicaragua         3.0   38.5
26                          Panama         3.0  34.75
27                        Paraguay         3.0   34.5
28                            Peru         3.0   40.0
29                     Puerto Rico         4.0      0
30       Sint Maarten (Dutch part)           0      0
31             St. Kitts and Nevis         3.0   25.5
32  St. Vincent and the Grenadines         3.0  32.25
33                       St. Lucia         4.0      0
34        St. Martin (French part)         3.0  35.75
35                        Suriname         3.0   24.0
36             Trinidad and Tobago         3.0   30.5
37        Turks and Caicos Islands         4.0   17.5
38                         Uruguay         3.0   27.0
39                   Venezuela, RB         3.0   28.5
40           Virgin Islands (U.S.)         4.0      0

In [168]:
import plotly
import plotly.plotly as py
import plotly.graph_objs as go

plotly.tools.set_credentials_file(username='ambigus9', api_key='VIIp594gf158yUUVfCUK')

data = [
    go.Heatmap(
        z=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50],
        x=[[agricultura],[ayuda]],
        y=paises,
        colorscale='Viridis'
    )
]
py.iplot(data, filename='agricultura')

In [158]:
indicadores_agricultura = np.array(['EG.ELC.ACCS.RU.ZS','EG.NSF.ACCS.RU.ZS'])
filtro = []
agricultura = list()
output = {}

for k in range(len(datos)):
    cn = datos['CountryName'][k]
    indicator_code = datos['IndicatorCode'][k]

    if cn in paises and indicator_code in indicadores_agricultura:
        year = datos['Year'][k]

        if cn not in output.keys():
            output[cn] = []
        output[cn].append(year)
        
for p in paises:
    if p not in output.keys():
        agricultura.append(np.array([p,0]))
        
for o in output:
    agricultura.append(np.array([o,np.mean(output.get(o))]))

agricultura = sorted(agricultura,key=lambda x:x[0]) 

for i in agricultura:
    filtro.append(i[1])
agricultura = filtro

pd.DataFrame(
    {'Paises': paises,
     'Agricultura': agricultura,
    }, columns=['Paises','Agricultura'])

                            Paises Agricultura
0              Antigua and Barbuda         3.0
1                        Argentina         3.0
2                            Aruba         4.0
3                     Bahamas, The         3.0
4                         Barbados         3.0
5                           Belize         3.0
6                          Bolivia         3.0
7                           Brazil         3.0
8                   Cayman Islands         4.0
9                            Chile         3.0
10                        Colombia         3.0
11                      Costa Rica         3.0
12                            Cuba         3.0
13                         Curacao         4.0
14                        Dominica         3.0
15              Dominican Republic         3.0
16                         Ecuador         3.0
17                     El Salvador         3.0
18                         Grenada         3.0
19                       Guatemala         3.0
20                          Guyana         3.0
21                           Haiti         3.0
22                        Honduras         3.0
23                         Jamaica         3.0
24                          Mexico         3.0
25                       Nicaragua         3.0
26                          Panama         3.0
27                        Paraguay         3.0
28                            Peru         3.0
29                     Puerto Rico         4.0
30       Sint Maarten (Dutch part)           0
31             St. Kitts and Nevis         3.0
32  St. Vincent and the Grenadines         3.0
33                       St. Lucia         4.0
34        St. Martin (French part)         3.0
35                        Suriname         3.0
36             Trinidad and Tobago         3.0
37        Turks and Caicos Islands         4.0
38                         Uruguay         3.0
39                   Venezuela, RB         3.0
40           Virgin Islands (U.S.)         4.0

In [202]:
indicadores_ayuda = np.array(['DT.DOD.MDRI.CD','BX.GRT.EXTA.CD.WD','DT.DIS.IDAG.CD','DC.DAC.AUSL.CD'])
filtro = []
ayuda = list()
output = {}

for k in range(len(datos)):
    cn = datos['CountryName'][k]
    indicator_code = datos['IndicatorCode'][k]

    if cn in paises and indicator_code in indicadores_ayuda:
        year = datos['Year'][k]

        if cn not in output.keys():
            output[cn] = []
        output[cn].append(year)
        
for p in paises:
    if p not in output.keys():
        ayuda.append(np.array([p,0]))
        
for o in output:
    ayuda.append(np.array([o,np.mean(output.get(o))]))

ayuda = sorted(ayuda,key=lambda x:x[0])  

for i in ayuda:
    filtro.append(i[1])
ayuda = filtro

pd.DataFrame(
    {'Paises': paises,
     'Indicador': 'Ayuda',
     'Ayuda': ayuda,
    }, columns=['Paises','Indicador','Ayuda'])

                            Paises Indicador  Ayuda
0              Antigua and Barbuda     Ayuda   25.0
1                        Argentina     Ayuda   30.5
2                            Aruba     Ayuda   17.0
3                     Bahamas, The     Ayuda   21.0
4                         Barbados     Ayuda   34.0
5                           Belize     Ayuda   37.0
6                          Bolivia     Ayuda  36.25
7                           Brazil     Ayuda   42.0
8                   Cayman Islands     Ayuda   16.0
9                            Chile     Ayuda   40.0
10                        Colombia     Ayuda   39.5
11                      Costa Rica     Ayuda   36.5
12                            Cuba     Ayuda   27.0
13                         Curacao     Ayuda      0
14                        Dominica     Ayuda  30.25
15              Dominican Republic     Ayuda  34.25
16                         Ecuador     Ayuda  36.75
17                     El Salvador     Ayuda   38.0
18                         Grenada     Ayuda  35.25
19                       Guatemala     Ayuda  38.25
20                          Guyana     Ayuda   42.0
21                           Haiti     Ayuda   36.5
22                        Honduras     Ayuda  37.25
23                         Jamaica     Ayuda   42.0
24                          Mexico     Ayuda   42.0
25                       Nicaragua     Ayuda   38.5
26                          Panama     Ayuda  34.75
27                        Paraguay     Ayuda   34.5
28                            Peru     Ayuda   40.0
29                     Puerto Rico     Ayuda      0
30       Sint Maarten (Dutch part)     Ayuda      0
31             St. Kitts and Nevis     Ayuda   25.5
32  St. Vincent and the Grenadines     Ayuda  32.25
33                       St. Lucia     Ayuda      0
34        St. Martin (French part)     Ayuda  35.75
35                        Suriname     Ayuda   24.0
36             Trinidad and Tobago     Ayuda   30.5
37        Turks and Caicos Islands     Ayuda   17.5
38                         Uruguay     Ayuda   27.0
39                   Venezuela, RB     Ayuda   28.5
40           Virgin Islands (U.S.)     Ayuda      0

In [203]:
indicadores_ayuda = np.array(['DT.DOD.MDRI.CD','BX.GRT.EXTA.CD.WD','DT.DIS.IDAG.CD','DC.DAC.AUSL.CD'])
filtro = []
ayuda = list()
output = {}

for k in range(len(datos)):
    cn = datos['CountryName'][k]
    indicator_code = datos['IndicatorCode'][k]

    if cn in paises and indicator_code in indicadores_ayuda:
        year = datos['Year'][k]

        if cn not in output.keys():
            output[cn] = []
        output[cn].append(year)
        
for p in paises:
    if p not in output.keys():
        ayuda.append(np.array([p,0]))
        
for o in output:
    ayuda.append(np.array([o,'Ayuda',np.mean(output.get(o))]))

ayuda = sorted(ayuda,key=lambda x:x[0])  
ayuda

[array(['Antigua and Barbuda', 'Ayuda', '25.0'],
       dtype='|S19'), array(['Argentina', 'Ayuda', '30.5'],
       dtype='|S9'), array(['Aruba', 'Ayuda', '17.0'],
       dtype='|S5'), array(['Bahamas, The', 'Ayuda', '21.0'],
       dtype='|S12'), array(['Barbados', 'Ayuda', '34.0'],
       dtype='|S8'), array(['Belize', 'Ayuda', '37.0'],
       dtype='|S6'), array(['Bolivia', 'Ayuda', '36.25'],
       dtype='|S7'), array(['Brazil', 'Ayuda', '42.0'],
       dtype='|S6'), array(['Cayman Islands', 'Ayuda', '16.0'],
       dtype='|S14'), array(['Chile', 'Ayuda', '40.0'],
       dtype='|S5'), array(['Colombia', 'Ayuda', '39.5'],
       dtype='|S8'), array(['Costa Rica', 'Ayuda', '36.5'],
       dtype='|S10'), array(['Cuba', 'Ayuda', '27.0'],
       dtype='|S5'), array(['Curacao', '0'],
       dtype='|S7'), array(['Dominica', 'Ayuda', '30.25'],
       dtype='|S8'), array(['Dominican Republic', 'Ayuda', '34.25'],
       dtype='|S18'), array(['Ecuador', 'Ayuda', '36.75'],
       dtype='|S7'), array(['El Salvador', 'Ayuda', '38.0'],
       dtype='|S11'), array(['Grenada', 'Ayuda', '35.25'],
       dtype='|S7'), array(['Guatemala', 'Ayuda', '38.25'],
       dtype='|S9'), array(['Guyana', 'Ayuda', '42.0'],
       dtype='|S6'), array(['Haiti', 'Ayuda', '36.5'],
       dtype='|S5'), array(['Honduras', 'Ayuda', '37.25'],
       dtype='|S8'), array(['Jamaica', 'Ayuda', '42.0'],
       dtype='|S7'), array(['Mexico', 'Ayuda', '42.0'],
       dtype='|S6'), array(['Nicaragua', 'Ayuda', '38.5'],
       dtype='|S9'), array(['Panama', 'Ayuda', '34.75'],
       dtype='|S6'), array(['Paraguay', 'Ayuda', '34.5'],
       dtype='|S8'), array(['Peru', 'Ayuda', '40.0'],
       dtype='|S5'), array(['Puerto Rico', '0'],
       dtype='|S11'), array(['Sint Maarten (Dutch part)', '0'],
       dtype='|S25'), array(['St. Kitts and Nevis', 'Ayuda', '25.5'],
       dtype='|S19'), array(['St. Lucia', 'Ayuda', '32.25'],
       dtype='|S9'), array(['St. Martin (French part)', '0'],
       dtype='|S24'), array(['St. Vincent and the Grenadines', 'Ayuda', '35.75'],
       dtype='|S30'), array(['Suriname', 'Ayuda', '24.0'],
       dtype='|S8'), array(['Trinidad and Tobago', 'Ayuda', '30.5'],
       dtype='|S19'), array(['Turks and Caicos Islands', 'Ayuda', '17.5'],
       dtype='|S24'), array(['Uruguay', 'Ayuda', '27.0'],
       dtype='|S7'), array(['Venezuela, RB', 'Ayuda', '28.5'],
       dtype='|S13'), array(['Virgin Islands (U.S.)', '0'],
       dtype='|S21')]

In [ ]:
pd.DataFrame(
    {'Paises': paises,
     'Agricultura': agricultura,
     'Ayuda': ayuda
    }, columns=['Paises','Agricultura','Ayuda'])

In [140]:
pd.DataFrame(
    {'Paises': paises,
     'Agricultura': agricultura,
     'Ayuda': ayuda
    }, columns=['Paises','Agricultura','Ayuda'])

                            Paises Agricultura  Ayuda
0              Antigua and Barbuda         3.0   25.0
1                        Argentina         3.0   30.5
2                            Aruba         4.0   17.0
3                     Bahamas, The         3.0   21.0
4                         Barbados         3.0   34.0
5                           Belize         3.0   37.0
6                          Bolivia         3.0  36.25
7                           Brazil         3.0   42.0
8                   Cayman Islands         4.0   16.0
9                            Chile         3.0   40.0
10                        Colombia         3.0   39.5
11                      Costa Rica         3.0   36.5
12                            Cuba         3.0   27.0
13                         Curacao         4.0      0
14                        Dominica         3.0  30.25
15              Dominican Republic         3.0  34.25
16                         Ecuador         3.0  36.75
17                     El Salvador         3.0   38.0
18                         Grenada         3.0  35.25
19                       Guatemala         3.0  38.25
20                          Guyana         3.0   42.0
21                           Haiti         3.0   36.5
22                        Honduras         3.0  37.25
23                         Jamaica         3.0   42.0
24                          Mexico         3.0   42.0
25                       Nicaragua         3.0   38.5
26                          Panama         3.0  34.75
27                        Paraguay         3.0   34.5
28                            Peru         3.0   40.0
29                     Puerto Rico         4.0      0
30       Sint Maarten (Dutch part)           0      0
31             St. Kitts and Nevis         3.0   25.5
32  St. Vincent and the Grenadines         3.0  32.25
33                       St. Lucia         4.0      0
34        St. Martin (French part)         3.0  35.75
35                        Suriname         3.0   24.0
36             Trinidad and Tobago         3.0   30.5
37        Turks and Caicos Islands         4.0   17.5
38                         Uruguay         3.0   27.0
39                   Venezuela, RB         3.0   28.5
40           Virgin Islands (U.S.)         4.0      0

In [146]:
glob = list()
glob.append(np.array(['EG.ELC.ACCS.RU.ZS','EG.NSF.ACCS.RU.ZS']))
glob.append(np.array(['DT.DOD.MDRI.CD','BX.GRT.EXTA.CD.WD','DT.DIS.IDAG.CD','DC.DAC.AUSL.CD']))
glob

[array(['EG.ELC.ACCS.RU.ZS', 'EG.NSF.ACCS.RU.ZS'],
       dtype='|S17'),
 array(['DT.DOD.MDRI.CD', 'BX.GRT.EXTA.CD.WD', 'DT.DIS.IDAG.CD',
        'DC.DAC.AUSL.CD'],
       dtype='|S17')]

In [147]:
for g in glob:
    print g

['EG.ELC.ACCS.RU.ZS' 'EG.NSF.ACCS.RU.ZS']
['DT.DOD.MDRI.CD' 'BX.GRT.EXTA.CD.WD' 'DT.DIS.IDAG.CD' 'DC.DAC.AUSL.CD']

In [152]:
filtro = []
temporal = list()
absoluto = list()
output = {}

for g in glob:
    
    for k in range(len(datos)):
        cn = datos['CountryName'][k]
        indicator_code = datos['IndicatorCode'][k]

        if cn in paises and indicator_code in g:
            year = datos['Year'][k]

            if cn not in output.keys():
                output[cn] = []
            output[cn].append(year)

    for p in paises:
        if p not in output.keys():
            temporal.append(np.array([p,0]))

    for o in output:
        temporal.append(np.array([o,np.mean(output.get(o))]))

    temporal = sorted(temporal,key=lambda x:x[0]) 

    for i in temporal:
        filtro.append(i[1])
    temporal = filtro
    
    absoluto.append(np.array([temporal]))
    temporal = []

absoluto[1]

array([['3.0', '3.0', '4.0', '3.0', '3.0', '3.0', '3.0', '3.0', '4.0',
        '3.0', '3.0', '3.0', '3.0', '4.0', '3.0', '3.0', '3.0', '3.0',
        '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0', '3.0',
        '3.0', '3.0', '4.0', '0', '3.0', '3.0', '4.0', '3.0', '3.0', '3.0',
        '4.0', '3.0', '3.0', '4.0', '14.0', '16.75', '10.5', '12.0',
        '18.5', '25.6666666667', '25.1666666667', '29.0', '12.0', '21.5',
        '27.3333333333', '25.3333333333', '15.0', '4.0', '21.1666666667',
        '23.8333333333', '25.5', '26.3333333333', '24.5', '26.5', '29.0',
        '25.3333333333', '25.8333333333', '29.0', '29.0', '26.6666666667',
        '24.1666666667', '24.0', '27.6666666667', '4.0', '0', '14.25',
        '22.5', '4.0', '24.8333333333', '13.5', '16.75', '13.0', '15.0',
        '15.75', '4.0']],
      dtype='|S13')

In [153]:
indicadores = np.array(['DT.DOD.MDRI.CD','BX.GRT.EXTA.CD.WD','DT.DIS.IDAG.CD','DC.DAC.AUSL.CD'])
filtro = []
temporal = list()
ayuda = list()
output = {}

for k in range(len(datos)):
    cn = datos['CountryName'][k]
    indicator_code = datos['IndicatorCode'][k]

    if cn in paises and indicator_code in indicadores:
        year = datos['Year'][k]

        if cn not in output.keys():
            output[cn] = []
        output[cn].append(year)
        
for p in paises:
    if p not in output.keys():
        temporal.append(np.array([p,0]))
        
for o in output:
    temporal.append(np.array([o,np.mean(output.get(o))]))

temporal = sorted(temporal,key=lambda x:x[0])  

for i in temporal:
    filtro.append(i[1])
ayuda = filtro

pd.DataFrame(
    {'Paises': paises,
     'Ayuda': ayuda,
    }, columns=['Paises','Ayuda'])

                            Paises  Ayuda
0              Antigua and Barbuda   25.0
1                        Argentina   30.5
2                            Aruba   17.0
3                     Bahamas, The   21.0
4                         Barbados   34.0
5                           Belize   37.0
6                          Bolivia  36.25
7                           Brazil   42.0
8                   Cayman Islands   16.0
9                            Chile   40.0
10                        Colombia   39.5
11                      Costa Rica   36.5
12                            Cuba   27.0
13                         Curacao      0
14                        Dominica  30.25
15              Dominican Republic  34.25
16                         Ecuador  36.75
17                     El Salvador   38.0
18                         Grenada  35.25
19                       Guatemala  38.25
20                          Guyana   42.0
21                           Haiti   36.5
22                        Honduras  37.25
23                         Jamaica   42.0
24                          Mexico   42.0
25                       Nicaragua   38.5
26                          Panama  34.75
27                        Paraguay   34.5
28                            Peru   40.0
29                     Puerto Rico      0
30       Sint Maarten (Dutch part)      0
31             St. Kitts and Nevis   25.5
32  St. Vincent and the Grenadines  32.25
33                       St. Lucia      0
34        St. Martin (French part)  35.75
35                        Suriname   24.0
36             Trinidad and Tobago   30.5
37        Turks and Caicos Islands   17.5
38                         Uruguay   27.0
39                   Venezuela, RB   28.5
40           Virgin Islands (U.S.)      0

In [154]:
ayuda

['25.0',
 '30.5',
 '17.0',
 '21.0',
 '34.0',
 '37.0',
 '36.25',
 '42.0',
 '16.0',
 '40.0',
 '39.5',
 '36.5',
 '27.0',
 '0',
 '30.25',
 '34.25',
 '36.75',
 '38.0',
 '35.25',
 '38.25',
 '42.0',
 '36.5',
 '37.25',
 '42.0',
 '42.0',
 '38.5',
 '34.75',
 '34.5',
 '40.0',
 '0',
 '0',
 '25.5',
 '32.25',
 '0',
 '35.75',
 '24.0',
 '30.5',
 '17.5',
 '27.0',
 '28.5',
 '0']

In [198]:
import csv

with open('agricultura.csv', 'wb') as myfile:
    wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
    for i in paises:
        wr.writerow(i)

In [199]:
glo = pd.read_csv("agricultura.csv")
glo

CParserError: Error tokenizing data. C error: Expected 19 fields in line 31, saw 25

In [192]:
np.savetxt("file_name.csv", np.hstack((agricultura,ayuda)), delimiter=",", fmt='%s')

In [193]:
b = pd.read_csv("file_name.csv")
b

      3.0
0    3.00
1    4.00
2    3.00
3    3.00
4    3.00
5    3.00
6    3.00
7    4.00
8    3.00
9    3.00
10   3.00
11   3.00
12   4.00
13   3.00
14   3.00
15   3.00
16   3.00
17   3.00
18   3.00
19   3.00
20   3.00
21   3.00
22   3.00
23   3.00
24   3.00
25   3.00
26   3.00
27   3.00
28   4.00
29   0.00
..    ...
51  36.50
52  27.00
53   0.00
54  30.25
55  34.25
56  36.75
57  38.00
58  35.25
59  38.25
60  42.00
61  36.50
62  37.25
63  42.00
64  42.00
65  38.50
66  34.75
67  34.50
68  40.00
69   0.00
70   0.00
71  25.50
72  32.25
73   0.00
74  35.75
75  24.00
76  30.50
77  17.50
78  27.00
79  28.50
80   0.00

[81 rows x 1 columns]