In [2]:
import numpy as np
import pandas as pd
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
import time

plotly.tools.set_credentials_file(username='ambigus9', api_key='VIIp594gf158yUUVfCUK')

datos = pd.read_csv("suramerica.csv").drop('Unnamed: 0', 1)
datos.head()

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
0,Antigua and Barbuda,ATG,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1960,126.144000
1,Antigua and Barbuda,ATG,Age dependency ratio (% of working-age populat...,SP.POP.DPND,1960,88.237117
2,Antigua and Barbuda,ATG,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,1960,7.779958
3,Antigua and Barbuda,ATG,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,1960,80.457159
4,Antigua and Barbuda,ATG,"Birth rate, crude (per 1,000 people)",SP.DYN.CBRT.IN,1960,32.920000

In [2]:
suramerica = np.array(['Antigua and Barbuda','Argentina','Aruba','Bahamas, The','Barbados','Belize','Bolivia','Brazil','Cayman Islands','Chile','Colombia','Costa Rica','Cuba','Curacao','Dominica','Dominican Republic','Ecuador','El Salvador','Grenada','Guatemala','Guyana','Haiti','Honduras','Jamaica','Mexico','Nicaragua','Panama','Paraguay','Peru','Puerto Rico','Sint Maarten (Dutch part)','St. Kitts and Nevis','St. Lucia','St. Martin (French part)','St. Vincent and the Grenadines','Suriname','Trinidad and Tobago','Turks and Caicos Islands','Uruguay','Venezuela, RB','Virgin Islands (U.S.)'])

In [3]:
def tabla_1(continente,datos_continente,x_indicators,y_indicator,years):
    
    datos = datos_continente
    paises = continente
                
    #Creamos una lista temporal que contiene todos los valores de los indicadores en 0          
    indicadores = list()
    for i in x_indicators: indicadores.append(i)
    for i in y_indicator: indicadores.append(i)
    temporal = list()

    for i in paises:
        for j in indicadores:
            for k in years:
                temporal.append([i,k,j,0.])
                
    #Agregamos valores de los indicadores a nuestra lista temporal              
    for k in range(len(datos)):
        cn = datos['CountryName'][k]
        indicator_code = datos['IndicatorCode'][k]
        indicator_name = datos['IndicatorName'][k]
        y = datos['Year'][k]
        v = datos['Value'][k]

        for i in range(len(temporal)):
            if cn == temporal[i][0] and y == temporal[i][1] and indicator_code == temporal[i][2]:
                temporal[i][3] = v
        
    #Consolidamos la tabla 1 en base a la lista temporal   
    valores = list()
    paises2 = list()
    years2 = list()
    matriz = []

    for i in paises:
        for j in years: paises2.append(i)
    matriz.append(paises2)        

    for i in temporal: years2.append(i[1])
    matriz.append(years2)

    for i in range(len(indicadores)):
        for k in range(len(temporal)):
            if indicadores[i] == temporal[k][2]:
                valores.append(temporal[k][3])
        matriz.append(valores)
        valores = list()

    matriz = np.array(matriz)
    return matriz

In [101]:
cn = datos['CountryName']
indices = numpy.flatnonzero((cn == 'Colombia'))

datos_colombia = datos.reindex([indices])
datos_colombia = datos_colombia.reset_index(drop=True)
pd.DataFrame(datos_colombia)

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
0,Colombia,COL,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1960,1.279940e+02
1,Colombia,COL,Age dependency ratio (% of working-age populat...,SP.POP.DPND,1960,9.846913e+01
2,Colombia,COL,"Age dependency ratio, old (% of working-age po...",SP.POP.DPND.OL,1960,6.296202e+00
3,Colombia,COL,"Age dependency ratio, young (% of working-age ...",SP.POP.DPND.YG,1960,9.217292e+01
4,Colombia,COL,Arms imports (SIPRI trend indicator values),MS.MIL.MPRT.KD,1960,5.000000e+06
5,Colombia,COL,"Birth rate, crude (per 1,000 people)",SP.DYN.CBRT.IN,1960,4.490400e+01
6,Colombia,COL,Changes in inventories (current LCU),NE.GDI.STKB.CN,1960,3.396163e+08
7,Colombia,COL,Changes in inventories (current US$),NE.GDI.STKB.CD,1960,5.118558e+07
8,Colombia,COL,CO2 emissions (kg per 2005 US$ of GDP),EN.ATM.CO2E.KD.GD,1960,7.058072e-01
9,Colombia,COL,CO2 emissions (kt),EN.ATM.CO2E.KT,1960,1.640983e+04
10,Colombia,COL,CO2 emissions (metric tons per capita),EN.ATM.CO2E.PC,1960,9.957186e-01
11,Colombia,COL,CO2 emissions from gaseous fuel consumption (%...,EN.ATM.CO2E.GF.ZS,1960,4.201117e+00
12,Colombia,COL,CO2 emissions from gaseous fuel consumption (kt),EN.ATM.CO2E.GF.KT,1960,6.893960e+02
13,Colombia,COL,CO2 emissions from liquid fuel consumption (% ...,EN.ATM.CO2E.LF.ZS,1960,4.837989e+01
14,Colombia,COL,CO2 emissions from liquid fuel consumption (kt),EN.ATM.CO2E.LF.KT,1960,7.939055e+03
15,Colombia,COL,CO2 emissions from solid fuel consumption (% o...,EN.ATM.CO2E.SF.ZS,1960,4.073743e+01
16,Colombia,COL,CO2 emissions from solid fuel consumption (kt),EN.ATM.CO2E.SF.KT,1960,6.684941e+03
17,Colombia,COL,Consumer price index (2010 = 100),FP.CPI.TOTL,1960,5.726239e-02
18,Colombia,COL,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,1960,1.219800e+01
19,Colombia,COL,DEC alternative conversion factor (LCU per US$),PA.NUS.ATLS,1960,6.635000e+00
20,Colombia,COL,Discrepancy in expenditure estimate of GDP (co...,NY.GDP.DISC.KN,1960,-1.248214e+12
21,Colombia,COL,Discrepancy in expenditure estimate of GDP (cu...,NY.GDP.DISC.CN,1960,-9.521990e+07
22,Colombia,COL,Exports as a capacity to import (constant LCU),NY.EXP.CAPM.KN,1960,5.544511e+12
23,Colombia,COL,Exports of goods and services (% of GDP),NE.EXP.GNFS.ZS,1960,1.565654e+01
24,Colombia,COL,Exports of goods and services (constant 2005 US$),NE.EXP.GNFS.KD,1960,2.793884e+09
25,Colombia,COL,Exports of goods and services (constant LCU),NE.EXP.GNFS.KN,1960,6.484141e+12
26,Colombia,COL,Exports of goods and services (current LCU),NE.EXP.GNFS.CN,1960,4.197782e+09
27,Colombia,COL,Exports of goods and services (current US$),NE.EXP.GNFS.CD,1960,6.326725e+08
28,Colombia,COL,External balance on goods and services (% of GDP),NE.RSB.GNFS.ZS,1960,9.348746e-01
29,Colombia,COL,External balance on goods and services (consta...,NE.RSB.GNFS.KN,1960,-5.553246e+10
...,...,...,...,...,...,...
37197,Colombia,COL,"PPG, multilateral (INT, current US$)",DT.INT.MLAT.CD,2015,2.278750e+08
37198,Colombia,COL,"PPG, official creditors (AMT, current US$)",DT.AMT.OFFT.CD,2015,1.677797e+09
37199,Colombia,COL,"PPG, official creditors (DIS, current US$)",DT.DIS.OFFT.CD,2015,7.371370e+08
37200,Colombia,COL,"PPG, official creditors (INT, current US$)",DT.INT.OFFT.CD,2015,3.881530e+08
37201,Colombia,COL,"PPG, other private creditors (AMT, current US$)",DT.AMT.PROP.CD,2015,2.172000e+06
37202,Colombia,COL,"PPG, other private creditors (DIS, current US$)",DT.DIS.PROP.CD,2015,0.000000e+00
37203,Colombia,COL,"PPG, other private creditors (INT, current US$)",DT.INT.PROP.CD,2015,1.600000e+05
37204,Colombia,COL,"PPG, private creditors (AMT, current US$)",DT.AMT.PRVT.CD,2015,1.075769e+09
37205,Colombia,COL,"PPG, private creditors (DIS, current US$)",DT.DIS.PRVT.CD,2015,9.384210e+08
37206,Colombia,COL,"PPG, private creditors (INT, current US$)",DT.INT.PRVT.CD,2015,2.110857e+09
37207,Colombia,COL,"Principal repayments on external debt, long-te...",DT.AMT.DLXF.CD,2015,8.363187e+09
37208,Colombia,COL,"Principal repayments on external debt, private...",DT.AMT.DPNG.CD,2015,5.609621e+09
37209,Colombia,COL,Private credit bureau coverage (% of adults),IC.CRD.PRVT.ZS,2015,8.870000e+01
37210,Colombia,COL,Procedures to build a warehouse (number),IC.WRH.PROC,2015,1.000000e+01
37211,Colombia,COL,Procedures to register property (number),IC.PRP.PROC,2015,6.000000e+00
37212,Colombia,COL,Profit tax (% of commercial profits),IC.TAX.PRFT.CP.ZS,2015,2.250000e+01
37213,Colombia,COL,Proportion of seats held by women in national ...,SG.GEN.PARL.ZS,2015,1.987952e+01
37214,Colombia,COL,Public credit registry coverage (% of adults),IC.CRD.PUBL.ZS,2015,0.000000e+00
37215,Colombia,COL,Source data assessment of statistical capacity...,IQ.SCI.SRCE,2015,8.000000e+01
37216,Colombia,COL,Start-up procedures to register a business (nu...,IC.REG.PROC,2015,8.000000e+00
37217,Colombia,COL,Strength of legal rights index (0=weak to 12=s...,IC.LGL.CRED.XQ,2015,1.200000e+01
37218,Colombia,COL,Tax payments (number),IC.TAX.PAYM,2015,1.100000e+01
37219,Colombia,COL,Time required to build a warehouse (days),IC.WRH.DURS,2015,7.300000e+01
37220,Colombia,COL,Time required to enforce a contract (days),IC.LGL.DURS,2015,1.288000e+03
37221,Colombia,COL,Time required to get electricity (days),IC.ELC.TIME,2015,1.020000e+02
37222,Colombia,COL,Time required to register property (days),IC.PRP.DURS,2015,1.600000e+01
37223,Colombia,COL,Time required to start a business (days),IC.REG.DURS,2015,1.100000e+01
37224,Colombia,COL,Time to prepare and pay taxes (hours),IC.TAX.DURS,2015,2.390000e+02
37225,Colombia,COL,Time to resolve insolvency (years),IC.ISV.DURS,2015,1.700000e+00
37226,Colombia,COL,Total tax rate (% of commercial profits),IC.TAX.TOTL.CP.ZS,2015,6.970000e+01

In [102]:
def tabla_v2(continente,datos_continente,x_indicators,y_indicator,years):
    
    datos = datos_continente
    paises = continente
                
    #Creamos una lista temporal que contiene todos los valores de los indicadores en 0          
    indicadores = list()
    for i in x_indicators: indicadores.append(i)
    for i in y_indicator: indicadores.append(i)
    temporal = list()

    for i in paises:
        for j in indicadores:
            for k in years:
                temporal.append([i,k,j,0.])
                
    for k in paises:
        cn = datos['CountryName']
        indices = numpy.flatnonzero((cn == k))
        datos_colombia = datos.reindex([indices])
        datos_colombia = datos_colombia.reset_index(drop=True)
                
    #Agregamos valores de los indicadores a nuestra lista temporal              
    for k in range(len(datos)):
        cn = datos['CountryName'][k]
        indicator_code = datos['IndicatorCode'][k]
        indicator_name = datos['IndicatorName'][k]
        y = datos['Year'][k]
        v = datos['Value'][k]

        for i in range(len(temporal)):
            if cn == temporal[i][0] and y == temporal[i][1] and indicator_code == temporal[i][2]:
                temporal[i][3] = v
        
    #Consolidamos la tabla 1 en base a la lista temporal   
    valores = list()
    paises2 = list()
    years2 = list()
    matriz = []

    for i in paises:
        for j in years: paises2.append(i)
    matriz.append(paises2)        

    for i in temporal: years2.append(i[1])
    matriz.append(years2)

    for i in range(len(indicadores)):
        for k in range(len(temporal)):
            if indicadores[i] == temporal[k][2]:
                valores.append(temporal[k][3])
        matriz.append(valores)
        valores = list()

    matriz = np.array(matriz)
    return matriz

In [99]:
cn = datos_colombia['CountryName'][252123]
cn

'Colombia'

In [103]:
start_time = time.time()

tabla1 = tabla_v2(suramerica,datos,x_indicators,y_indicator,years)
tabla2 = np.array(zip(*tabla1[2:]))

print("--- %s seconds ---" % (time.time() - start_time))

--- 21.5009999275 seconds ---

In [104]:
pd.DataFrame(tabla2).to_csv('economia9.csv')
pd.DataFrame(zip(*tabla1),columns=np.hstack((np.array(['Pais']),np.array(['Año']),x_name_indicators,y_name_indicator)))

,Pais,Año,GDP (constant LCU),GDP (current LCU),GDP (current US$),GDP at market prices (constant 2010 US$),GDP deflator (base year varies by country),GDP growth (annual %),GDP per capita (constant 2010 US$),GDP per capita (constant LCU),GDP per capita (current LCU),GDP per capita (current US$),GDP per capita growth (annual %),"GDP per capita, PPP (constant 2011 international $)","GDP per capita, PPP (current international $)","GDP, PPP (constant 2011 international $)","GDP, PPP (current international $)"
0,Antigua and Barbuda,2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Antigua and Barbuda,2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Antigua and Barbuda,2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Antigua and Barbuda,2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Antigua and Barbuda,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Argentina,2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Argentina,2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Argentina,2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Argentina,2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Argentina,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Aruba,2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Aruba,2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,Aruba,2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,Aruba,2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,Aruba,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,"Bahamas, The",2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,"Bahamas, The",2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,"Bahamas, The",2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,"Bahamas, The",2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,"Bahamas, The",2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,Barbados,2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,Barbados,2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,Barbados,2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,Barbados,2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,Barbados,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,Belize,2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,Belize,2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,Belize,2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,Belize,2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,Belize,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,Suriname,2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
176,Suriname,2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
177,Suriname,2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
178,Suriname,2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
179,Suriname,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
180,Trinidad and Tobago,2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
181,Trinidad and Tobago,2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
182,Trinidad and Tobago,2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
183,Trinidad and Tobago,2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
184,Trinidad and Tobago,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
185,Turks and Caicos Islands,2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
186,Turks and Caicos Islands,2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
187,Turks and Caicos Islands,2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
188,Turks and Caicos Islands,2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
189,Turks and Caicos Islands,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
190,Uruguay,2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
191,Uruguay,2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
192,Uruguay,2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
193,Uruguay,2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
194,Uruguay,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
195,"Venezuela, RB",2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
196,"Venezuela, RB",2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
197,"Venezuela, RB",2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
198,"Venezuela, RB",2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
199,"Venezuela, RB",2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
200,Virgin Islands (U.S.),2008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
201,Virgin Islands (U.S.),2009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
202,Virgin Islands (U.S.),2010,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
203,Virgin Islands (U.S.),2011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
204,Virgin Islands (U.S.),2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [92]:
name_indicators = np.array(['GDP (constant LCU)','GDP (current LCU)','GDP (current US$)','GDP at market prices (constant 2010 US$)','GDP deflator (base year varies by country)','GDP growth (annual %)','GDP per capita (constant 2010 US$)','GDP per capita (constant LCU)','GDP per capita (current LCU)','GDP per capita (current US$)','GDP per capita growth (annual %)','GDP per capita, PPP (constant 2011 international $)','GDP per capita, PPP (current international $)','GDP, PPP (constant 2011 international $)','GDP, PPP (current international $)'])
x_name_indicators = np.array(['GDP (constant LCU)','GDP (current LCU)','GDP (current US$)','GDP at market prices (constant 2010 US$)','GDP deflator (base year varies by country)','GDP growth (annual %)','GDP per capita (constant 2010 US$)','GDP per capita (constant LCU)','GDP per capita (current LCU)','GDP per capita (current US$)','GDP per capita growth (annual %)','GDP per capita, PPP (constant 2011 international $)','GDP per capita, PPP (current international $)','GDP, PPP (constant 2011 international $)'])
y_name_indicator = np.array(['GDP, PPP (current international $)'])
x_indicators = np.array(['NY.GDP.MKTP.KN','NY.GDP.MKTP.CN','NY.GDP.MKTP.CD','NY.GDP.MKTP.KD','NY.GDP.DEFL.ZS','NY.GDP.MKTP.KD.ZG','NY.GDP.PCAP.KD','NY.GDP.PCAP.KN','NY.GDP.PCAP.CN','NY.GDP.PCAP.CD','NY.GDP.PCAP.KD.ZG','NY.GDP.PCAP.PP.KD','NY.GDP.PCAP.PP.CD','NY.GDP.MKTP.PP.KD'])
y_indicator = np.array(['NY.GDP.MKTP.PP.CD'])
years = np.array([2008,2009,2010,2011,2012])

In [5]:
start_time = time.time()

tabla1 = tabla_1(suramerica,pd.read_csv("suramerica.csv"),x_indicators,y_indicator,years)
tabla2 = np.array(zip(*tabla1[2:]))

print("--- %s seconds ---" % (time.time() - start_time))

--- 635.090999842 seconds ---

In [6]:
pd.DataFrame(tabla2).to_csv('economia8.csv')
pd.DataFrame(zip(*tabla1),columns=np.hstack((np.array(['Pais']),np.array(['Año']),x_name_indicators,y_name_indicator)))

,Pais,Año,GDP (constant LCU),GDP (current LCU),GDP (current US$),GDP at market prices (constant 2010 US$),GDP deflator (base year varies by country),GDP growth (annual %),GDP per capita (constant 2010 US$),GDP per capita (constant LCU),GDP per capita (current LCU),GDP per capita (current US$),GDP per capita growth (annual %),"GDP per capita, PPP (constant 2011 international $)","GDP per capita, PPP (current international $)","GDP, PPP (constant 2011 international $)","GDP, PPP (current international $)"
0,Antigua and Barbuda,2008,3.358406e+09,3.637845e+09,1.347350e+09,1.239080e+09,108.320559,0.071111,14517.635341,39348.639719,42622.666667,15786.172840,-1.046262,25735.714754,24723.111892,2.196543e+09,2.110118e+09
1,Antigua and Barbuda,2009,2.954188e+09,3.257308e+09,1.206410e+09,1.089944e+09,110.260684,-12.036015,12629.713786,34231.611819,37744.009270,13979.262693,-13.004332,22388.956865,21671.375749,1.932167e+09,1.870240e+09
2,Antigua and Barbuda,2010,2.743171e+09,3.065955e+09,1.135539e+09,1.012090e+09,111.766847,-7.142991,11602.142227,31446.478970,35146.738046,13017.310387,-8.136143,20567.359344,20151.309866,1.794152e+09,1.757859e+09
3,Antigua and Barbuda,2011,2.693974e+09,3.050780e+09,1.129918e+09,9.939385e+08,113.244595,-1.793436,11275.280156,30560.551094,34608.172248,12817.841573,-2.817256,19987.924139,19987.924139,1.761975e+09,1.761975e+09
4,Antigua and Barbuda,2012,2.802259e+09,3.252725e+09,1.204713e+09,1.033890e+09,116.075112,4.019542,11607.745344,31461.665675,36519.163794,13525.616220,2.948620,20577.292107,20946.700835,1.832799e+09,1.865702e+09
5,Argentina,2008,7.058647e+11,1.283906e+12,4.037820e+11,2.663823e+11,181.891166,3.074946,6596.583217,17479.748134,31794.117656,9999.093517,2.023423,0.000000,0.000000,0.000000e+00,0.000000e+00
6,Argentina,2009,7.062178e+11,1.411526e+12,3.766279e+11,2.665156e+11,199.871182,0.050024,6532.461614,17309.837526,34597.376834,9231.382900,-0.972043,0.000000,0.000000,0.000000e+00,0.000000e+00
7,Argentina,2010,7.729666e+11,1.810830e+12,4.616402e+11,2.917055e+11,234.270156,9.451578,7076.301272,18750.913904,43927.795332,11198.642567,8.325187,0.000000,0.000000,0.000000e+00,0.000000e+00
8,Argentina,2011,8.377910e+11,2.312009e+12,5.578902e+11,3.161692e+11,275.964823,8.386451,7590.074325,20112.319237,55502.926232,13392.916904,7.260475,0.000000,0.000000,0.000000e+00,0.000000e+00
9,Argentina,2012,8.445081e+11,2.765575e+12,6.043785e+11,3.187041e+11,327.477653,0.801760,7571.028495,20061.851245,65698.079692,14357.411589,-0.250931,0.000000,0.000000,0.000000e+00,0.000000e+00
10,Aruba,2008,3.293180e+09,4.997610e+09,2.791961e+09,2.140527e+09,151.756357,-6.881302,21121.812032,32495.707604,49314.302066,27549.889423,-6.995240,0.000000,0.000000,0.000000e+00,0.000000e+00
11,Aruba,2009,3.107000e+09,4.473090e+09,2.498933e+09,2.019512e+09,143.968136,-5.653502,19913.149353,30636.191528,44106.354027,24640.421244,-5.722344,0.000000,0.000000,0.000000e+00,0.000000e+00
12,Aruba,2010,0.000000e+00,4.417190e+09,2.467704e+09,0.000000e+00,0.000000,0.000000,0.000000,0.000000,43477.563314,24289.141516,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
13,Aruba,2011,0.000000e+00,4.626190e+09,2.584464e+09,0.000000e+00,0.000000,0.000000,0.000000,0.000000,45383.279705,25353.787545,0.000000,36015.070460,36015.070460,3.671232e+09,3.671232e+09
14,Aruba,2012,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
15,"Bahamas, The",2008,7.893019e+09,8.246650e+09,8.246650e+09,7.828204e+09,104.480301,-2.323937,22456.959177,22642.895461,23657.365306,23657.365306,-4.097079,24356.137496,23397.815772,8.490233e+09,8.156174e+09
16,"Bahamas, The",2009,7.563465e+09,7.820420e+09,7.820420e+09,7.501356e+09,103.397319,-4.175259,21143.684034,21318.746829,22043.012571,22043.012571,-5.847965,22931.799068,22196.819494,8.135744e+09,7.874988e+09
17,"Bahamas, The",2010,7.679850e+09,7.909580e+09,7.909580e+09,7.616786e+09,102.991334,1.538779,21109.069382,21283.845578,21920.516587,21920.516587,-0.163712,22894.257064,22431.137635,8.260935e+09,8.093827e+09
18,"Bahamas, The",2011,7.726920e+09,7.889750e+09,7.889750e+09,7.663469e+09,102.107308,0.612903,20897.843209,21070.870522,21514.898653,21514.898653,-1.000642,22665.167557,22665.167557,8.311566e+09,8.311566e+09
19,"Bahamas, The",2012,7.898250e+09,8.234470e+09,8.234470e+09,7.833392e+09,104.256892,2.217313,21035.565253,21209.732859,22112.608355,22112.608355,0.659025,22814.536713,23224.109020,8.495860e+09,8.648380e+09
20,Barbados,2008,1.141000e+09,9.190000e+09,4.595000e+09,4.207235e+09,805.433830,0.440141,15171.321780,4114.454681,33139.209924,16569.604962,0.019641,16077.271231,15444.691525,4.458468e+09,4.283045e+09
21,Barbados,2009,1.095000e+09,9.204000e+09,4.602000e+09,4.037618e+09,840.547945,-4.031551,14499.501768,3932.257439,33052.509103,16526.254552,-4.428223,15365.333754,14872.864480,4.278723e+09,4.141587e+09
22,Barbados,2010,1.098000e+09,8.891000e+09,4.445500e+09,4.048680e+09,809.744991,0.273973,14482.019369,3927.516222,31802.865871,15901.432935,-0.120572,15346.807401,15036.362531,4.290446e+09,4.203656e+09
23,Barbados,2011,1.106000e+09,8.716000e+09,4.358000e+09,4.078179e+09,788.065099,0.728597,14533.676909,3941.525720,31061.788583,15530.894292,0.356701,15401.549650,15401.549650,4.321706e+09,4.321706e+09
24,Barbados,2012,1.109000e+09,8.626000e+09,4.313000e+09,4.089241e+09,777.817854,0.271248,14522.483045,3938.489950,30634.278003,15317.139001,-0.077020,15389.687349,15665.966891,4.333428e+09,4.411223e+09
25,Belize,2008,2.353310e+09,2.737250e+09,1.368625e+09,1.216177e+09,116.314910,3.229101,3972.292734,7686.410596,8940.441592,4470.220796,0.612002,7951.230903,7638.380094,2.434389e+09,2.338605e+09
26,Belize,2009,2.370095e+09,2.673914e+09,1.336957e+09,1.224851e+09,112.818879,0.713251,3901.732567,7549.876244,8517.685753,4258.842876,-1.776308,7809.992526,7559.677016,2.451752e+09,2.373172e+09
27,Belize,2010,2.448874e+09,2.794227e+09,1.397113e+09,1.265564e+09,114.102527,3.323871,3935.100940,7614.444248,8688.273338,4344.136669,0.855219,7876.785094,7717.448532,2.533245e+09,2.482001e+09
28,Belize,2011,2.500397e+09,2.974011e+09,1.487006e+09,1.292191e+09,118.941565,2.103951,3925.328666,7595.534838,9034.247994,4517.123997,-0.248336,7857.224198,7857.224198,2.586543e+09,2.586543e+09
29,Belize,2012,2.596031e+09,3.147735e+09,1.573867e+09,1.341614e+09,121.251820,3.824749,3984.514038,7710.058894,9348.586753,4674.293377,1.507781,7975.693957,8118.875623,2.685472e+09,2.733682e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,Suriname,2008,8.395000e+09,9.698000e+09,3.532969e+09,2.039032e+09,115.521144,4.143407,4024.481275,16569.395074,19141.154667,6973.098239,2.970949,13698.376446,13159.397236,6.940378e+09,6.667301e+09
176,Suriname,2009,8.648000e+09,1.063800e+10,3.875410e+09,2.100482e+09,123.011101,3.013699,4098.325295,16873.422019,20756.182174,7561.450701,1.834871,13949.723916,13502.625889,7.149540e+09,6.920393e+09
177,Suriname,2010,9.094000e+09,1.199300e+10,4.368398e+09,2.208809e+09,131.878161,5.157262,4262.950097,17551.207104,23146.209237,8430.905965,4.016880,14510.067562,14216.548791,7.518261e+09,7.366177e+09
178,Suriname,2011,9.573000e+09,1.445200e+10,4.422277e+09,2.325152e+09,150.966259,5.267209,4442.068375,18288.664009,27609.711924,8448.504261,4.201745,15119.743549,15119.743549,7.914263e+09,7.914263e+09
179,Suriname,2012,9.867000e+09,1.643400e+10,4.980000e+09,2.396560e+09,166.555184,3.071138,4534.345766,18668.583916,31093.494281,9422.270994,2.077352,15433.833827,15710.905898,8.157321e+09,8.303764e+09
180,Trinidad and Tobago,2008,9.292100e+10,1.752870e+11,2.787023e+10,1.959583e+10,188.640888,3.390302,14897.560446,70642.373412,133260.400860,21188.094391,2.909889,31618.612461,30374.539865,4.159024e+10,3.995382e+10
181,Trinidad and Tobago,2009,8.884200e+10,1.212810e+11,1.917516e+10,1.873563e+10,136.513136,-4.389750,14176.214775,67221.842218,91766.644674,14508.789811,-4.842039,30087.626949,29123.298283,3.976453e+10,3.849005e+10
182,Trinidad and Tobago,2010,8.875900e+10,1.341250e+11,2.103757e+10,1.871812e+10,151.111437,-0.093424,14093.963197,66831.815495,100990.516492,15840.407261,-0.580208,29913.056033,29307.955926,3.972738e+10,3.892375e+10
183,Trinidad and Tobago,2011,8.876500e+10,1.564500e+11,2.440984e+10,1.871939e+10,176.251901,0.006760,14024.219072,66501.097551,117209.448677,18287.402474,-0.494851,29765.030960,29765.030960,3.973007e+10,3.973007e+10
184,Trinidad and Tobago,2012,8.997800e+10,1.580450e+11,2.458084e+10,1.897519e+10,175.648492,1.366530,14143.925437,67068.730205,117805.213111,18322.323801,0.853569,30019.095993,30558.006362,4.027299e+10,4.099598e+10
185,Turks and Caicos Islands,2008,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
186,Turks and Caicos Islands,2009,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
187,Turks and Caicos Islands,2010,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
188,Turks and Caicos Islands,2011,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
189,Turks and Caicos Islands,2012,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
190,Uruguay,2008,5.052072e+11,6.361509e+11,3.036621e+10,2.063873e+10,125.918805,7.176145,6159.285387,150770.683281,189848.643113,9062.290535,6.821688,15307.821407,14705.516637,5.129394e+10,4.927572e+10
191,Uruguay,2009,5.266457e+11,7.145234e+11,3.166091e+10,2.151453e+10,135.674418,4.243494,6397.877786,156611.091184,212481.186055,9415.153583,3.873703,15900.800885,15391.169530,5.347059e+10,5.175682e+10
192,Uruguay,2010,5.677420e+11,8.080785e+11,4.028468e+10,2.319340e+10,142.331996,7.803410,6873.312262,168249.061526,239472.246974,11938.275054,7.431128,17082.409721,16736.855995,5.764312e+10,5.647708e+10
193,Uruguay,2011,5.970496e+11,9.263561e+11,4.796244e+10,2.439068e+10,155.155647,5.162133,7204.218838,176349.191254,273615.728096,14166.557667,4.814368,17904.819864,17904.819864,6.061874e+10,6.061874e+10
194,Uruguay,2012,6.168902e+11,1.043637e+12,5.138487e+10,2.520121e+10,169.177100,3.323115,7419.204610,181611.741978,307245.478226,15127.644151,2.984165,18439.129220,18770.153110,6.263317e+10,6.375757e+10
195,"Venezuela, RB",2008,5.852507e+10,6.775936e+11,3.156002e+11,1.830507e+11,1157.783478,5.277966,6510.387860,2081.504611,24099.316471,11224.646703,3.607786,17913.002134,17208.193373,5.036548e+11,4.838379e+11
196,"Venezuela, RB",2009,5.665092e+10,7.072625e+11,3.294190e+11,1.771889e+11,1248.457217,-3.202303,6204.395342,1983.672523,24765.302768,11534.840600,-4.700066,17071.079232,16523.939669,4.875262e+11,4.719007e+11
197,"Venezuela, RB",2010,5.580751e+10,1.016835e+12,3.938015e+11,1.745509e+11,1822.039270,-1.488791,6019.880351,1924.679293,35068.412555,13581.353377,-2.973940,16563.395588,16228.340806,4.802680e+11,4.705528e+11
198,"Venezuela, RB",2011,5.813827e+10,1.357487e+12,3.164822e+11,1.818409e+11,2334.928584,4.176425,6179.257320,1975.635382,46129.675236,10754.592879,2.647511,17001.913240,17001.913240,5.003260e+11,5.003260e+11
199,"Venezuela, RB",2012,6.140910e+10,1.635451e+12,3.812862e+11,1.920712e+11,2663.206235,5.625957,6433.632482,2056.964341,54781.202588,12771.595036,4.116598,17701.813601,18019.601015,5.284742e+11,5.379615e+11
200,Virgin Islands (U.S.),2008,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
201,Virgin Islands (U.S.),2009,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
202,Virgin Islands (U.S.),2010,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
203,Virgin Islands (U.S.),2011,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00
204,Virgin Islands (U.S.),2012,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00

In [ ]:
def tabla_optimizada(paises,indicadores,years):
    
    #Agregamos valores de los indicadores a nuestra lista temporal              
    for k in range(len(datos)):
        cn = datos['CountryName'][k]
        indicator_code = datos['IndicatorCode'][k]
        y = datos['Year'][k]
        v = datos['Value'][k]

        if cn == temporal[i][0] and y == temporal[i][1] and indicator_code == temporal[i][2]:
                temporal[i][3] = v
                
    return matriz

In [9]:
#Agregamos valores de los indicadores a nuestra lista temporal              

from bisect import bisect_left

In [13]:
bisect_left(datos['CountryName'],'Venezuela')

938469

In [16]:
In [56]: import random, numpy

In [57]: lst = numpy.array([random.uniform(0, 5) for _ in xrange(1000)]) # example list

In [58]: a, b = 1, 3

In [59]: numpy.flatnonzero((lst > a) & (lst < b))[:10]
Out[59]: array([ 0, 12, 13, 15, 18, 19, 23, 24, 26, 29])

In [2]:
import random, numpy

start_time = time.time()


cn = datos['CountryName']
y = datos['Year']
indicator = datos['IndicatorCode']
years = np.array([2012,2013,2014,2015])
paises = np.array(['Antigua and Barbuda','Argentina','Aruba','Bahamas, The','Barbados','Belize','Bolivia','Brazil','Cayman Islands','Chile','Colombia','Costa Rica','Cuba','Curacao','Dominica','Dominican Republic','Ecuador','El Salvador','Grenada','Guatemala','Guyana','Haiti','Honduras','Jamaica','Mexico','Nicaragua','Panama','Paraguay','Peru','Puerto Rico','Sint Maarten (Dutch part)','St. Kitts and Nevis','St. Lucia','St. Martin (French part)','St. Vincent and the Grenadines','Suriname','Trinidad and Tobago','Turks and Caicos Islands','Uruguay','Venezuela, RB','Virgin Islands (U.S.)'])
indicators = np.array(['NY.GDP.MKTP.KN','NY.GDP.MKTP.CN','NY.GDP.MKTP.CD','NY.GDP.MKTP.KD','NY.GDP.DEFL.ZS','NY.GDP.MKTP.KD.ZG','NY.GDP.PCAP.KD','NY.GDP.PCAP.KN','NY.GDP.PCAP.CN','NY.GDP.PCAP.CD','NY.GDP.PCAP.KD.ZG','NY.GDP.PCAP.PP.KD','NY.GDP.PCAP.PP.CD','NY.GDP.MKTP.PP.KD'])

temporal = []

for i in paises:
    print datos['Value'][numpy.flatnonzero((cn == i))]
            
print("--- %s seconds ---" % (time.time() - start_time))

0        1.261440e+02
1        8.823712e+01
2        7.779958e+00
3        8.045716e+01
4        3.292000e+01
5        3.667000e+01
6        6.706169e-01
7        0.000000e+00
8        0.000000e+00
9        1.000000e+02
10       3.667000e+01
11       0.000000e+00
12       0.000000e+00
13       9.098000e+00
14       1.714290e+00
15       4.425000e+00
16       7.706422e+00
17       8.902544e+00
18       4.868000e+03
19       6.416700e+01
20       5.951200e+01
21       6.178273e+01
22       2.000000e+06
23       9.000000e+06
24       0.000000e+00
25       0.000000e+00
26       2.449240e+02
27       2.755520e+02
28       1.714290e+00
29       2.935780e-01
             ...
13821    6.300000e+00
13822    4.900000e+00
13823    8.100000e+00
13824    7.300000e+00
13825    8.800000e+00
13826    9.000000e+00
13827    7.000000e+00
13828    1.200000e+01
13829    5.300000e+00
13830    5.777780e+01
13831    6.333340e+01
13832    4.000000e+00
13833    0.000000e+00
13834    1.600000e+01
13835    7.000000e+00
13836    2.590000e+01
13837    1.111111e+01
13838    0.000000e+00
13839    6.000000e+01
13840    8.000000e+00
13841    5.000000e+00
13842    5.700000e+01
13843    1.100000e+02
13844    3.510000e+02
13845    4.200000e+01
13846    3.900000e+01
13847    2.100000e+01
13848    2.070000e+02
13849    3.000000e+00
13850    4.190000e+01
Name: Value, dtype: float64
13851    6.137800e+01
13852    5.699722e+01
13853    8.758858e+00
13854    4.823837e+01
13855    1.030000e+08
13856    2.368200e+01
13857    5.062746e+09
13858    0.000000e+00
13859    6.401767e-01
13860    4.881510e+04
13861    2.367473e+00
13862    4.845252e+00
13863    2.365215e+03
13864    8.445012e+01
13865    4.122441e+04
13866    8.007812e+00
13867    3.909022e+03
13868    8.637000e+00
13869    8.145357e+09
13870   -3.308512e-03
13871    1.475655e+10
13872    7.604049e+00
13873    3.943428e+09
13874    1.106041e+10
13875    1.000000e-02
13876    2.129133e-06
13877   -4.939740e+09
13878    2.800000e-09
13879    3.109000e+00
13880    5.654634e+10
             ...
39776    6.300000e+00
39777    1.250000e+01
39778    1.130000e+01
39779    1.370000e+01
39780    8.464000e+03
39781    3.900000e+02
39782    4.797000e+03
39783    9.513000e+03
39784    1.081000e+02
39785    9.555557e+01
39786    8.666670e+01
39787    7.000000e+01
39788    1.000000e+02
39789    2.100000e+01
39790    7.000000e+00
39791    0.000000e+00
39792    3.618677e+01
39793    4.260000e+01
39794    1.000000e+02
39795    1.400000e+01
39796    2.000000e+00
39797    9.000000e+00
39798    3.410000e+02
39799    5.900000e+02
39800    9.200000e+01
39801    5.150000e+01
39802    2.500000e+01
39803    4.050000e+02
39804    2.800000e+00
39805    1.374000e+02
Name: Value, dtype: float64
39806    1.062062e+02
39807    8.633301e+01
39808    4.630139e+00
39809    8.170287e+01
39810    3.567900e+01
39811    6.389000e+00
39812    4.820000e+00
39813    1.456058e+01
39814    7.893000e+03
39815    6.712900e+01
39816    6.408400e+01
39817    6.556937e+01
39818    0.000000e+00
39819    0.000000e+00
39820    1.814840e+02
39821    2.272530e+02
39822    2.484873e+00
39823    3.134888e+00
39824    4.384777e+01
39825    5.366736e+01
39826    5.097772e+01
39827    5.420800e+04
39828    2.668300e+04
39829    4.922400e+01
39830    3.163869e+00
39831    6.991539e+01
39832    6.302099e+01
39833    2.752500e+04
39834    5.077600e+01
39835    3.106802e+00
             ...
47383    1.883586e+01
47384    6.941058e+01
47385    5.243569e+01
47386    1.034410e+05
47387    1.548395e+00
47388    0.000000e+00
47389    6.022400e+04
47390    5.822100e+01
47391    9.845063e-01
47392    3.500000e+01
47393    3.383571e+02
47394    1.800000e+02
47395    6.000000e+00
47396    5.000000e+00
47397    6.803510e+08
47398    5.597510e+08
47399    1.800000e+01
47400    4.321700e+04
47401    4.177900e+01
47402   -1.618423e-01
47403    1.000000e+00
47404    2.300000e+01
47405    9.770000e+01
47406    9.770000e+01
47407    9.770000e+01
47408    9.810000e+01
47409    9.810000e+01
47410    9.810000e+01
47411    2.000000e+00
47412    2.000000e+00
Name: Value, dtype: float64
47413    9.184240e+01
47414    8.576638e+01
47415    7.020133e+00
47416    7.874625e+01
47417    3.438800e+01
47418    2.802378e-01
47419    4.107040e+02
47420    3.749831e+00
47421    0.000000e+00
47422    0.000000e+00
47423    1.000000e+02
47424    4.107040e+02
47425    0.000000e+00
47426    0.000000e+00
47427    8.285000e+00
47428    1.020010e+00
47429    4.495000e+00
47430    1.477690e+09
47431    1.732000e+08
47432    1.465555e+09
47433    1.698023e+08
47434    1.172100e+01
47435    1.338089e+04
47436    1.349168e+04
47437    1.581360e+03
47438    1.550337e+03
47439    1.525998e+08
47440    1.496062e+08
47441    1.393275e+03
47442    5.725664e+00
             ...
65548    9.900000e+00
65549    9.200000e+00
65550    1.060000e+01
65551    6.900000e+00
65552    1.210000e+01
65553    1.120000e+01
65554    1.290000e+01
65555    5.700000e+01
65556    5.000000e+00
65557    4.000000e+01
65558    7.000000e+01
65559    2.740000e+01
65560    8.000000e+00
65561    0.000000e+00
65562    1.600000e+01
65563    7.000000e+00
65564    0.000000e+00
65565    1.315789e+01
65566    0.000000e+00
65567    8.000000e+00
65568    6.000000e+00
65569    1.900000e+01
65570    1.800000e+02
65571    4.270000e+02
65572    6.700000e+01
65573    1.220000e+02
65574    2.850000e+01
65575    5.800000e+01
65576    3.000000e+00
65577    3.370000e+01
Name: Value, dtype: float64
65578    1.249270e+02
65579    8.146059e+01
65580    1.235856e+01
65581    6.910202e+01
65582    3.057600e+01
65583    1.723490e+02
65584    7.463128e-01
65585    2.127660e+00
65586    3.667000e+00
65587    9.574468e+01
65588    1.650150e+02
65589    2.127660e+00
65590    3.667000e+00
65591    1.245700e+01
65592    1.714290e+00
65593    4.333000e+00
65594    6.933000e+03
65595    3.003145e+00
65596    5.929779e+00
65597    4.226316e+00
65598    9.760000e+03
65599    6.302500e+01
65600    5.856000e+01
65601    6.073805e+01
65602    2.386470e+07
65603    4.859100e+07
65604    0.000000e+00
65605    0.000000e+00
65606    2.252310e+02
65607    2.941360e+02
             ...
83159    1.200000e+01
83160    1.100000e+01
83161    1.300000e+01
83162    8.000000e+00
83163    1.300000e+01
83164    1.180000e+01
83165    1.410000e+01
83166    4.100000e+01
83167    1.000000e+00
83168    2.700000e+01
83169    4.400000e+01
83170    3.000000e+00
83171    3.000000e+00
83172    0.000000e+00
83173    9.000000e+00
83174    6.000000e+00
83175    1.950000e+01
83176    1.666667e+01
83177    0.000000e+00
83178    8.000000e+00
83179    7.000000e+00
83180    2.800000e+01
83181    4.420000e+02
83182    1.340000e+03
83183    8.700000e+01
83184    1.180000e+02
83185    1.800000e+01
83186    2.370000e+02
83187    1.800000e+00
83188    3.470000e+01
Name: Value, dtype: float64
83189     1.817200e+02
83190     9.772781e+01
83191     8.206086e+00
83192     8.952172e+01
83193     4.496700e+01
83194     4.920013e-01
83195     4.400400e+01
83196     4.779511e-01
83197     0.000000e+00
83198     0.000000e+00
83199     1.000000e+02
83200     4.400400e+01
83201     0.000000e+00
83202     0.000000e+00
83203     1.118100e+01
83204     1.428570e+00
83205     6.500000e+00
83206     1.018000e+03
83207     1.105704e+00
83208     1.730646e+08
83209     4.010350e+07
83210     8.943879e+07
83211     2.807248e+07
83212     2.317256e+01
83213     9.714427e+02
83214     1.879748e+03
83215     4.355857e+02
83216     3.049103e+02
83217     3.990180e+07
83218     2.793129e+07
              ...
112848    7.758000e+06
112849    4.367000e+07
112850    4.594000e+07
112851    9.689000e+06
112852    0.000000e+00
112853    0.000000e+00
112854    0.000000e+00
112855    2.758000e+07
112856    0.000000e+00
112857    2.684400e+07
112858    7.125000e+07
112859    0.000000e+00
112860    0.000000e+00
112861    1.500000e+01
112862    9.000000e+00
112863    2.470000e+01
112864    3.125000e+00
112865    0.000000e+00
112866    4.000000e+01
112867    9.000000e+00
112868    4.000000e+00
112869    2.900000e+01
112870    1.090000e+02
112871    8.920000e+02
112872    6.600000e+01
112873    6.000000e+01
112874    4.300000e+01
112875    1.470000e+02
112876    2.000000e+00
112877    3.110000e+01
Name: Value, dtype: float64
112878    1.028358e+02
112879    8.837823e+01
112880    8.657098e+00
112881    7.972113e+01
112882    6.000000e+06
112883    4.453900e+01
112884    3.427390e-01
112885    1.004758e+03
112886    2.720377e-01
112887    1.094891e+00
112888    1.100100e+01
112889    9.635036e+01
112890    9.680880e+02
112891    7.299270e-01
112892    7.334000e+00
112893    2.243134e-05
112894    2.377200e+01
112895    1.197980e-05
112896    2.049105e+09
112897    2.345946e+03
112898    8.703632e+08
112899    1.334135e+01
112900    4.165976e+08
112901    1.094010e+09
112902    9.000000e+02
112903    7.512646e+07
112904   -5.929487e+00
112905   -4.000000e+02
112906   -3.338954e+07
112907    6.700000e+00
              ...
148155    5.711800e+07
148156    3.109570e+08
148157    6.293920e+08
148158    7.272900e+07
148159    0.000000e+00
148160    0.000000e+00
148161    0.000000e+00
148162    2.198000e+06
148163    1.455400e+07
148164    5.427600e+07
148165    3.131550e+08
148166    0.000000e+00
148167    4.320000e+01
148168    1.200000e+01
148169    7.000000e+00
148170    0.000000e+00
148171    5.307692e+01
148172    1.500000e+01
148173    8.000000e+01
148174    1.500000e+01
148175    0.000000e+00
148176    4.200000e+01
148177    2.750000e+02
148178    5.910000e+02
148179    4.200000e+01
148180    9.100000e+01
148181    5.000000e+01
148182    1.025000e+03
148183    1.800000e+00
148184    8.370000e+01
Name: Value, dtype: float64
148185    9.204680e+01
148186    8.688871e+01
148187    5.865863e+00
148188    8.102284e+01
148189    2.059281e+01
148190    1.820725e-04
148191    2.679301e+09
148192    2.000000e+06
148193    2.360000e+08
148194    4.312400e+01
148195    3.777917e-01
148196    4.690826e+04
148197    6.470678e-01
148198    2.423390e-01
148199    1.136770e+02
148200    8.324734e+01
148201    3.904988e+04
148202    1.059256e+01
148203    4.968785e+03
148204    1.341000e+01
148205    6.795522e-14
148206    1.000000e-10
148207    1.391600e+10
148208    7.059046e+00
148209    4.550528e+09
148210    6.628418e+09
148211    7.274910e-05
148212    1.070545e+09
148213   -5.823907e-02
148214   -7.402398e+09
              ...
183705    1.766658e+09
183706    2.499500e+08
183707    3.936734e+09
183708    3.412871e+09
183709    3.355930e+08
183710    2.521600e+07
183711    1.378000e+06
183712    1.616690e+08
183713    1.072994e+10
183714    8.897723e+09
183715    5.314254e+09
183716    1.485046e+10
183717    1.837840e+08
183718    7.900000e+01
183719    1.820000e+01
183720    1.360000e+01
183721    9.941520e+00
183722    5.510000e+01
183723    6.000000e+01
183724    1.100000e+01
183725    2.000000e+00
183726    9.600000e+00
183727    4.257000e+02
183728    7.310000e+02
183729    4.360000e+01
183730    3.170000e+01
183731    8.300000e+01
183732    2.600000e+03
183733    4.000000e+00
183734    6.920000e+01
Name: Value, dtype: float64
183735       11.001000
183736        1.398373
183737        0.000000
183738        0.000000
183739      100.000000
183740       11.001000
183741        0.000000
183742        0.000000
183743       12.164739
183744      957.000000
183745        0.000000
183746        0.000000
183747        2.575139
183748     7867.000000
183749        0.000000
183750        0.000000
183751     7867.000000
183752      100.000000
183753        2.575139
183754       11.250000
183755       27.000000
183756        0.833333
183757        0.024919
183758      200.000000
183759       11.001000
183760        1.370670
183761        0.000000
183762        0.000000
183763      100.000000
183764       11.001000
              ...
187711      240.000000
187712        1.113892
187713    91059.000000
187714      153.748354
187715       11.000000
187716        5.000000
187717      246.550000
187718        1.366353
187719    59172.000000
187720        6.000000
187721        6.000000
187722        0.000000
187723        0.000000
187724      140.000000
187725     2365.983911
187726      264.000000
187727        6.000000
187728        6.000000
187729        0.000000
187730    59172.000000
187731      100.000000
187732        1.366353
187733        1.000000
187734       32.000000
187735       95.600000
187736       95.600000
187737       97.400000
187738       97.400000
187739        1.000000
187740       22.000000
Name: Value, dtype: float64
187741    8.869180e+01
187742    7.789292e+01
187743    8.768604e+00
187744    6.912431e+01
187745    9.404462e+00
187746    1.151869e+09
187747    6.046887e+11
187748    4.000000e+05
187749    3.780903e+08
187750    3.120000e+08
187751    3.603800e+01
187752    1.992553e+11
187753    4.210000e+04
187754    3.979401e+07
187755    7.114192e-01
187756    1.349089e+04
187757    1.753045e+00
187758    6.795325e-01
187759    9.167500e+01
187760    5.137266e+01
187761    6.930630e+03
187762    3.346018e+01
187763    4.514077e+03
187764    1.235500e+01
187765    1.057948e-03
187766    1.050815e+12
187767   -4.000000e+02
187768    1.399035e+12
187769    1.346560e+01
187770    2.104431e+09
              ...
214867    4.900000e+00
214868    8.100000e+00
214869    7.400000e+00
214870    8.700000e+00
214871    1.636000e+03
214872    5.200000e+01
214873    1.144000e+03
214874    1.896000e+03
214875    2.600000e+00
214876    9.555557e+01
214877    9.666670e+01
214878    7.200000e+01
214879    1.120000e+01
214880    1.300000e+01
214881    6.000000e+00
214882    2.230000e+01
214883    1.583333e+01
214884    4.510000e+01
214885    1.000000e+02
214886    7.000000e+00
214887    4.000000e+00
214888    7.000000e+00
214889    1.520000e+02
214890    4.800000e+02
214891    3.000000e+01
214892    2.850000e+01
214893    5.500000e+00
214894    2.910000e+02
214895    3.200000e+00
214896    2.890000e+01
Name: Value, dtype: float64
214897    1.279940e+02
214898    9.846913e+01
214899    6.296202e+00
214900    9.217292e+01
214901    5.000000e+06
214902    4.490400e+01
214903    3.396163e+08
214904    5.118558e+07
214905    7.058072e-01
214906    1.640983e+04
214907    9.957186e-01
214908    4.201117e+00
214909    6.893960e+02
214910    4.837989e+01
214911    7.939055e+03
214912    4.073743e+01
214913    6.684941e+03
214914    5.726239e-02
214915    1.219800e+01
214916    6.635000e+00
214917   -1.248214e+12
214918   -9.521990e+07
214919    5.544511e+12
214920    1.565654e+01
214921    2.793884e+09
214922    6.484141e+12
214923    4.197782e+09
214924    6.326725e+08
214925    9.348746e-01
214926   -5.553246e+10
              ...
252094    2.278750e+08
252095    1.677797e+09
252096    7.371370e+08
252097    3.881530e+08
252098    2.172000e+06
252099    0.000000e+00
252100    1.600000e+05
252101    1.075769e+09
252102    9.384210e+08
252103    2.110857e+09
252104    8.363187e+09
252105    5.609621e+09
252106    8.870000e+01
252107    1.000000e+01
252108    6.000000e+00
252109    2.250000e+01
252110    1.987952e+01
252111    0.000000e+00
252112    8.000000e+01
252113    8.000000e+00
252114    1.200000e+01
252115    1.100000e+01
252116    7.300000e+01
252117    1.288000e+03
252118    1.020000e+02
252119    1.600000e+01
252120    1.100000e+01
252121    2.390000e+02
252122    1.700000e+00
252123    6.970000e+01
Name: Value, dtype: float64
252124    1.189184e+02
252125    9.136296e+01
252126    5.782195e+00
252127    8.558076e+01
252128    3.129825e+08
252129    3.240368e+10
252130    7.446999e+08
252131    1.321264e+08
252132    4.455800e+01
252133   -2.818432e+09
252134    4.020000e+07
252135    7.132378e+06
252136    1.999231e-01
252137    4.913780e+02
252138    3.686140e-01
252139    0.000000e+00
252140    0.000000e+00
252141    1.000000e+02
252142    4.913780e+02
252143    0.000000e+00
252144    0.000000e+00
252145    2.492243e-01
252146    1.004500e+01
252147    5.636269e+00
252148    3.227177e+09
252149   -3.000000e+02
252150    3.600137e+10
252151    2.141581e+01
252152    3.034564e+08
252153    3.052006e+10
              ...
288551    2.752800e+07
288552    3.933000e+06
288553    1.011000e+06
288554    1.294090e+08
288555    3.024400e+07
288556    3.755390e+08
288557    4.292800e+08
288558    3.487100e+07
288559    1.000000e+02
288560    1.500000e+01
288561    5.000000e+00
288562    1.930000e+01
288563    3.333333e+01
288564    2.750000e+01
288565    1.190000e+01
288566    2.790000e+01
288567    8.000000e+01
288568    9.000000e+00
288569    1.000000e+01
288570    9.000000e+00
288571    1.180000e+02
288572    8.520000e+02
288573    4.500000e+01
288574    1.900000e+01
288575    2.400000e+01
288576    1.510000e+02
288577    3.000000e+00
288578    5.800000e+01
288579    7.600000e+00
288580    1.940000e+01
Name: Value, dtype: float64
288581    1.030398e+02
288582    6.587137e+01
288583    7.715934e+00
288584    5.815543e+01
288585    1.270000e+08
288586    3.195000e+01
288587    1.369991e+04
288588    1.918452e+00
288589    0.000000e+00
288590    0.000000e+00
288591    9.769807e+01
288592    1.338455e+04
288593    8.297645e-01
288594    1.136770e+02
288595    8.830000e+00
288596    4.182000e+00
288597    1.554020e+05
288598    2.176154e+00
288599    4.366499e+00
288600    2.011111e+00
288601    1.436160e+05
288602    6.562000e+01
288603    6.227100e+01
288604    6.390466e+01
288605    6.180000e+08
288606    6.380000e+08
288607    0.000000e+00
288608    0.000000e+00
288609    1.788800e+02
288610    2.207630e+02
              ...
309193    7.100000e+00
309194    8.758502e+06
309195    7.697000e+01
309196    2.734453e-01
309197    2.089701e+01
309198    1.700000e+01
309199    4.400000e+01
309200    9.320000e+01
309201    8.910000e+01
309202    9.440000e+01
309203    9.490000e+01
309204    8.980000e+01
309205    9.640000e+01
309206    5.661020e-02
309207    1.800000e+03
309208    1.200000e+01
309209    3.900000e+01
309210    4.000000e+00
309211    3.500000e+00
309212    4.400000e+00
309213    2.300000e+00
309214    5.500000e+00
309215    4.900000e+00
309216    6.000000e+00
309217    4.690000e+02
309218    4.500000e+01
309219    2.700000e+02
309220    6.470000e+02
309221    1.770000e+02
309222    4.885621e+01
Name: Value, dtype: float64
309223    1.057542e+02
309224    8.550453e+01
309225    9.034032e+00
309226    7.647050e+01
309227    4.870056e+00
309228    7.357202e-01
309229    4.122295e+01
309230    5.390699e+01
309231    4.987592e+01
309232    1.248260e+05
309233    3.156800e+04
309234    2.529000e+01
309235   -8.233875e-01
309236    6.835949e+01
309237    6.196170e+01
309238    9.325800e+04
309239    7.471000e+01
309240    1.269036e+00
309241    1.025856e+02
309242    8.579636e+01
309243    8.932886e+00
309244    7.686347e+01
309245    4.440000e+02
309246    4.807640e+00
309247    2.840653e+02
309248    1.035271e+00
309249    4.136969e+01
309250    5.382267e+01
309251    5.002142e+01
309252    1.261250e+05
              ...
310757    1.780000e+09
310758    1.967870e+05
310759    1.215966e+02
310760    1.200000e+01
310761    6.000000e+00
310762    1.210391e+08
310763    1.432737e+08
310764    1.445529e+01
310765    3.510631e+02
310766    1.324557e+00
310767    1.906550e+01
310768    6.647920e+01
310769    5.394413e+01
310770    1.558720e+05
310771    3.700000e+01
310772    3.500000e+01
310773    1.647600e+04
310774    1.057000e+01
310775    2.345824e+00
310776    4.440000e+02
310777    6.000000e+00
310778    6.000000e+00
310779    8.700000e+01
310780    1.393960e+05
310781    8.943000e+01
310782    1.204534e+00
310783    1.000000e+00
310784    2.800000e+01
310785    3.000000e+00
310786    2.000000e+00
Name: Value, dtype: float64
310787    1.100100e+01
310788    1.833011e-01
310789    0.000000e+00
310790    0.000000e+00
310791    1.000000e+02
310792    1.100100e+01
310793    0.000000e+00
310794    0.000000e+00
310795    1.714290e+00
310796    4.543947e+00
310797    3.982271e+00
310798    2.390000e+03
310799    3.605570e+06
310800    5.812320e+06

In [25]:
start_time = time.time()

pais = np.array(['Colombia'])
indicadores = np.array(['NY.GDP.MKTP.KN','NY.GDP.MKTP.CN'])

for i in pais:
    for j in indicadores:
        for k in years:
            print datos['Value'][numpy.flatnonzero((cn == i) & (indicator == j) & (y == k))]
    
print("--- %s seconds ---" % (time.time() - start_time))

249652    4.708800e+14
Name: Value, dtype: float64
250669    4.941240e+14
Name: Value, dtype: float64
251535    5.166190e+14
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
249653    6.642400e+14
Name: Value, dtype: float64
250670    7.102570e+14
Name: Value, dtype: float64
251536    7.561520e+14
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
--- 2.32899999619 seconds ---

In [26]:
datos[249652:249652+1]

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
249652,Colombia,COL,GDP (constant LCU),NY.GDP.MKTP.KN,2012,4.708800e+14

In [27]:
datos[250669:250669+1]

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
250669,Colombia,COL,GDP (constant LCU),NY.GDP.MKTP.KN,2013,4.941240e+14

In [28]:
datos[251535:251535+1]

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
251535,Colombia,COL,GDP (constant LCU),NY.GDP.MKTP.KN,2014,5.166190e+14

In [41]:
datos[64339:64339+1]

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
64339,"Bahamas, The",BHS,GDP (constant LCU),NY.GDP.MKTP.KN,2012,7.898250e+09

In [40]:
datos[38118:38118+1]

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
38118,Argentina,ARG,GDP (constant LCU),NY.GDP.MKTP.KN,2012,8.445081e+11

In [39]:
datos[12769:12769+1]

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
12769,Antigua and Barbuda,ATG,GDP (constant LCU),NY.GDP.MKTP.KN,2012,2.802259e+09

In [147]:
y = datos['Year']
indicator = datos['IndicatorCode']
paises = np.array(['Antigua and Barbuda','Argentina','Aruba','Bahamas, The','Barbados','Belize','Bolivia','Brazil','Cayman Islands','Chile','Colombia','Costa Rica','Cuba','Curacao','Dominica','Dominican Republic','Ecuador','El Salvador','Grenada','Guatemala','Guyana','Haiti','Honduras','Jamaica','Mexico','Nicaragua','Panama','Paraguay','Peru','Puerto Rico','Sint Maarten (Dutch part)','St. Kitts and Nevis','St. Lucia','St. Martin (French part)','St. Vincent and the Grenadines','Suriname','Trinidad and Tobago','Turks and Caicos Islands','Uruguay','Venezuela, RB','Virgin Islands (U.S.)'])
years = range(2008,2012+1)
indicators = np.array(['NY.GDP.MKTP.KN','NY.GDP.MKTP.CN','NY.GDP.MKTP.CD','NY.GDP.MKTP.KD','NY.GDP.DEFL.ZS','NY.GDP.MKTP.KD.ZG','NY.GDP.PCAP.KD','NY.GDP.PCAP.KN','NY.GDP.PCAP.CN','NY.GDP.PCAP.CD','NY.GDP.PCAP.KD.ZG','NY.GDP.PCAP.PP.KD','NY.GDP.PCAP.PP.CD','NY.GDP.MKTP.PP.KD'])

In [148]:
start_time = time.time()

indices_total = []
temp = []

for i in indicators:
    for j in years:
        indices_total.append([np.flatnonzero((indicator == i) & (y == j))])
    
for i in indices_total:
    lista_indice = np.array(i).flatten()
    for j in lista_indice:
        temp.append(j)
        
datos_v2 = datos.reindex([temp])

print("--- %s seconds ---" % (time.time() - start_time))

pd.DataFrame.pivot_table(datos_v2, values='Value', index=['CountryName', 'Year'], columns=['IndicatorName'])

--- 11.0249998569 seconds ---

IndicatorName                        GDP (constant LCU)  GDP (current LCU)  \
CountryName                    Year
Antigua and Barbuda            2008        3.358406e+09       3.637845e+09
                               2009        2.954188e+09       3.257308e+09
                               2010        2.743171e+09       3.065955e+09
                               2011        2.693974e+09       3.050780e+09
                               2012        2.802259e+09       3.252725e+09
Argentina                      2008        7.058647e+11       1.283906e+12
                               2009        7.062178e+11       1.411526e+12
                               2010        7.729666e+11       1.810830e+12
                               2011        8.377910e+11       2.312009e+12
                               2012        8.445081e+11       2.765575e+12
Aruba                          2008        3.293180e+09       4.997610e+09
                               2009        3.107000e+09       4.473090e+09
                               2010                 NaN       4.417190e+09
                               2011                 NaN       4.626190e+09
Bahamas, The                   2008        7.893019e+09       8.246650e+09
                               2009        7.563465e+09       7.820420e+09
                               2010        7.679850e+09       7.909580e+09
                               2011        7.726920e+09       7.889750e+09
                               2012        7.898250e+09       8.234470e+09
Barbados                       2008        1.141000e+09       9.190000e+09
                               2009        1.095000e+09       9.204000e+09
                               2010        1.098000e+09       8.891000e+09
                               2011        1.106000e+09       8.716000e+09
                               2012        1.109000e+09       8.626000e+09
Belize                         2008        2.353310e+09       2.737250e+09
                               2009        2.370095e+09       2.673914e+09
                               2010        2.448874e+09       2.794227e+09
                               2011        2.500397e+09       2.974011e+09
                               2012        2.596031e+09       3.147735e+09
Bolivia                        2008        3.027783e+10       1.206938e+11
...                                                 ...                ...
St. Lucia                      2008        3.001301e+09       3.225132e+09
                               2009        2.987686e+09       3.204361e+09
                               2010        2.936394e+09       3.373642e+09
                               2011        2.957003e+09       3.483068e+09
                               2012        2.925769e+09       3.540059e+09
St. Vincent and the Grenadines 2008        1.731660e+09       1.877658e+09
                               2009        1.695311e+09       1.822291e+09
                               2010        1.638262e+09       1.839310e+09
                               2011        1.631322e+09       1.825549e+09
                               2012        1.653842e+09       1.870921e+09
Suriname                       2008        8.395000e+09       9.698000e+09
                               2009        8.648000e+09       1.063800e+10
                               2010        9.094000e+09       1.199300e+10
                               2011        9.573000e+09       1.445200e+10
                               2012        9.867000e+09       1.643400e+10
Trinidad and Tobago            2008        9.292100e+10       1.752870e+11
                               2009        8.884200e+10       1.212810e+11
                               2010        8.875900e+10       1.341250e+11
                               2011        8.876500e+10       1.564500e+11
                               2012        8.997800e+10       1.580450e+11
Uruguay                        2008        5.052072e+11       6.361509e+11
                               2009        5.266457e+11       7.145234e+11
                               2010        5.677420e+11       8.080785e+11
                               2011        5.970496e+11       9.263561e+11
                               2012        6.168902e+11       1.043637e+12
Venezuela, RB                  2008        5.852507e+10       6.775936e+11
                               2009        5.665092e+10       7.072625e+11
                               2010        5.580751e+10       1.016835e+12
                               2011        5.813827e+10       1.357487e+12
                               2012        6.140910e+10       1.635451e+12

IndicatorName                        GDP at market prices (constant 2005 US$)  \
CountryName                    Year
Antigua and Barbuda            2008                              1.239080e+09
                               2009                              1.089944e+09
                               2010                              1.012090e+09
                               2011                              9.939385e+08
                               2012                              1.033890e+09
Argentina                      2008                              2.663823e+11
                               2009                              2.665156e+11
                               2010                              2.917055e+11
                               2011                              3.161692e+11
                               2012                              3.187041e+11
Aruba                          2008                              2.140527e+09
                               2009                              2.019512e+09
                               2010                                       NaN
                               2011                                       NaN
Bahamas, The                   2008                              7.828204e+09
                               2009                              7.501356e+09
                               2010                              7.616786e+09
                               2011                              7.663469e+09
                               2012                              7.833392e+09
Barbados                       2008                              4.207235e+09
                               2009                              4.037618e+09
                               2010                              4.048680e+09
                               2011                              4.078179e+09
                               2012                              4.089241e+09
Belize                         2008                              1.216177e+09
                               2009                              1.224851e+09
                               2010                              1.265564e+09
                               2011                              1.292191e+09
                               2012                              1.341614e+09
Bolivia                        2008                              1.110729e+10
...                                                                       ...
St. Lucia                      2008                              1.059686e+09
                               2009                              1.054878e+09
                               2010                              1.036769e+09
                               2011                              1.044045e+09
                               2012                              1.033017e+09
St. Vincent and the Grenadines 2008                              6.226055e+08
                               2009                              6.095367e+08
                               2010                              5.890250e+08
                               2011                              5.865297e+08
                               2012                              5.946267e+08
Suriname                       2008                              2.039032e+09
                               2009                              2.100482e+09
                               2010                              2.208809e+09
                               2011                              2.325152e+09
                               2012                              2.396560e+09
Trinidad and Tobago            2008                              1.959583e+10
                               2009                              1.873563e+10
                               2010                              1.871812e+10
                               2011                              1.871939e+10
                               2012                              1.897519e+10
Uruguay                        2008                              2.063873e+10
                               2009                              2.151453e+10
                               2010                              2.319340e+10
                               2011                              2.439068e+10
                               2012                              2.520121e+10
Venezuela, RB                  2008                              1.830507e+11
                               2009                              1.771889e+11
                               2010                              1.745509e+11
                               2011                              1.818409e+11
                               2012                              1.920712e+11

IndicatorName                        GDP at market prices (current US$)  \
CountryName                    Year
Antigua and Barbuda            2008                        1.347350e+09
                               2009                        1.206410e+09
                               2010                        1.135539e+09
                               2011                        1.129918e+09
                               2012                        1.204713e+09
Argentina                      2008                        4.037820e+11
                               2009                        3.766279e+11
                               2010                        4.616402e+11
                               2011                        5.578902e+11
                               2012                        6.043785e+11
Aruba                          2008                        2.791961e+09
                               2009                        2.498933e+09
                               2010                        2.467704e+09
                               2011                        2.584464e+09
Bahamas, The                   2008                        8.246650e+09
                               2009                        7.820420e+09
                               2010                        7.909580e+09
                               2011                        7.889750e+09
                               2012                        8.234470e+09
Barbados                       2008                        4.595000e+09
                               2009                        4.602000e+09
                               2010                        4.445500e+09
                               2011                        4.358000e+09
                               2012                        4.313000e+09
Belize                         2008                        1.368625e+09
                               2009                        1.336957e+09
                               2010                        1.397113e+09
                               2011                        1.487006e+09
                               2012                        1.573867e+09
Bolivia                        2008                        1.667432e+10
...                                                                 ...
St. Lucia                      2008                        1.194493e+09
                               2009                        1.186800e+09
                               2010                        1.249497e+09
                               2011                        1.290025e+09
                               2012                        1.311133e+09
St. Vincent and the Grenadines 2008                        6.954288e+08
                               2009                        6.749225e+08
                               2010                        6.812260e+08
                               2011                        6.761294e+08
                               2012                        6.929338e+08
Suriname                       2008                        3.532969e+09
                               2009                        3.875410e+09
                               2010                        4.368398e+09
                               2011                        4.422277e+09
                               2012                        4.980000e+09
Trinidad and Tobago            2008                        2.787023e+10
                               2009                        1.917516e+10
                               2010                        2.103757e+10
                               2011                        2.440984e+10
                               2012                        2.458084e+10
Uruguay                        2008                        3.036621e+10
                               2009                        3.166091e+10
                               2010                        4.028468e+10
                               2011                        4.796244e+10
                               2012                        5.138487e+10
Venezuela, RB                  2008                        3.156002e+11
                               2009                        3.294190e+11
                               2010                        3.938015e+11
                               2011                        3.164822e+11
                               2012                        3.812862e+11

IndicatorName                        GDP deflator (base year varies by country)  \
CountryName                    Year
Antigua and Barbuda            2008                                  108.320559
                               2009                                  110.260684
                               2010                                  111.766847
                               2011                                  113.244595
                               2012                                  116.075112
Argentina                      2008                                  181.891166
                               2009                                  199.871182
                               2010                                  234.270156
                               2011                                  275.964823
                               2012                                  327.477653
Aruba                          2008                                  151.756357
                               2009                                  143.968136
                               2010                                         NaN
                               2011                                         NaN
Bahamas, The                   2008                                  104.480301
                               2009                                  103.397319
                               2010                                  102.991334
                               2011                                  102.107308
                               2012                                  104.256892
Barbados                       2008                                  805.433830
                               2009                                  840.547945
                               2010                                  809.744991
                               2011                                  788.065099
                               2012                                  777.817854
Belize                         2008                                  116.314910
                               2009                                  112.818879
                               2010                                  114.102527
                               2011                                  118.941565
                               2012                                  121.251820
Bolivia                        2008                                  398.620971
...                                                                         ...
St. Lucia                      2008                                  107.457800
                               2009                                  107.252257
                               2010                                  114.890624
                               2011                                  117.790506
                               2012                                  120.995880
St. Vincent and the Grenadines 2008                                  108.431105
                               2009                                  107.490042
                               2010                                  112.272038
                               2011                                  111.906167
                               2012                                  113.125755
Suriname                       2008                                  115.521144
                               2009                                  123.011101
                               2010                                  131.878161
                               2011                                  150.966259
                               2012                                  166.555184
Trinidad and Tobago            2008                                  188.640888
                               2009                                  136.513136
                               2010                                  151.111437
                               2011                                  176.251901
                               2012                                  175.648492
Uruguay                        2008                                  125.918805
                               2009                                  135.674418
                               2010                                  142.331996
                               2011                                  155.155647
                               2012                                  169.177100
Venezuela, RB                  2008                                 1157.783478
                               2009                                 1248.457217
                               2010                                 1822.039270
                               2011                                 2334.928584
                               2012                                 2663.206235

IndicatorName                        GDP growth (annual %)  \
CountryName                    Year
Antigua and Barbuda            2008               0.071111
                               2009             -12.036015
                               2010              -7.142991
                               2011              -1.793436
                               2012               4.019542
Argentina                      2008               3.074946
                               2009               0.050024
                               2010               9.451578
                               2011               8.386451
                               2012               0.801760
Aruba                          2008              -6.881302
                               2009              -5.653502
                               2010                    NaN
                               2011                    NaN

In [91]:
df = datos_v2.sort_values(['CountryName', 'IndicatorName'], ascending=[1,1])
df.head()

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
12769,Antigua and Barbuda,ATG,GDP (constant LCU),NY.GDP.MKTP.KN,2012,2.802259e+09
13263,Antigua and Barbuda,ATG,GDP (constant LCU),NY.GDP.MKTP.KN,2013,2.792556e+09
13628,Antigua and Barbuda,ATG,GDP (constant LCU),NY.GDP.MKTP.KN,2014,2.927213e+09
12770,Antigua and Barbuda,ATG,GDP (current LCU),NY.GDP.MKTP.CN,2012,3.252725e+09
13264,Antigua and Barbuda,ATG,GDP (current LCU),NY.GDP.MKTP.CN,2013,3.241586e+09

In [114]:
pd.DataFrame.pivot_table(df, values='Value', index=['CountryName', 'Year'], columns=['IndicatorName'])

IndicatorName                        GDP (constant LCU)  GDP (current LCU)  \
CountryName                    Year
Antigua and Barbuda            2012        2.802259e+09       3.252725e+09
                               2013        2.792556e+09       3.241586e+09
                               2014        2.927213e+09       3.296635e+09
Argentina                      2012        8.445081e+11       2.765575e+12
                               2013        8.688752e+11       3.406265e+12
                               2014        8.728164e+11       4.425694e+12
Bahamas, The                   2012        7.898250e+09       8.234470e+09
                               2013        7.899990e+09       8.431750e+09
                               2014        7.980790e+09       8.510500e+09
Barbados                       2012        1.109000e+09       8.626000e+09
                               2013        1.109000e+09       8.562000e+09
                               2014        1.111000e+09       8.709000e+09
Belize                         2012        2.596031e+09       3.147735e+09
                               2013        2.635638e+09       3.248588e+09
                               2014        2.730081e+09       3.398308e+09
Bolivia                        2012        3.603746e+10       1.871539e+11
                               2013        3.848657e+10       2.118560e+11
                               2014        4.058816e+10       2.280037e+11
Brazil                         2012        1.819417e+12       4.713095e+12
                               2013        1.869337e+12       5.157569e+12
                               2014        1.872042e+12       5.521256e+12
Cayman Islands                 2012                 NaN       2.776938e+09
Chile                          2012        1.096276e+14       1.290276e+14
                               2013        1.142607e+14       1.370290e+14
                               2014        1.164248e+14       1.471849e+14
Colombia                       2012        4.708800e+14       6.642400e+14
                               2013        4.941240e+14       7.102570e+14
                               2014        5.166190e+14       7.561520e+14
Costa Rica                     2012        2.395294e+12       2.278177e+13
                               2013        2.477626e+12       2.460687e+13
...                                                 ...                ...
Paraguay                       2013        2.695513e+13       1.251522e+14
                               2014        2.822804e+13       1.377977e+14
Peru                           2012        4.312730e+11       5.083261e+11
                               2013        4.561590e+11       5.455524e+11
                               2014        4.668799e+11       5.752481e+11
Puerto Rico                    2012        9.548508e+09       1.010807e+11
                               2013        9.493381e+09       1.031348e+11
Sint Maarten (Dutch part)      2012                 NaN       1.764400e+09
                               2013                 NaN       1.825400e+09
St. Kitts and Nevis            2012        1.687515e+09       1.976184e+09
                               2013        1.785730e+09       2.125684e+09
                               2014        1.908858e+09       2.300948e+09
St. Lucia                      2012        2.925769e+09       3.540059e+09
                               2013        2.929823e+09       3.602842e+09
                               2014        2.943186e+09       3.791963e+09
St. Vincent and the Grenadines 2012        1.653842e+09       1.870921e+09
                               2013        1.681461e+09       1.945718e+09
                               2014        1.691507e+09       1.969135e+09
Suriname                       2012        9.867000e+09       1.643400e+10
                               2013        1.014700e+10       1.693200e+10
                               2014        1.033400e+10       1.719400e+10
Trinidad and Tobago            2012        8.997800e+10       1.580450e+11
                               2013        9.154300e+10       1.756090e+11
                               2014        9.229100e+10       1.850570e+11
Uruguay                        2012        6.168902e+11       1.043637e+12
                               2013        6.483539e+11       1.178197e+12
                               2014        6.710360e+11       1.335977e+12
Venezuela, RB                  2012        6.140910e+10       1.635451e+12
                               2013        6.223388e+10       2.245844e+12
                               2014        5.974453e+10                NaN

IndicatorName                        GDP at market prices (constant 2005 US$)  \
CountryName                    Year
Antigua and Barbuda            2012                              1.033890e+09
                               2013                              1.030310e+09
                               2014                              1.079992e+09
Argentina                      2012                              3.187041e+11
                               2013                              3.278999e+11
                               2014                              3.293872e+11
Bahamas, The                   2012                              7.833392e+09
                               2013                              7.835118e+09
                               2014                              7.915254e+09
Barbados                       2012                              4.089241e+09
                               2013                              4.089241e+09
                               2014                              4.096615e+09
Belize                         2012                              1.341614e+09
                               2013                              1.362082e+09
                               2014                              1.410890e+09
Bolivia                        2012                              1.322018e+10
                               2013                              1.411863e+10
                               2014                              1.488958e+10
Brazil                         2012                              1.172167e+12
                               2013                              1.204328e+12
                               2014                              1.206071e+12
Cayman Islands                 2012                                       NaN
Chile                          2012                              1.648063e+11
                               2013                              1.717714e+11
                               2014                              1.750248e+11
Colombia                       2012                              2.028926e+11
                               2013                              2.129079e+11
                               2014                              2.226006e+11
Costa Rica                     2012                              2.749930e+10
                               2013                              2.844452e+10
...                                                                       ...
Paraguay                       2013                              1.310064e+10
                               2014                              1.371930e+10
Peru                           2012                              1.179796e+11
                               2013                              1.247875e+11
                               2014                              1.277203e+11
Puerto Rico                    2012                              7.161608e+10
                               2013                              7.120261e+10
Sint Maarten (Dutch part)      2012                                       NaN
                               2013                                       NaN
St. Kitts and Nevis            2012                              5.651311e+08
                               2013                              5.980224e+08
                               2014                              6.392566e+08
St. Lucia                      2012                              1.033017e+09
                               2013                              1.034448e+09
                               2014                              1.039166e+09
St. Vincent and the Grenadines 2012                              5.946267e+08
                               2013                              6.045570e+08
                               2014                              6.081687e+08
Suriname                       2012                              2.396560e+09
                               2013                              2.464569e+09
                               2014                              2.509988e+09
Trinidad and Tobago            2012                              1.897519e+10
                               2013                              1.930523e+10
                               2014                              1.946298e+10
Uruguay                        2012                              2.520121e+10
                               2013                              2.648656e+10
                               2014                              2.741317e+10
Venezuela, RB                  2012                              1.920712e+11
                               2013                              1.946509e+11
                               2014                              1.868649e+11

IndicatorName                        GDP at market prices (current US$)  \
CountryName                    Year
Antigua and Barbuda            2012                        1.204713e+09
                               2013                        1.200588e+09
                               2014                        1.220976e+09
Argentina                      2012                        6.043785e+11
                               2013                        6.143835e+11
                               2014                        5.376600e+11
Bahamas, The                   2012                        8.234470e+09
                               2013                        8.431750e+09
                               2014                        8.510500e+09
Barbados                       2012                        4.313000e+09
                               2013                        4.281000e+09
                               2014                        4.354500e+09
Belize                         2012                        1.573867e+09
                               2013                        1.624294e+09
                               2014                        1.699154e+09
Bolivia                        2012                        2.708450e+10
                               2013                        3.065934e+10
                               2014                        3.299619e+10
Brazil                         2012                        2.413136e+12
                               2013                        2.392082e+12
                               2014                        2.346076e+12
Cayman Islands                 2012                                 NaN
Chile                          2012                        2.652316e+11
                               2013                        2.766737e+11
                               2014                        2.580615e+11
Colombia                       2012                        3.696597e+11
                               2013                        3.800635e+11
                               2014                        3.777396e+11
Costa Rica                     2012                        4.530067e+10
                               2013                        4.923671e+10
...                                                                 ...
Paraguay                       2013                        2.907893e+10
                               2014                        3.088086e+10
Peru                           2012                        1.926797e+11
                               2013                        2.018485e+11
                               2014                        2.025963e+11
Puerto Rico                    2012                        1.010807e+11
                               2013                        1.031348e+11
Sint Maarten (Dutch part)      2012                                 NaN
                               2013                                 NaN
St. Kitts and Nevis            2012                        7.319199e+08
                               2013                        7.872904e+08
                               2014                        8.522031e+08
St. Lucia                      2012                        1.311133e+09
                               2013                        1.334386e+09
                               2014                        1.404431e+09
St. Vincent and the Grenadines 2012                        6.929338e+08
                               2013                        7.206362e+08
                               2014                        7.293094e+08
Suriname                       2012                        4.980000e+09
                               2013                        5.130909e+09
                               2014                        5.210303e+09
Trinidad and Tobago            2012                        2.458084e+10
                               2013                        2.725747e+10
                               2014                        2.888266e+10
Uruguay                        2012                        5.138487e+10
                               2013                        5.752465e+10
                               2014                        5.747103e+10
Venezuela, RB                  2012                        3.812862e+11
                               2013                                 NaN
                               2014                                 NaN

IndicatorName                        GDP deflator (base year varies by country)  \
CountryName                    Year
Antigua and Barbuda            2012                                  116.075112
                               2013                                  116.079546
                               2014                                  112.620290
Argentina                      2012                                  327.477653
                               2013                                  392.031592
                               2014                                  507.059011
Bahamas, The                   2012                                  104.256892
                               2013                                  106.731148
                               2014                                  106.637313
Barbados                       2012                                  777.817854
                               2013                                  772.046889
                               2014                                  783.888389
Belize                         2012                                  121.251820
                               2013                                  123.256257
                               2014                                  124.476463
Bolivia                        2012                                  519.331490
                               2013                                  550.467428
                               2014                                  561.749243
Brazil                         2012                                  259.044203
                               2013                                  275.903712
                               2014                                  294.932328
Cayman Islands                 2012                                         NaN
Chile                          2012                                  117.696214
                               2013                                  119.926623
                               2014                                  126.420551
Colombia                       2012                                  141.063541
                               2013                                  143.740640
                               2014                                  146.365503
Costa Rica                     2012                                  951.105704
                               2013                                  993.163287
...                                                                         ...
Paraguay                       2013                                  464.298446
                               2014                                  488.158886
Peru                           2012                                  117.866443
                               2013                                  119.596987
                               2014                                  123.211153
Puerto Rico                    2012                                 1058.602382
                               2013                                 1086.386185
Sint Maarten (Dutch part)      2012                                         NaN
                               2013                                         NaN
St. Kitts and Nevis            2012                                  117.106174
                               2013                                  119.037269
                               2014                                  120.540601
St. Lucia                      2012                                  120.995880
                               2013                                  122.971299
                               2014                                  128.838708
St. Vincent and the Grenadines 2012                                  113.125755
                               2013                                  115.715883
                               2014                                  116.413111
Suriname                       2012                                  166.555184
                               2013                                  166.867054
                               2014                                  166.382814
Trinidad and Tobago            2012                                  175.648492
                               2013                                  191.832254
                               2014                                  200.514676
Uruguay                        2012                                  169.177100
                               2013                                  181.721280
                               2014                                  199.091759
Venezuela, RB                  2012                                 2663.206235
                               2013                                 3608.715680
                               2014                                         NaN

IndicatorName                        GDP growth (annual %)  \
CountryName                    Year
Antigua and Barbuda            2012               4.019542
                               2013              -0.346261
                               2014               4.821983
Argentina                      2012               0.801760
                               2013               2.885352
                               2014               0.453605
Bahamas, The                   2012               2.217313
                               2013               0.022030
                               2014               1.022786
Barbados                       2012               0.271248
                               2013               0.000000
                               2014               0.180343
Belize                         2012               3.824749
                               2013               1.525675

In [81]:
tuplas = []
for i in paises:
    for j in years:
         tuplas.append(tuple((i,j)))

In [101]:
arrays = [['Antigua and Barbuda','Argentina','Aruba','Bahamas, The'], [2012,2013,2014,2015]]

index = pd.MultiIndex.from_tuples(tuplas)

df_3 = pd.DataFrame(df.drop(['CountryName','CountryCode','IndicatorCode','Year'],1), index=index)
df_3.head()

                         IndicatorName  Value
Antigua and Barbuda 2012           NaN    NaN
                    2013           NaN    NaN
                    2014           NaN    NaN
                    2015           NaN    NaN
Argentina           2012           NaN    NaN

In [110]:
pivot_table(df, values='Value', index=['CountryName', 'Year'], columns=['IndicatorCode']) #, aggfunc=np.sum)

In [111]:
df.pivot(columns='IndicatorName', values='Value')

IndicatorName,GDP (constant LCU),GDP (current LCU),GDP at market prices (constant 2005 US$),GDP at market prices (current US$),GDP deflator (base year varies by country),GDP growth (annual %),GDP per capita (constant 2005 US$),GDP per capita (constant LCU),GDP per capita (current LCU),GDP per capita (current US$),GDP per capita growth (annual %),"GDP per capita, PPP (constant 2011 international $)","GDP per capita, PPP (current international $)","GDP, PPP (constant 2011 international $)"
12769,2.802259e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12770,NaN,3.252725e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12771,NaN,NaN,1.033890e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12772,NaN,NaN,NaN,1.204713e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12773,NaN,NaN,NaN,NaN,116.075112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12774,NaN,NaN,NaN,NaN,NaN,4.019542,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12775,NaN,NaN,NaN,NaN,NaN,NaN,11607.745344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31461.665675,NaN,NaN,NaN,NaN,NaN,NaN
12777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36519.163794,NaN,NaN,NaN,NaN,NaN
12778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13525.616220,NaN,NaN,NaN,NaN
12779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.948620,NaN,NaN,NaN
12780,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20577.292107,NaN,NaN
12781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20946.700835,NaN
12782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.832799e+09
13263,2.792556e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13264,NaN,3.241586e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13265,NaN,NaN,1.030310e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13266,NaN,NaN,NaN,1.200588e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13267,NaN,NaN,NaN,NaN,116.079546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13268,NaN,NaN,NaN,NaN,NaN,-0.346261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13269,NaN,NaN,NaN,NaN,NaN,NaN,11449.800650,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31033.571931,NaN,NaN,NaN,NaN,NaN,NaN
13271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36023.629494,NaN,NaN,NaN,NaN,NaN
13272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13342.084998,NaN,NaN,NaN,NaN
13273,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.360684,NaN,NaN,NaN
13274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20297.300255,NaN,NaN
13275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20969.552699,NaN
13276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.826453e+09
13628,2.927213e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13629,NaN,3.296635e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963585,NaN,NaN,NaN,NaN,2663.206235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
963586,NaN,NaN,NaN,NaN,NaN,5.625957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
963587,NaN,NaN,NaN,NaN,NaN,NaN,6433.632482,NaN,NaN,NaN,NaN,NaN,NaN,NaN
963588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2056.964341,NaN,NaN,NaN,NaN,NaN,NaN
963589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54781.202588,NaN,NaN,NaN,NaN,NaN
963590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12771.595036,NaN,NaN,NaN,NaN
963591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.116598,NaN,NaN,NaN
963592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17701.813601,NaN,NaN
963593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18019.601015,NaN
963597,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.284742e+11
964272,6.223388e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964273,NaN,2.245844e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964274,NaN,NaN,1.946509e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964275,NaN,NaN,NaN,NaN,3608.715680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964276,NaN,NaN,NaN,NaN,NaN,1.343094,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964277,NaN,NaN,NaN,NaN,NaN,NaN,6429.204742,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2055.548702,NaN,NaN,NaN,NaN,NaN,NaN
964279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74178.908309,NaN,NaN,NaN,NaN,NaN
964280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.068822,NaN,NaN,NaN
964281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17689.630899,NaN,NaN
964282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18275.516581,NaN
964284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.355721e+11
964743,5.974453e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964744,NaN,NaN,1.868649e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964745,NaN,NaN,NaN,NaN,NaN,-4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964746,NaN,NaN,NaN,NaN,NaN,NaN,6088.027290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
964747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1946.467268,NaN,NaN,NaN,NaN,NaN,NaN
964748,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.306682,NaN,NaN,NaN
964749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16750.898436,NaN,NaN
964751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.141492e+11

In [37]:
lista = np.array(indices_total[0]).flatten()

In [38]:
for i in indices_total:
    lista_indice = np.array(indices_total[i]).flatten()

TypeError: list indices must be integers, not list

In [39]:
temp = []

for i in indices_total:
    lista_indice = np.array(i).flatten()
    for j in lista_indice:
        temp.append(j)
        
datos_v2 = datos.reindex([temp])
temp

[12769,
 38118,
 64339,
 82199,
 110756,
 145899,
 181390,
 213111,
 249652,
 286220,
 308254,
 331199,
 364858,
 400667,
 435339,
 460499,
 494933,
 524016,
 548355,
 583084,
 615101,
 652115,
 685993,
 719995,
 751199,
 788050,
 802294,
 816401,
 839328,
 865478,
 883881,
 908052,
 936784,
 963581,
 13263,
 38837,
 64832,
 82599,
 111663,
 146820,
 182349,
 213868,
 250669,
 287194,
 308733,
 331885,
 365822,
 401637,
 436312,
 461183,
 495926,
 524795,
 549130,
 584086,
 615967,
 653076,
 686810,
 720892,
 752187,
 789034,
 802640,
 816839,
 840081,
 866210,
 884351,
 908474,
 937508,
 964272,
 13628,
 39416,
 65252,
 82949,
 112403,
 147631,
 183162,
 214489,
 251535,
 288028,
 332487,
 366624,
 402427,
 437127,
 461821,
 496765,
 549771,
 584877,
 616699,
 653886,
 687557,
 721606,
 752979,
 789815,
 817199,
 840725,
 866848,
 884780,
 908856,
 938090,
 964743,
 12770,
 38119,
 64340,
 82200,
 110757,
 145900,
 181391,
 187445,
 213112,
 249653,
 286221,
 308255,
 331200,
 364859,
 400668,
 435340,
 460500,
 494934,
 524017,
 548356,
 583085,
 615102,
 652116,
 685994,
 719996,
 751200,
 788051,
 802295,
 803603,
 816402,
 839329,
 865479,
 883882,
 908053,
 936785,
 963582,
 13264,
 38838,
 64833,
 82600,
 111664,
 146821,
 182350,
 213869,
 250670,
 287195,
 308734,
 331886,
 365823,
 401638,
 436313,
 461184,
 495927,
 524796,
 549131,
 584087,
 615968,
 653077,
 686811,
 720893,
 752188,
 789035,
 802641,
 803639,
 816840,
 840082,
 866211,
 884352,
 908475,
 937509,
 964273,
 13629,
 39417,
 65253,
 82950,
 112404,
 147632,
 183163,
 214490,
 251536,
 288029,
 332488,
 366625,
 402428,
 437128,
 461822,
 496766,
 525432,
 549772,
 584878,
 616700,
 653887,
 687558,
 721607,
 752980,
 789816,
 817200,
 840726,
 866849,
 884781,
 908857,
 938091,
 12772,
 38121,
 64342,
 82202,
 110759,
 145902,
 181393,
 213114,
 249655,
 286223,
 308257,
 331202,
 364861,
 400670,
 435342,
 460502,
 494936,
 524019,
 548358,
 583087,
 615104,
 652118,
 685996,
 719998,
 751202,
 788053,
 802297,
 816404,
 839331,
 865481,
 883884,
 908055,
 936787,
 963584,
 13266,
 38840,
 64835,
 82602,
 111666,
 146823,
 182352,
 213871,
 250672,
 287197,
 308736,
 331888,
 365825,
 401640,
 436315,
 461186,
 495929,
 524798,
 549133,
 584089,
 615970,
 653079,
 686813,
 720895,
 752190,
 789037,
 802643,
 816842,
 840084,
 866213,
 884354,
 908477,
 937511,
 13631,
 39419,
 65255,
 82952,
 112406,
 147634,
 183165,
 214492,
 251538,
 288031,
 332490,
 366627,
 402430,
 437130,
 461824,
 496768,
 525433,
 549774,
 584880,
 616702,
 653889,
 687560,
 721609,
 752982,
 789818,
 817202,
 840728,
 866851,
 884783,
 908859,
 938093,
 12771,
 38120,
 64341,
 82201,
 110758,
 145901,
 181392,
 213113,
 249654,
 286222,
 308256,
 331201,
 364860,
 400669,
 435341,
 460501,
 494935,
 524018,
 548357,
 583086,
 615103,
 652117,
 685995,
 719997,
 751201,
 788052,
 802296,
 816403,
 839330,
 865480,
 883883,
 908054,
 936786,
 963583,
 13265,
 38839,
 64834,
 82601,
 111665,
 146822,
 182351,
 213870,
 250671,
 287196,
 308735,
 331887,
 365824,
 401639,
 436314,
 461185,
 495928,
 524797,
 549132,
 584088,
 615969,
 653078,
 686812,
 720894,
 752189,
 789036,
 802642,
 816841,
 840083,
 866212,
 884353,
 908476,
 937510,
 964274,
 13630,
 39418,
 65254,
 82951,
 112405,
 147633,
 183164,
 214491,
 251537,
 288030,
 332489,
 366626,
 402429,
 437129,
 461823,
 496767,
 549773,
 584879,
 616701,
 653888,
 687559,
 721608,
 752981,
 789817,
 817201,
 840727,
 866850,
 884782,
 908858,
 938092,
 964744,
 12773,
 38122,
 64343,
 82203,
 110760,
 145903,
 181394,
 213115,
 249656,
 286224,
 308258,
 331203,
 364862,
 400671,
 435343,
 460503,
 494937,
 524020,
 548359,
 583088,
 615105,
 652119,
 685997,
 719999,
 751203,
 788054,
 802298,
 816405,
 839332,
 865482,
 883885,
 908056,
 936788,
 963585,
 13267,
 38841,
 64836,
 82603,
 111667,
 146824,
 182353,
 213872,
 250673,
 287198,
 308737,
 331889,
 365826,
 401641,
 436316,
 461187,
 495930,
 524799,
 549134,
 584090,
 615971,
 653080,
 686814,
 720896,
 752191,
 789038,
 802644,
 816843,
 840085,
 866214,
 884355,
 908478,
 937512,
 964275,
 13632,
 39420,
 65256,
 82953,
 112407,
 147635,
 183166,
 214493,
 251539,
 288032,
 332491,
 366628,
 402431,
 437131,
 461825,
 496769,
 549775,
 584881,
 616703,
 653890,
 687561,
 721610,
 752983,
 789819,
 817203,
 840729,
 866852,
 884784,
 908860,
 938094,
 12774,
 38123,
 64344,
 82204,
 110761,
 145904,
 181395,
 213116,
 249657,
 286225,
 308259,
 331204,
 364863,
 400672,
 435344,
 460504,
 494938,
 524021,
 548360,
 583089,
 615106,
 652120,
 685998,
 720000,
 751204,
 788055,
 802299,
 816406,
 839333,
 865483,
 883886,
 908057,
 936789,
 963586,
 13268,
 38842,
 64837,
 82604,
 111668,
 146825,
 182354,
 213873,
 250674,
 287199,
 308738,
 331890,
 365827,
 401642,
 436317,
 461188,
 495931,
 524800,
 549135,
 584091,
 615972,
 653081,
 686815,
 720897,
 752192,
 789039,
 802645,
 816844,
 840086,
 866215,
 884356,
 908479,
 937513,
 964276,
 13633,
 39421,
 65257,
 82954,
 112408,
 147636,
 183167,
 214494,
 251540,
 288033,
 332492,
 366629,
 402432,
 437132,
 461826,
 496770,
 549776,
 584882,
 616704,
 653891,
 687562,
 721611,
 752984,
 789820,
 817204,
 840730,
 866853,
 884785,
 908861,
 938095,
 964745,
 12775,
 38124,
 64345,
 82205,
 110762,
 145905,
 181396,
 213117,
 249658,
 286226,
 308260,
 331205,
 364864,
 400673,
 435345,
 460505,
 494939,
 524022,
 548361,
 583090,
 615107,
 652121,
 685999,
 720001,
 751205,
 788056,
 802300,
 816407,
 839334,
 865484,
 883887,
 908058,
 936790,
 963587,
 13269,
 38843,
 64838,
 82605,
 111669,
 146826,
 182355,
 213874,
 250675,
 287200,
 308739,
 331891,
 365828,
 401643,
 436318,
 461189,
 495932,
 524801,
 549136,
 584092,
 615973,
 653082,
 686816,
 720898,
 752193,
 789040,
 802646,
 816845,
 840087,
 866216,
 884357,
 908480,
 937514,
 964277,
 13634,
 39422,
 65258,
 82955,
 112409,
 147637,
 183168,
 214495,
 251541,
 288034,
 332493,
 366630,
 402433,
 437133,
 461827,
 496771,
 549777,
 584883,
 616705,
 653892,
 687563,
 721612,
 752985,
 789821,
 817205,
 840731,
 866854,
 884786,
 908862,
 938096,
 964746,
 12776,
 38125,
 64346,
 82206,
 110763,
 145906,
 181397,
 213118,
 249659,
 286227,
 308261,
 331206,
 364865,
 400674,
 435346,
 460506,
 494940,
 524023,
 548362,
 583091,
 615108,
 652122,
 686000,
 720002,
 751206,
 788057,
 802301,
 816408,
 839335,
 865485,
 883888,
 908059,
 936791,
 963588,
 13270,
 38844,
 64839,
 82606,
 111670,
 146827,
 182356,
 213875,
 250676,
 287201,
 308740,
 331892,
 365829,
 401644,
 436319,
 461190,
 495933,
 524802,
 549137,
 584093,
 615974,
 653083,
 686817,
 720899,
 752194,
 789041,
 802647,
 816846,
 840088,
 866217,
 884358,
 908481,
 937515,
 964278,
 13635,
 39423,
 65259,
 82956,
 112410,
 147638,
 183169,
 214496,
 251542,
 288035,
 332494,
 366631,
 402434,
 437134,
 461828,
 496772,
 549778,
 584884,
 616706,
 653893,
 687564,
 721613,
 752986,
 789822,
 817206,
 840732,
 866855,
 884787,
 908863,
 938097,
 964747,
 12777,
 38126,
 64347,
 82207,
 110764,
 145907,
 181398,
 187446,
 213119,
 249660,
 286228,
 308262,
 331207,
 364866,
 400675,
 435347,
 460507,
 494941,
 524024,
 548363,
 583092,
 615109,
 652123,
 686001,
 720003,
 751207,
 788058,
 802302,
 803604,
 816409,
 839336,
 865486,
 883889,
 908060,
 936792,
 963589,
 13271,
 38845,
 64840,
 82607,
 111671,
 146828,
 182357,
 213876,
 250677,
 287202,
 308741,
 331893,
 365830,
 401645,
 436320,
 461191,
 495934,
 524803,
 549138,
 584094,
 615975,
 653084,
 686818,
 720900,
 752195,
 789042,
 802648,
 803640,
 816847,
 840089,
 866218,
 884359,
 908482,
 937516,
 964279,
 13636,
 39424,
 65260,
 82957,
 112411,
 147639,
 183170,
 214497,
 251543,
 288036,
 332495,
 366632,
 402435,
 437135,
 461829,
 496773,
 525434,
 549779,
 584885,
 616707,
 653894,
 687565,
 721614,
 752987,
 789823,
 817207,
 840733,
 866856,
 884788,
 908864,
 938098,
 12778,
 38127,
 64348,
 82208,
 110765,
 145908,
 181399,
 213120,
 249661,
 286229,
 308263,
 331208,
 364867,
 400676,
 435348,
 460508,
 494942,
 524025,
 548364,
 583093,
 615110,
 652124,
 686002,
 720004,
 751208,
 788059,
 802303,
 816410,
 839337,
 865487,
 883890,
 908061,
 936793,
 963590,
 13272,
 38846,
 64841,
 82608,
 111672,
 146829,
 182358,
 213877,
 250678,
 287203,
 308742,
 331894,
 365831,
 401646,
 436321,
 461192,
 495935,
 524804,
 549139,
 584095,
 615976,
 653085,
 686819,
 720901,
 752196,
 789043,
 802649,
 816848,
 840090,
 866219,
 884360,
 908483,
 937517,
 13637,
 39425,
 65261,
 82958,
 112412,
 147640,
 183171,
 214498,
 251544,
 288037,
 332496,
 366633,
 402436,
 437136,
 461830,
 496774,
 525435,
 549780,
 584886,
 616708,
 653895,
 687566,
 721615,
 752988,
 789824,
 817208,
 840734,
 866857,
 884789,
 908865,
 938099,
 12779,
 38128,
 64349,
 82209,
 110766,
 145909,
 181400,
 ...]

In [40]:
datos_v2 = datos.reindex([temp])
#datos_colombia = datos_colombia.reset_index(drop=True)
datos_v2

,CountryName,CountryCode,IndicatorName,IndicatorCode,Year,Value
12769,Antigua and Barbuda,ATG,GDP (constant LCU),NY.GDP.MKTP.KN,2012,2.802259e+09
38118,Argentina,ARG,GDP (constant LCU),NY.GDP.MKTP.KN,2012,8.445081e+11
64339,"Bahamas, The",BHS,GDP (constant LCU),NY.GDP.MKTP.KN,2012,7.898250e+09
82199,Barbados,BRB,GDP (constant LCU),NY.GDP.MKTP.KN,2012,1.109000e+09
110756,Belize,BLZ,GDP (constant LCU),NY.GDP.MKTP.KN,2012,2.596031e+09
145899,Bolivia,BOL,GDP (constant LCU),NY.GDP.MKTP.KN,2012,3.603746e+10
181390,Brazil,BRA,GDP (constant LCU),NY.GDP.MKTP.KN,2012,1.819417e+12
213111,Chile,CHL,GDP (constant LCU),NY.GDP.MKTP.KN,2012,1.096276e+14
249652,Colombia,COL,GDP (constant LCU),NY.GDP.MKTP.KN,2012,4.708800e+14
286220,Costa Rica,CRI,GDP (constant LCU),NY.GDP.MKTP.KN,2012,2.395294e+12
308254,Cuba,CUB,GDP (constant LCU),NY.GDP.MKTP.KN,2012,5.870874e+10
331199,Dominica,DMA,GDP (constant LCU),NY.GDP.MKTP.KN,2012,1.179000e+09
364858,Dominican Republic,DOM,GDP (constant LCU),NY.GDP.MKTP.KN,2012,1.731479e+12
400667,Ecuador,ECU,GDP (constant LCU),NY.GDP.MKTP.KN,2012,6.436243e+10
435339,El Salvador,SLV,GDP (constant LCU),NY.GDP.MKTP.KN,2012,9.451700e+09
460499,Grenada,GRD,GDP (constant LCU),NY.GDP.MKTP.KN,2012,1.870186e+09
494933,Guatemala,GTM,GDP (constant LCU),NY.GDP.MKTP.KN,2012,2.139466e+11
524016,Guyana,GUY,GDP (constant LCU),NY.GDP.MKTP.KN,2012,3.797320e+11
548355,Haiti,HTI,GDP (constant LCU),NY.GDP.MKTP.KN,2012,1.440700e+10
583084,Honduras,HND,GDP (constant LCU),NY.GDP.MKTP.KN,2012,1.728102e+11
615101,Jamaica,JAM,GDP (constant LCU),NY.GDP.MKTP.KN,2012,8.369980e+11
652115,Mexico,MEX,GDP (constant LCU),NY.GDP.MKTP.KN,2012,1.327940e+13
685993,Nicaragua,NIC,GDP (constant LCU),NY.GDP.MKTP.KN,2012,1.447016e+11
719995,Panama,PAN,GDP (constant LCU),NY.GDP.MKTP.KN,2012,3.098550e+10
751199,Paraguay,PRY,GDP (constant LCU),NY.GDP.MKTP.KN,2012,2.363733e+13
788050,Peru,PER,GDP (constant LCU),NY.GDP.MKTP.KN,2012,4.312730e+11
802294,Puerto Rico,PRI,GDP (constant LCU),NY.GDP.MKTP.KN,2012,9.548508e+09
816401,St. Kitts and Nevis,KNA,GDP (constant LCU),NY.GDP.MKTP.KN,2012,1.687515e+09
839328,St. Lucia,LCA,GDP (constant LCU),NY.GDP.MKTP.KN,2012,2.925769e+09
865478,St. Vincent and the Grenadines,VCT,GDP (constant LCU),NY.GDP.MKTP.KN,2012,1.653842e+09
...,...,...,...,...,...,...
13641,Antigua and Barbuda,ATG,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,1.914524e+09
65265,"Bahamas, The",BHS,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,8.584645e+09
82963,Barbados,BRB,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,4.341243e+09
112416,Belize,BLZ,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,2.824141e+09
147645,Bolivia,BOL,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,6.680383e+10
183176,Brazil,BRA,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,3.113801e+12
214503,Chile,CHL,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,3.904198e+11
251549,Colombia,COL,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,6.090065e+11
288042,Costa Rica,CRI,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,6.771108e+10
332500,Dominica,DMA,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,7.506981e+08
366638,Dominican Republic,DOM,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,1.316614e+11
402441,Ecuador,ECU,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,1.725278e+11
437140,El Salvador,SLV,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,4.866101e+10
461834,Grenada,GRD,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,1.260631e+09
496779,Guatemala,GTM,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,1.138950e+11
549784,Haiti,HTI,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,1.746683e+10
584890,Honduras,HND,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,3.728447e+10
616713,Jamaica,JAM,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,2.304189e+10
653900,Mexico,MEX,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,2.041802e+12
687570,Nicaragua,NIC,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,2.821812e+10
721619,Panama,PAN,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,7.709555e+10
752992,Paraguay,PRY,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,5.570708e+10
789829,Peru,PER,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,3.542617e+11
817212,St. Kitts and Nevis,KNA,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,1.218163e+09
840739,St. Lucia,LCA,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,1.880444e+09
866861,St. Vincent and the Grenadines,VCT,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,1.119198e+09
884793,Suriname,SUR,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,8.543403e+09
908870,Trinidad and Tobago,TTO,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,4.130826e+10
938104,Uruguay,URY,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,6.813061e+10
964751,"Venezuela, RB",VEN,"GDP, PPP (constant 2011 international $)",NY.GDP.MKTP.PP.KD,2014,5.141492e+11

In [ ]:
datos_v2

In [42]:
#Creamos una lista temporal que contiene todos los valores de los indicadores en 0          
temporal = list()

for i in paises:
    for j in indicators:
        for k in years:
            temporal.append([i,k,j,0.])

pd.DataFrame(temporal)

                          0     1                  2    3
0       Antigua and Barbuda  2012     NY.GDP.MKTP.KN  0.0
1       Antigua and Barbuda  2013     NY.GDP.MKTP.KN  0.0
2       Antigua and Barbuda  2014     NY.GDP.MKTP.KN  0.0
3       Antigua and Barbuda  2015     NY.GDP.MKTP.KN  0.0
4       Antigua and Barbuda  2012     NY.GDP.MKTP.CN  0.0
5       Antigua and Barbuda  2013     NY.GDP.MKTP.CN  0.0
6       Antigua and Barbuda  2014     NY.GDP.MKTP.CN  0.0
7       Antigua and Barbuda  2015     NY.GDP.MKTP.CN  0.0
8       Antigua and Barbuda  2012     NY.GDP.MKTP.CD  0.0
9       Antigua and Barbuda  2013     NY.GDP.MKTP.CD  0.0
10      Antigua and Barbuda  2014     NY.GDP.MKTP.CD  0.0
11      Antigua and Barbuda  2015     NY.GDP.MKTP.CD  0.0
12      Antigua and Barbuda  2012     NY.GDP.MKTP.KD  0.0
13      Antigua and Barbuda  2013     NY.GDP.MKTP.KD  0.0
14      Antigua and Barbuda  2014     NY.GDP.MKTP.KD  0.0
15      Antigua and Barbuda  2015     NY.GDP.MKTP.KD  0.0
16      Antigua and Barbuda  2012     NY.GDP.DEFL.ZS  0.0
17      Antigua and Barbuda  2013     NY.GDP.DEFL.ZS  0.0
18      Antigua and Barbuda  2014     NY.GDP.DEFL.ZS  0.0
19      Antigua and Barbuda  2015     NY.GDP.DEFL.ZS  0.0
20      Antigua and Barbuda  2012  NY.GDP.MKTP.KD.ZG  0.0
21      Antigua and Barbuda  2013  NY.GDP.MKTP.KD.ZG  0.0
22      Antigua and Barbuda  2014  NY.GDP.MKTP.KD.ZG  0.0
23      Antigua and Barbuda  2015  NY.GDP.MKTP.KD.ZG  0.0
24      Antigua and Barbuda  2012     NY.GDP.PCAP.KD  0.0
25      Antigua and Barbuda  2013     NY.GDP.PCAP.KD  0.0
26      Antigua and Barbuda  2014     NY.GDP.PCAP.KD  0.0
27      Antigua and Barbuda  2015     NY.GDP.PCAP.KD  0.0
28      Antigua and Barbuda  2012     NY.GDP.PCAP.KN  0.0
29      Antigua and Barbuda  2013     NY.GDP.PCAP.KN  0.0
...                     ...   ...                ...  ...
2266  Virgin Islands (U.S.)  2014     NY.GDP.PCAP.KD  0.0
2267  Virgin Islands (U.S.)  2015     NY.GDP.PCAP.KD  0.0
2268  Virgin Islands (U.S.)  2012     NY.GDP.PCAP.KN  0.0
2269  Virgin Islands (U.S.)  2013     NY.GDP.PCAP.KN  0.0
2270  Virgin Islands (U.S.)  2014     NY.GDP.PCAP.KN  0.0
2271  Virgin Islands (U.S.)  2015     NY.GDP.PCAP.KN  0.0
2272  Virgin Islands (U.S.)  2012     NY.GDP.PCAP.CN  0.0
2273  Virgin Islands (U.S.)  2013     NY.GDP.PCAP.CN  0.0
2274  Virgin Islands (U.S.)  2014     NY.GDP.PCAP.CN  0.0
2275  Virgin Islands (U.S.)  2015     NY.GDP.PCAP.CN  0.0
2276  Virgin Islands (U.S.)  2012     NY.GDP.PCAP.CD  0.0
2277  Virgin Islands (U.S.)  2013     NY.GDP.PCAP.CD  0.0
2278  Virgin Islands (U.S.)  2014     NY.GDP.PCAP.CD  0.0
2279  Virgin Islands (U.S.)  2015     NY.GDP.PCAP.CD  0.0
2280  Virgin Islands (U.S.)  2012  NY.GDP.PCAP.KD.ZG  0.0
2281  Virgin Islands (U.S.)  2013  NY.GDP.PCAP.KD.ZG  0.0
2282  Virgin Islands (U.S.)  2014  NY.GDP.PCAP.KD.ZG  0.0
2283  Virgin Islands (U.S.)  2015  NY.GDP.PCAP.KD.ZG  0.0
2284  Virgin Islands (U.S.)  2012  NY.GDP.PCAP.PP.KD  0.0
2285  Virgin Islands (U.S.)  2013  NY.GDP.PCAP.PP.KD  0.0
2286  Virgin Islands (U.S.)  2014  NY.GDP.PCAP.PP.KD  0.0
2287  Virgin Islands (U.S.)  2015  NY.GDP.PCAP.PP.KD  0.0
2288  Virgin Islands (U.S.)  2012  NY.GDP.PCAP.PP.CD  0.0
2289  Virgin Islands (U.S.)  2013  NY.GDP.PCAP.PP.CD  0.0
2290  Virgin Islands (U.S.)  2014  NY.GDP.PCAP.PP.CD  0.0
2291  Virgin Islands (U.S.)  2015  NY.GDP.PCAP.PP.CD  0.0
2292  Virgin Islands (U.S.)  2012  NY.GDP.MKTP.PP.KD  0.0
2293  Virgin Islands (U.S.)  2013  NY.GDP.MKTP.PP.KD  0.0
2294  Virgin Islands (U.S.)  2014  NY.GDP.MKTP.PP.KD  0.0
2295  Virgin Islands (U.S.)  2015  NY.GDP.MKTP.PP.KD  0.0

[2296 rows x 4 columns]

In [28]:
indices_total

[[array([ 12769,  38118,  64339,  82199, 110756, 145899, 181390, 213111,
         249652, 286220, 308254, 331199, 364858, 400667, 435339, 460499,
         494933, 524016, 548355, 583084, 615101, 652115, 685993, 719995,
         751199, 788050, 802294, 816401, 839328, 865478, 883881, 908052,
         936784, 963581], dtype=int64)],
 [array([ 13263,  38837,  64832,  82599, 111663, 146820, 182349, 213868,
         250669, 287194, 308733, 331885, 365822, 401637, 436312, 461183,
         495926, 524795, 549130, 584086, 615967, 653076, 686810, 720892,
         752187, 789034, 802640, 816839, 840081, 866210, 884351, 908474,
         937508, 964272], dtype=int64)],
 [array([ 13628,  39416,  65252,  82949, 112403, 147631, 183162, 214489,
         251535, 288028, 332487, 366624, 402427, 437127, 461821, 496765,
         549771, 584877, 616699, 653886, 687557, 721606, 752979, 789815,
         817199, 840725, 866848, 884780, 908856, 938090, 964743], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12770,  38119,  64340,  82200, 110757, 145900, 181391, 187445,
         213112, 249653, 286221, 308255, 331200, 364859, 400668, 435340,
         460500, 494934, 524017, 548356, 583085, 615102, 652116, 685994,
         719996, 751200, 788051, 802295, 803603, 816402, 839329, 865479,
         883882, 908053, 936785, 963582], dtype=int64)],
 [array([ 13264,  38838,  64833,  82600, 111664, 146821, 182350, 213869,
         250670, 287195, 308734, 331886, 365823, 401638, 436313, 461184,
         495927, 524796, 549131, 584087, 615968, 653077, 686811, 720893,
         752188, 789035, 802641, 803639, 816840, 840082, 866211, 884352,
         908475, 937509, 964273], dtype=int64)],
 [array([ 13629,  39417,  65253,  82950, 112404, 147632, 183163, 214490,
         251536, 288029, 332488, 366625, 402428, 437128, 461822, 496766,
         525432, 549772, 584878, 616700, 653887, 687558, 721607, 752980,
         789816, 817200, 840726, 866849, 884781, 908857, 938091], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12772,  38121,  64342,  82202, 110759, 145902, 181393, 213114,
         249655, 286223, 308257, 331202, 364861, 400670, 435342, 460502,
         494936, 524019, 548358, 583087, 615104, 652118, 685996, 719998,
         751202, 788053, 802297, 816404, 839331, 865481, 883884, 908055,
         936787, 963584], dtype=int64)],
 [array([ 13266,  38840,  64835,  82602, 111666, 146823, 182352, 213871,
         250672, 287197, 308736, 331888, 365825, 401640, 436315, 461186,
         495929, 524798, 549133, 584089, 615970, 653079, 686813, 720895,
         752190, 789037, 802643, 816842, 840084, 866213, 884354, 908477,
         937511], dtype=int64)],
 [array([ 13631,  39419,  65255,  82952, 112406, 147634, 183165, 214492,
         251538, 288031, 332490, 366627, 402430, 437130, 461824, 496768,
         525433, 549774, 584880, 616702, 653889, 687560, 721609, 752982,
         789818, 817202, 840728, 866851, 884783, 908859, 938093], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12771,  38120,  64341,  82201, 110758, 145901, 181392, 213113,
         249654, 286222, 308256, 331201, 364860, 400669, 435341, 460501,
         494935, 524018, 548357, 583086, 615103, 652117, 685995, 719997,
         751201, 788052, 802296, 816403, 839330, 865480, 883883, 908054,
         936786, 963583], dtype=int64)],
 [array([ 13265,  38839,  64834,  82601, 111665, 146822, 182351, 213870,
         250671, 287196, 308735, 331887, 365824, 401639, 436314, 461185,
         495928, 524797, 549132, 584088, 615969, 653078, 686812, 720894,
         752189, 789036, 802642, 816841, 840083, 866212, 884353, 908476,
         937510, 964274], dtype=int64)],
 [array([ 13630,  39418,  65254,  82951, 112405, 147633, 183164, 214491,
         251537, 288030, 332489, 366626, 402429, 437129, 461823, 496767,
         549773, 584879, 616701, 653888, 687559, 721608, 752981, 789817,
         817201, 840727, 866850, 884782, 908858, 938092, 964744], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12773,  38122,  64343,  82203, 110760, 145903, 181394, 213115,
         249656, 286224, 308258, 331203, 364862, 400671, 435343, 460503,
         494937, 524020, 548359, 583088, 615105, 652119, 685997, 719999,
         751203, 788054, 802298, 816405, 839332, 865482, 883885, 908056,
         936788, 963585], dtype=int64)],
 [array([ 13267,  38841,  64836,  82603, 111667, 146824, 182353, 213872,
         250673, 287198, 308737, 331889, 365826, 401641, 436316, 461187,
         495930, 524799, 549134, 584090, 615971, 653080, 686814, 720896,
         752191, 789038, 802644, 816843, 840085, 866214, 884355, 908478,
         937512, 964275], dtype=int64)],
 [array([ 13632,  39420,  65256,  82953, 112407, 147635, 183166, 214493,
         251539, 288032, 332491, 366628, 402431, 437131, 461825, 496769,
         549775, 584881, 616703, 653890, 687561, 721610, 752983, 789819,
         817203, 840729, 866852, 884784, 908860, 938094], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12774,  38123,  64344,  82204, 110761, 145904, 181395, 213116,
         249657, 286225, 308259, 331204, 364863, 400672, 435344, 460504,
         494938, 524021, 548360, 583089, 615106, 652120, 685998, 720000,
         751204, 788055, 802299, 816406, 839333, 865483, 883886, 908057,
         936789, 963586], dtype=int64)],
 [array([ 13268,  38842,  64837,  82604, 111668, 146825, 182354, 213873,
         250674, 287199, 308738, 331890, 365827, 401642, 436317, 461188,
         495931, 524800, 549135, 584091, 615972, 653081, 686815, 720897,
         752192, 789039, 802645, 816844, 840086, 866215, 884356, 908479,
         937513, 964276], dtype=int64)],
 [array([ 13633,  39421,  65257,  82954, 112408, 147636, 183167, 214494,
         251540, 288033, 332492, 366629, 402432, 437132, 461826, 496770,
         549776, 584882, 616704, 653891, 687562, 721611, 752984, 789820,
         817204, 840730, 866853, 884785, 908861, 938095, 964745], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12775,  38124,  64345,  82205, 110762, 145905, 181396, 213117,
         249658, 286226, 308260, 331205, 364864, 400673, 435345, 460505,
         494939, 524022, 548361, 583090, 615107, 652121, 685999, 720001,
         751205, 788056, 802300, 816407, 839334, 865484, 883887, 908058,
         936790, 963587], dtype=int64)],
 [array([ 13269,  38843,  64838,  82605, 111669, 146826, 182355, 213874,
         250675, 287200, 308739, 331891, 365828, 401643, 436318, 461189,
         495932, 524801, 549136, 584092, 615973, 653082, 686816, 720898,
         752193, 789040, 802646, 816845, 840087, 866216, 884357, 908480,
         937514, 964277], dtype=int64)],
 [array([ 13634,  39422,  65258,  82955, 112409, 147637, 183168, 214495,
         251541, 288034, 332493, 366630, 402433, 437133, 461827, 496771,
         549777, 584883, 616705, 653892, 687563, 721612, 752985, 789821,
         817205, 840731, 866854, 884786, 908862, 938096, 964746], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12776,  38125,  64346,  82206, 110763, 145906, 181397, 213118,
         249659, 286227, 308261, 331206, 364865, 400674, 435346, 460506,
         494940, 524023, 548362, 583091, 615108, 652122, 686000, 720002,
         751206, 788057, 802301, 816408, 839335, 865485, 883888, 908059,
         936791, 963588], dtype=int64)],
 [array([ 13270,  38844,  64839,  82606, 111670, 146827, 182356, 213875,
         250676, 287201, 308740, 331892, 365829, 401644, 436319, 461190,
         495933, 524802, 549137, 584093, 615974, 653083, 686817, 720899,
         752194, 789041, 802647, 816846, 840088, 866217, 884358, 908481,
         937515, 964278], dtype=int64)],
 [array([ 13635,  39423,  65259,  82956, 112410, 147638, 183169, 214496,
         251542, 288035, 332494, 366631, 402434, 437134, 461828, 496772,
         549778, 584884, 616706, 653893, 687564, 721613, 752986, 789822,
         817206, 840732, 866855, 884787, 908863, 938097, 964747], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12777,  38126,  64347,  82207, 110764, 145907, 181398, 187446,
         213119, 249660, 286228, 308262, 331207, 364866, 400675, 435347,
         460507, 494941, 524024, 548363, 583092, 615109, 652123, 686001,
         720003, 751207, 788058, 802302, 803604, 816409, 839336, 865486,
         883889, 908060, 936792, 963589], dtype=int64)],
 [array([ 13271,  38845,  64840,  82607, 111671, 146828, 182357, 213876,
         250677, 287202, 308741, 331893, 365830, 401645, 436320, 461191,
         495934, 524803, 549138, 584094, 615975, 653084, 686818, 720900,
         752195, 789042, 802648, 803640, 816847, 840089, 866218, 884359,
         908482, 937516, 964279], dtype=int64)],
 [array([ 13636,  39424,  65260,  82957, 112411, 147639, 183170, 214497,
         251543, 288036, 332495, 366632, 402435, 437135, 461829, 496773,
         525434, 549779, 584885, 616707, 653894, 687565, 721614, 752987,
         789823, 817207, 840733, 866856, 884788, 908864, 938098], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12778,  38127,  64348,  82208, 110765, 145908, 181399, 213120,
         249661, 286229, 308263, 331208, 364867, 400676, 435348, 460508,
         494942, 524025, 548364, 583093, 615110, 652124, 686002, 720004,
         751208, 788059, 802303, 816410, 839337, 865487, 883890, 908061,
         936793, 963590], dtype=int64)],
 [array([ 13272,  38846,  64841,  82608, 111672, 146829, 182358, 213877,
         250678, 287203, 308742, 331894, 365831, 401646, 436321, 461192,
         495935, 524804, 549139, 584095, 615976, 653085, 686819, 720901,
         752196, 789043, 802649, 816848, 840090, 866219, 884360, 908483,
         937517], dtype=int64)],
 [array([ 13637,  39425,  65261,  82958, 112412, 147640, 183171, 214498,
         251544, 288037, 332496, 366633, 402436, 437136, 461830, 496774,
         525435, 549780, 584886, 616708, 653895, 687566, 721615, 752988,
         789824, 817208, 840734, 866857, 884789, 908865, 938099], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12779,  38128,  64349,  82209, 110766, 145909, 181400, 213121,
         249662, 286230, 308264, 331209, 364868, 400677, 435349, 460509,
         494943, 524026, 548365, 583094, 615111, 652125, 686003, 720005,
         751209, 788060, 802304, 816411, 839338, 865488, 883891, 908062,
         936794, 963591], dtype=int64)],
 [array([ 13273,  38847,  64842,  82609, 111673, 146830, 182359, 213878,
         250679, 287204, 308743, 331895, 365832, 401647, 436322, 461193,
         495936, 524805, 549140, 584096, 615977, 653086, 686820, 720902,
         752197, 789044, 802650, 816849, 840091, 866220, 884361, 908484,
         937518, 964280], dtype=int64)],
 [array([ 13638,  39426,  65262,  82959, 112413, 147641, 183172, 214499,
         251545, 288038, 332497, 366634, 402437, 437137, 461831, 496775,
         549781, 584887, 616709, 653896, 687567, 721616, 752989, 789825,
         817209, 840735, 866858, 884790, 908866, 938100, 964748], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12780,  64350,  82210, 110767, 145910, 181401, 213122, 249663,
         286231, 308265, 331210, 364869, 400678, 435350, 460510, 494944,
         524027, 548366, 583095, 615112, 652126, 686004, 720006, 751210,
         788061, 802305, 816412, 839339, 865489, 883892, 908063, 936795,
         963592], dtype=int64)],
 [array([ 13274,  64843,  82610, 111674, 146831, 182360, 213879, 250680,
         287205, 308744, 331896, 365833, 401648, 436323, 461194, 495937,
         524806, 549141, 584097, 615978, 653087, 686821, 720903, 752198,
         789045, 802651, 816850, 840092, 866221, 884362, 908485, 937519,
         964281], dtype=int64)],
 [array([ 13639,  65263,  82960, 112414, 147642, 183173, 214500, 251546,
         288039, 332498, 366635, 402438, 437138, 461832, 496776, 549782,
         584888, 616710, 653897, 687568, 721617, 752990, 789826, 817210,
         840736, 866859, 884791, 908867, 938101, 964749], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12781,  64351,  82211, 110768, 145911, 181402, 213123, 249664,
         286232, 308266, 331211, 364870, 400679, 435351, 460511, 494945,
         524028, 548367, 583096, 615113, 652127, 686005, 720007, 751211,
         788062, 802306, 816413, 839340, 865490, 883893, 908064, 936796,
         963593], dtype=int64)],
 [array([ 13275,  64844,  82611, 111675, 146832, 182361, 213880, 250681,
         287206, 308745, 331897, 365834, 401649, 436324, 461195, 495938,
         524807, 549142, 584098, 615979, 653088, 686822, 720904, 752199,
         789046, 802652, 816851, 840093, 866222, 884363, 908486, 937520,
         964282], dtype=int64)],
 [array([ 13640,  65264,  82961, 112415, 147643, 183174, 214501, 251547,
         288040, 332499, 366636, 402439, 437139, 461833, 496777, 549783,
         584889, 616711, 653898, 687569, 721618, 752991, 789827, 817211,
         840737, 866860, 884792, 908868, 938102], dtype=int64)],
 [array([], dtype=int64)],
 [array([ 12782,  64352,  82213, 110769, 145915, 181406, 213127, 249668,
         286236, 308269, 331212, 364874, 400683, 435354, 460512, 494949,
         524029, 548370, 583099, 615117, 652131, 686008, 720010, 751214,
         788066, 802307, 816414, 839342, 865491, 883894, 908068, 936800,
         963597], dtype=int64)],
 [array([ 13276,  64845,  82613, 111676, 146834, 182363, 213884, 250683,
         287208, 308746, 331898, 365836, 401651, 436325, 461196, 495940,
         524808, 549143, 584099, 615981, 653092, 686823, 720905, 752200,
         789048, 802653, 816852, 840095, 866223, 884364, 908488, 937522,
         964284], dtype=int64)],
 [array([ 13641,  65265,  82963, 112416, 147645, 183176, 214503, 251549,
         288042, 332500, 366638, 402441, 437140, 461834, 496779, 549784,
         584890, 616713, 653900, 687570, 721619, 752992, 789829, 817212,
         840739, 866861, 884793, 908870, 938104, 964751], dtype=int64)],
 [array([], dtype=int64)]]

In [21]:
#The list of lists
list_of_lists = lista
flattened_list = []

#flatten the lis
for x in list_of_lists:
    for y in x:
        flattened_list.append(y)
        
flattened_list

TypeError: 'numpy.int64' object is not iterable

In [38]:
start_time = time.time()

cn = datos['CountryName']
y = datos['Year']
indicator = datos['IndicatorCode']
years = np.array([2012,2013,2014,2015])
paises = np.array(['Antigua and Barbuda','Argentina','Aruba','Bahamas, The','Barbados','Belize','Bolivia','Brazil','Cayman Islands','Chile','Colombia','Costa Rica','Cuba','Curacao','Dominica','Dominican Republic','Ecuador','El Salvador','Grenada','Guatemala','Guyana','Haiti','Honduras','Jamaica','Mexico','Nicaragua','Panama','Paraguay','Peru','Puerto Rico','Sint Maarten (Dutch part)','St. Kitts and Nevis','St. Lucia','St. Martin (French part)','St. Vincent and the Grenadines','Suriname','Trinidad and Tobago','Turks and Caicos Islands','Uruguay','Venezuela, RB','Virgin Islands (U.S.)'])
indicators = np.array(['NY.GDP.MKTP.KN','NY.GDP.MKTP.CN','NY.GDP.MKTP.CD','NY.GDP.MKTP.KD','NY.GDP.DEFL.ZS','NY.GDP.MKTP.KD.ZG','NY.GDP.PCAP.KD','NY.GDP.PCAP.KN','NY.GDP.PCAP.CN','NY.GDP.PCAP.CD','NY.GDP.PCAP.KD.ZG','NY.GDP.PCAP.PP.KD','NY.GDP.PCAP.PP.CD','NY.GDP.MKTP.PP.KD'])

for i in paises:
    for j in indicators:
        for k in years:
            print datos['Value'][numpy.flatnonzero((cn == i) & (indicator == j) & (y == k))]
    
print("--- %s seconds ---" % (time.time() - start_time))

12769    2.802259e+09
Name: Value, dtype: float64
13263    2.792556e+09
Name: Value, dtype: float64
13628    2.927213e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12770    3.252725e+09
Name: Value, dtype: float64
13264    3.241586e+09
Name: Value, dtype: float64
13629    3.296635e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12772    1.204713e+09
Name: Value, dtype: float64
13266    1.200588e+09
Name: Value, dtype: float64
13631    1.220976e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12771    1.033890e+09
Name: Value, dtype: float64
13265    1.030310e+09
Name: Value, dtype: float64
13630    1.079992e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12773    116.075112
Name: Value, dtype: float64
13267    116.079546
Name: Value, dtype: float64
13632    112.62029
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12774    4.019542
Name: Value, dtype: float64
13268   -0.346261
Name: Value, dtype: float64
13633    4.821983
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12775    11607.745344
Name: Value, dtype: float64
13269    11449.80065
Name: Value, dtype: float64
13634    11881.096762
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12776    31461.665675
Name: Value, dtype: float64
13270    31033.571931
Name: Value, dtype: float64
13635    32202.558129
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12777    36519.163794
Name: Value, dtype: float64
13271    36023.629494
Name: Value, dtype: float64
13636    36266.614191
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12778    13525.61622
Name: Value, dtype: float64
13272    13342.084998
Name: Value, dtype: float64
13637    13432.07933
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12779    2.94862
Name: Value, dtype: float64
13273   -1.360684
Name: Value, dtype: float64
13638    3.766844
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12780    20577.292107
Name: Value, dtype: float64
13274    20297.300255
Name: Value, dtype: float64
13639    21061.867863
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12781    20946.700835
Name: Value, dtype: float64
13275    20969.552699
Name: Value, dtype: float64
13640    22076.918137
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
12782    1.832799e+09
Name: Value, dtype: float64
13276    1.826453e+09
Name: Value, dtype: float64
13641    1.914524e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
38118    8.445081e+11
Name: Value, dtype: float64
38837    8.688752e+11
Name: Value, dtype: float64
39416    8.728164e+11
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
38119    2.765575e+12
Name: Value, dtype: float64
38838    3.406265e+12
Name: Value, dtype: float64
39417    4.425694e+12
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
38121    6.043785e+11
Name: Value, dtype: float64
38840    6.143835e+11
Name: Value, dtype: float64
39419    5.376600e+11
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
38120    3.187041e+11
Name: Value, dtype: float64
38839    3.278999e+11
Name: Value, dtype: float64
39418    3.293872e+11
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
38122    327.477653
Name: Value, dtype: float64
38841    392.031592
Name: Value, dtype: float64
39420    507.059011
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
38123    0.80176
Name: Value, dtype: float64
38842    2.885352
Name: Value, dtype: float64
39421    0.453605
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
38124    7571.028495
Name: Value, dtype: float64
38843    7708.343904
Name: Value, dtype: float64
39422    7663.728453
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
38125    20061.851245
Name: Value, dtype: float64
38844    20425.712154
Name: Value, dtype: float64
39423    20307.489304
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
38126    65698.079692
Name: Value, dtype: float64
38845    80075.244584
Name: Value, dtype: float64
39424    102970.954445
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
38127    14357.411589
Name: Value, dtype: float64
38846    14443.065651
Name: Value, dtype: float64
39425    12509.531118
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
38128   -0.250931
Name: Value, dtype: float64
38847    1.813696
Name: Value, dtype: float64
39426   -0.578794
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
Series([], Name: Value, dtype: float64)
64339    7.898250e+09
Name: Value, dtype: float64
64832    7.899990e+09
Name: Value, dtype: float64
65252    7.980790e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64340    8.234470e+09
Name: Value, dtype: float64
64833    8.431750e+09
Name: Value, dtype: float64
65253    8.510500e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64342    8.234470e+09
Name: Value, dtype: float64
64835    8.431750e+09
Name: Value, dtype: float64
65255    8.510500e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64341    7.833392e+09
Name: Value, dtype: float64
64834    7.835118e+09
Name: Value, dtype: float64
65254    7.915254e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64343    104.256892
Name: Value, dtype: float64
64836    106.731148
Name: Value, dtype: float64
65256    106.637313
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64344    2.217313
Name: Value, dtype: float64
64837    0.02203
Name: Value, dtype: float64
65257    1.022786
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64345    21035.565253
Name: Value, dtype: float64
64838    20736.547344
Name: Value, dtype: float64
65258    20663.546866
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64346    21209.732859
Name: Value, dtype: float64
64839    20908.23918
Name: Value, dtype: float64
65259    20834.634281
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64347    22112.608355
Name: Value, dtype: float64
64840    22315.603653
Name: Value, dtype: float64
65260    22217.494139
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64348    22112.608355
Name: Value, dtype: float64
64841    22315.603653
Name: Value, dtype: float64
65261    22217.494139
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64349    0.659025
Name: Value, dtype: float64
64842   -1.421487
Name: Value, dtype: float64
65262   -0.352038
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64350    22814.536713
Name: Value, dtype: float64
64843    22490.230949
Name: Value, dtype: float64
65263    22411.056842
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64351    23224.10902
Name: Value, dtype: float64
64844    23235.11389
Name: Value, dtype: float64
65264    23491.129584
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
64352    8.495860e+09
Name: Value, dtype: float64
64845    8.497731e+09
Name: Value, dtype: float64
65265    8.584645e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82199    1.109000e+09
Name: Value, dtype: float64
82599    1.109000e+09
Name: Value, dtype: float64
82949    1.111000e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82200    8.626000e+09
Name: Value, dtype: float64
82600    8.562000e+09
Name: Value, dtype: float64
82950    8.709000e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82202    4.313000e+09
Name: Value, dtype: float64
82602    4.281000e+09
Name: Value, dtype: float64
82952    4.354500e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82201    4.089241e+09
Name: Value, dtype: float64
82601    4.089241e+09
Name: Value, dtype: float64
82951    4.096615e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82203    777.817854
Name: Value, dtype: float64
82603    772.046889
Name: Value, dtype: float64
82953    783.888389
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82204    0.271248
Name: Value, dtype: float64
82604    0.0
Name: Value, dtype: float64
82954    0.180343
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82205    14522.483045
Name: Value, dtype: float64
82605    14475.03487
Name: Value, dtype: float64
82955    14456.261631
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82206    3938.48995
Name: Value, dtype: float64
82606    3925.622029
Name: Value, dtype: float64
82956    3920.530736
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82207    30634.278003
Name: Value, dtype: float64
82607    30307.642751
Name: Value, dtype: float64
82957    30732.585221
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82208    15317.139001
Name: Value, dtype: float64
82608    15153.821375
Name: Value, dtype: float64
82958    15366.292611
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82209   -0.07702
Name: Value, dtype: float64
82609   -0.326722
Name: Value, dtype: float64
82959   -0.129694
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82210    15389.687349
Name: Value, dtype: float64
82610    15339.405825
Name: Value, dtype: float64
82960    15319.51155
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82211    15665.966891
Name: Value, dtype: float64
82611    15847.451374
Name: Value, dtype: float64
82961    16057.816171
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
82213    4.333428e+09
Name: Value, dtype: float64
82613    4.333428e+09
Name: Value, dtype: float64
82963    4.341243e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110756    2.596031e+09
Name: Value, dtype: float64
111663    2.635638e+09
Name: Value, dtype: float64
112403    2.730081e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110757    3.147735e+09
Name: Value, dtype: float64
111664    3.248588e+09
Name: Value, dtype: float64
112404    3.398308e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110759    1.573867e+09
Name: Value, dtype: float64
111666    1.624294e+09
Name: Value, dtype: float64
112406    1.699154e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110758    1.341614e+09
Name: Value, dtype: float64
111665    1.362082e+09
Name: Value, dtype: float64
112405    1.410890e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110760    121.25182
Name: Value, dtype: float64
111667    123.256257
Name: Value, dtype: float64
112407    124.476463
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110761    3.824749
Name: Value, dtype: float64
111668    1.525675
Name: Value, dtype: float64
112408    3.583315
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110762    3984.514038
Name: Value, dtype: float64
111669    3957.321729
Name: Value, dtype: float64
112409    4011.561189
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110763    7710.058894
Name: Value, dtype: float64
111670    7657.44161
Name: Value, dtype: float64
112410    7762.395296
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110764    9348.586753
Name: Value, dtype: float64
111671    9438.275909
Name: Value, dtype: float64
112411    9662.355104
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110765    4674.293377
Name: Value, dtype: float64
111672    4719.137955
Name: Value, dtype: float64
112412    4831.177552
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110766    1.507781
Name: Value, dtype: float64
111673   -0.68245
Name: Value, dtype: float64
112413    1.37061
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110767    7975.693957
Name: Value, dtype: float64
111674    7921.263847
Name: Value, dtype: float64
112414    8029.833508
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110768    8118.875623
Name: Value, dtype: float64
111675    8183.618392
Name: Value, dtype: float64
112415    8416.82125
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
110769    2.685472e+09
Name: Value, dtype: float64
111676    2.726444e+09
Name: Value, dtype: float64
112416    2.824141e+09
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145899    3.603746e+10
Name: Value, dtype: float64
146820    3.848657e+10
Name: Value, dtype: float64
147631    4.058816e+10
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145900    1.871539e+11
Name: Value, dtype: float64
146821    2.118560e+11
Name: Value, dtype: float64
147632    2.280037e+11
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145902    2.708450e+10
Name: Value, dtype: float64
146823    3.065934e+10
Name: Value, dtype: float64
147634    3.299619e+10
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145901    1.322018e+10
Name: Value, dtype: float64
146822    1.411863e+10
Name: Value, dtype: float64
147633    1.488958e+10
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145903    519.33149
Name: Value, dtype: float64
146824    550.467428
Name: Value, dtype: float64
147635    561.749243
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145904    5.122275
Name: Value, dtype: float64
146825    6.796012
Name: Value, dtype: float64
147636    5.46057
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145905    1291.189517
Name: Value, dtype: float64
146826    1357.569323
Name: Value, dtype: float64
147637    1409.746646
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145906    3519.70873
Name: Value, dtype: float64
146827    3700.656283
Name: Value, dtype: float64
147638    3842.888681
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145907    18278.955796
Name: Value, dtype: float64
146828    20370.907461
Name: Value, dtype: float64
147639    21587.398066
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145908    2645.290274
Name: Value, dtype: float64
146829    2948.032918
Name: Value, dtype: float64
147640    3124.080762
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145909    3.474161
Name: Value, dtype: float64
146830    5.140981
Name: Value, dtype: float64
147641    3.843437
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145910    5793.069971
Name: Value, dtype: float64
146831    6090.890591
Name: Value, dtype: float64
147642    6324.990141
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145911    5897.068622
Name: Value, dtype: float64
146832    6292.622645
Name: Value, dtype: float64
147643    6629.815099
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
145915    5.931386e+10
Name: Value, dtype: float64
146834    6.334484e+10
Name: Value, dtype: float64
147645    6.680383e+10
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
181390    1.819417e+12
Name: Value, dtype: float64
182349    1.869337e+12
Name: Value, dtype: float64
183162    1.872042e+12
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
181391    4.713095e+12
Name: Value, dtype: float64
182350    5.157569e+12
Name: Value, dtype: float64
183163    5.521256e+12
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
181393    2.413136e+12
Name: Value, dtype: float64
182352    2.392082e+12
Name: Value, dtype: float64
183165    2.346076e+12
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
181392    1.172167e+12
Name: Value, dtype: float64
182351    1.204328e+12
Name: Value, dtype: float64
183164    1.206071e+12
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
181394    259.044203
Name: Value, dtype: float64
182353    275.903712
Name: Value, dtype: float64
183166    294.932328
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
181395    1.762489
Name: Value, dtype: float64
182354    2.743697
Name: Value, dtype: float64
183167    0.144707
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
181396    5791.295487
Name: Value, dtype: float64
182355    5896.072508
Name: Value, dtype: float64
183168    5852.49976
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
181397    8989.145487
Name: Value, dtype: float64
182356    9151.778508
Name: Value, dtype: float64
183169    9084.145666
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
181398    23285.860253
Name: Value, dtype: float64
182357    25250.096596
Name: Value, dtype: float64
183170    26792.082283
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
181399    11922.513058
Name: Value, dtype: float64
182358    11711.004404
Name: Value, dtype: float64
183171    11384.41501
Name: Value, dtype: float64
Series([], Name: Value, dtype: float64)
181400    0.81526
Name: Value, dtype: float64
182359    1.809216
Name: Value, dtype: float64
183172   -0.739013
Name: Value, dtype: float64